/* ref（速查手册）分类补强 5 —— 全部为真实参考数据 */
export default [
  {
    slug: 'dns-records', name: 'DNS 记录类型速查',
    desc: 'DNS 记录类型速查表：A/AAAA/CNAME/MX/TXT 等 16 种记录及用途。',
    keywords: 'dns记录,dns类型,域名记录,解析记录,ns记录,mx记录',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '记录', mono: true }, { key: 1, label: '说明' }, { key: 2, label: '用途' }],
      search: '输入记录（CNAME）或用途（邮件）过滤…', dense: true,
    },
    usage: '<ol><li>速查DNS 记录类型。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: 'D', a: 'N' }, { q: 'T', a: 'T' }],
  },
  {
    slug: 'tlds', name: '顶级域名速查',
    desc: '常见顶级域名速查表：.com/.cn/.io 等 34 个通用与国别顶级域。',
    keywords: '顶级域名,tld,域名后缀,.com,.cn,域名大全',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '后缀', mono: true }, { key: 1, label: '含义' }, { key: 2, label: '说明' }],
      search: '输入后缀（.io）或含义（中国）过滤…', dense: true,
    },
    usage: '<ol><li>速查顶级域名。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '顶', a: '级' }, { q: '.', a: 'i' }],
  },
  {
    slug: 'imperial-units', name: '英制单位换算',
    desc: '英制与公制单位换算速查：英寸、磅、加仑、华氏度等对照。',
    keywords: '英制单位,单位换算,英寸厘米,磅公斤,加仑升,华氏度',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '英制' }, { key: 1, label: '公制' }],
      search: '输入单位（加仑）或数值过滤…', dense: true,
    },
    usage: '<ol><li>速查英制单位换算。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '英', a: '制' }, { q: '美', a: '制' }],
  },
  {
    slug: 'lunar-festivals', name: '农历节日速查',
    desc: '中国农历节日速查表：春节、元宵、端午、中秋等节日日期。',
    keywords: '农历节日,传统节日,春节,中秋,端午,节日大全',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '节日' }, { key: 1, label: '日期' }, { key: 2, label: '说明' }],
      search: '输入节日（春节）或日期过滤…', dense: true,
    },
    usage: '<ol><li>速查农历节日。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '农', a: '历' }, { q: '清', a: '明' }],
  },
  {
    slug: 'math-constants', name: '数学常数速查',
    desc: '常用数学与物理常数：π、e、黄金比例、光速等精确值。',
    keywords: '数学常数,物理常数,圆周率,黄金比例,自然常数,科学常数',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '常数', mono: true }, { key: 1, label: '数值', mono: true }, { key: 2, label: '说明' }],
      search: '输入常数（π）或说明（光速）过滤…', dense: true,
    },
    usage: '<ol><li>速查数学常数。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: 'π', a: ' ' }, { q: '物', a: '理' }],
  },
  {
    slug: 'iso-langs', name: 'ISO 语言代码速查',
    desc: 'ISO 639 语言代码速查表：zh/en/ja 等 32 种语言代码。',
    keywords: '语言代码,iso639,语言标识,zh en,国际化,i18n',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '代码', mono: true }, { key: 1, label: '中文名' }, { key: 2, label: '英文名' }],
      search: '输入代码（zh）或语言（英语）过滤…', dense: true,
    },
    usage: '<ol><li>速查ISO 语言代码。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '语', a: '言' }, { q: '代', a: '码' }],
  },
  {
    slug: 'http-cache', name: 'HTTP 缓存头速查',
    desc: 'HTTP 缓存机制速查：Cache-Control、ETag、条件请求等。',
    keywords: 'http缓存,缓存头,cache-control,etag,缓存策略,浏览器缓存',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '头/指令', mono: true }, { key: 1, label: '类型' }, { key: 2, label: '说明' }],
      search: '输入头名（ETag）或用途（缓存）过滤…', dense: true,
    },
    usage: '<ol><li>速查HTTP 缓存头。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: 'C', a: 'a' }, { q: '缓', a: '存' }],
  },
  {
    slug: 'weather-symbols', name: '天气符号速查',
    desc: '天气符号大全：晴、雨、雪、雷等 20 个符号可复制。',
    keywords: '天气符号,天气图标,天气预报符号,天气表情,天气大全',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '符号' }, { key: 1, label: '含义' }],
      search: '输入符号（☀️）或含义（雨）过滤…', dense: true,
    },
    usage: '<ol><li>速查天气符号。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '天', a: '气' }, { q: '符', a: '号' }],
  },
  {
    slug: 'network-terms', name: '网络术语速查',
    desc: '网络基础术语速查：IP、DNS、TCP、CDN 等 24 个术语解释。',
    keywords: '网络术语,网络基础,ip地址,dns,tcp,网络知识',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '术语', mono: true }, { key: 1, label: '类型' }, { key: 2, label: '解释' }],
      search: '输入术语（DNS）或解释（加密）过滤…', dense: true,
    },
    usage: '<ol><li>速查网络术语。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '理', a: '解' }, { q: 'T', a: 'C' }],
  },
  {
    slug: 'zodiac-dates', name: '星座日期表',
    desc: '十二星座日期与元素速查：日期范围、四象属性与性格。',
    keywords: '星座日期,十二星座,星座表,星座属性,星座大全',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '星座' }, { key: 1, label: '日期' }, { key: 2, label: '元素' }, { key: 3, label: '性格' }],
      search: '输入星座（白羊）或日期过滤…', dense: true,
    },
    usage: '<ol><li>速查星座日期表。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '星', a: '座' }, { q: '四', a: '象' }],
  },
  {
    slug: 'shichen', name: '十二时辰表',
    desc: '古代十二时辰速查：时辰名称、对应时间与生肖。',
    keywords: '十二时辰,时辰表,子时,古代时间,天干地支时辰',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '时辰' }, { key: 1, label: '时间', mono: true }, { key: 2, label: '生肖' }, { key: 3, label: '说明' }],
      search: '输入时辰（子时）或时间（23）过滤…', dense: true,
    },
    usage: '<ol><li>速查十二时辰表。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '十', a: '二' }, { q: '子', a: '时' }],
  },
  {
    slug: 'key-symbols', name: '键盘符号速查',
    desc: '键盘特殊符号速查：~!@# 等符号的键位与输入方法。',
    keywords: '键盘符号,特殊符号键位,shift键,符号输入,键盘大全',
    category: 'ref', kind: 'table',
    table: {
      columns: [{ key: 0, label: '符号', mono: true }, { key: 1, label: '名称' }, { key: 2, label: '输入' }],
      search: '输入符号（@）或键位（Shift）过滤…', dense: true,
    },
    usage: '<ol><li>速查键盘符号。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>',
    faq: [{ q: '多', a: '数' }, { q: '中', a: '文' }],
  },
];
