/* D-Tool 工具批量生成器：把紧凑定义展开为 src/tools/<slug>.mjs
   运行：node scripts/gen-tools.mjs [分类...]   （省略参数 = 全部）
   手写工具（文件已存在且非生成）不会被覆盖；生成文件头部带标记，重新生成可覆盖。

   定义结构（见 scripts/tool-data/*.mjs）：
   { slug, name, desc, keywords, category,
     kind: 'table' | 'transform' | 'calc' | 'gen',
     table: { columns:[{key,label,render?}], search?, dense?, rows? },
     transform: { lib, fn, label?, auto?, multi?, placeholder?, outLabel?, hint?, params? },
     calc: { lib, fn, label?, unit?, hint?, inputs:[{label,value?,placeholder?,step?,min?}] },
     gen: { lib, fn, label?, batch?, hint?, params:[{name,label,type?,options?,value?,min?,max?}] },
     usage?, faq? }
*/
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const TOOLS_DIR = path.join(ROOT, 'src', 'tools');
const DATA_DIR = path.join(ROOT, 'scripts', 'tool-data');
const GEN_MARK = '/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */';

const esc = (s) => String(s ?? '').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const args = process.argv.slice(2);

/* ---------- 加载所有分类数据 ---------- */
const dataFiles = readdirSync(DATA_DIR).filter((f) => f.endsWith('.mjs')).sort();
let tools = [];
for (const f of dataFiles) {
  const mod = await import(pathToFileURL(path.join(DATA_DIR, f)).href);
  tools = tools.concat(mod.default || []);
}
if (args.length) {
  tools = tools.filter((t) => args.includes(t.category));
  if (!tools.length) { console.error('没有匹配的工具定义'); process.exit(1); }
}
console.log(`加载 ${tools.length} 条定义（${args.length ? args.join(',') : '全部'}）`);

/* ---------- 渲染各 kind 的 body ---------- */
function renderTable(t) {
  const { columns } = t.table;
  const head = `<thead><tr>${columns.map((c) => `<th>${c.label}</th>`).join('')}</tr></thead>`;
  const bodyRows = `<tbody>${t.table.rows ? t.table.rows.map((r) => renderRow(r, columns)).join('\n') : '<!-- rows from tools-table.mjs -->'}</tbody>`;
  return `<div class="table-wrap${t.table.dense ? ' table-dense' : ''}" id="tb-wrap">
  <table class="data" id="tb-table">${head}${bodyRows}</table>
</div>
<div class="table-count" id="tb-count"></div>`;
}
function renderRow(r, columns) {
  return `<tr>${columns.map((c) => `<td>${c.render ? c.render(r[c.key]) : esc(r[c.key])}</td>`).join('')}</tr>`;
}

function renderTransform(t) {
  const x = t.transform;
  const actions = x.actions || [{ label: x.label || '转换', fn: x.fn }];
  const params = (x.params || []).map((p, i) => {
    const opts = (p.options || []).map(([v, label]) => `<option value="${esc(v)}"${v === p.value ? ' selected' : ''}>${esc(label)}</option>`).join('');
    return p.type === 'select'
      ? `<div class="field"><label for="xp-${i}">${p.label}</label><select id="xp-${i}">${opts}</select></div>`
      : `<div class="field"><label for="xp-${i}">${p.label}</label><input type="number" id="xp-${i}" value="${p.value ?? ''}"${p.min != null ? ` min="${p.min}"` : ''}></div>`;
  }).join('');
  const buttons = actions.map((a, i) => `<button id="x-run-${i}" class="btn${i === 0 ? '' : ' btn-ghost'}" data-fn="${a.fn}">${a.label}</button>`).join('');
  return `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="${esc(x.placeholder || '在此输入内容')}"></textarea>
</div>
${params}
<div class="toolbar">
  ${buttons}
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">${x.outLabel || '输出结果'}</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>
${x.hint ? `<div class="note">${x.hint}</div>` : ''}
<script type="application/json" id="x-cfg">{"lib":"${x.lib}","actions":${JSON.stringify(actions.map((a) => ({ label: a.label, fn: a.fn })))},"multi":${!!x.multi},"auto":${!!x.auto},"params":${JSON.stringify((x.params || []).map((p) => ({ name: p.name, type: p.type })))}}</script>`;
}

function renderCalc(t) {
  const c = t.calc;
  const inputs = (c.inputs || []).map((f, i) => {
    if (f.type === 'select') {
      const opts = (f.options || []).map(([v, label]) => `<option value="${esc(v)}"${v === f.value ? ' selected' : ''}>${esc(label)}</option>`).join('');
      return `<div class="field"><label for="ci-${i}">${f.label}</label><select id="ci-${i}">${opts}</select></div>`;
    }
    if (f.type === 'date') {
      return `<div class="field"><label for="ci-${i}">${f.label}</label><input type="date" id="ci-${i}" value="${f.value ?? ''}"></div>`;
    }
    if (f.type === 'text' || f.type === 'textarea') {
      return `<div class="field"><label for="ci-${i}">${f.label}</label>${f.type === 'textarea'
        ? `<textarea id="ci-${i}" rows="${f.rows || 3}">${f.value ?? ''}</textarea>`
        : `<input type="text" id="ci-${i}" value="${f.value ?? ''}" placeholder="${esc(f.placeholder || '')}">`}</div>`;
    }
    return `<div class="field">
  <label for="ci-${i}">${f.label}</label>
  <input type="number" id="ci-${i}" value="${f.value ?? ''}" placeholder="${esc(f.placeholder || '')}"${f.step ? ` step="${f.step}"` : ''}${f.min != null ? ` min="${f.min}"` : ''}>
</div>`;
  }).join('');
  return `<div class="calc-form">
${inputs}
</div>
<div class="toolbar">
  <button id="c-run" class="btn">${c.label || '计算'}</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
${c.hint ? `<div class="note">${c.hint}</div>` : ''}
<script type="application/json" id="c-cfg">{"lib":"${c.lib}","fn":"${c.fn}","unit":"${esc(c.unit || '')}"}</script>`;
}

function renderGen(t) {
  const g = t.gen;
  const params = (g.params || []).map((p, i) => {
    const opts = (p.options || []).map(([v, label]) => `<option value="${esc(v)}"${v === p.value ? ' selected' : ''}>${esc(label)}</option>`).join('');
    if (p.type === 'select') return `<div class="field"><label for="gp-${i}">${p.label}</label><select id="gp-${i}">${opts}</select></div>`;
    if (p.type === 'range') return `<div class="field"><label for="gp-${i}" class="field-label">${p.label}</label><input type="range" id="gp-${i}" min="${p.min ?? 0}" max="${p.max ?? 100}" value="${p.value ?? 50}"><span class="range-val" id="gp-${i}-val"></span></div>`;
    return `<div class="field"><label for="gp-${i}">${p.label}</label><input type="number" id="gp-${i}" value="${p.value ?? ''}" min="${p.min ?? ''}"></div>`;
  }).join('');
  return `<div class="row">
${params || '<div class="field grow"></div>'}
</div>
<div class="toolbar">
  <button id="g-run" class="btn">${g.label || '生成'}</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
${g.hint ? `<div class="note">${g.hint}</div>` : ''}
<script type="application/json" id="g-cfg">{"lib":"${g.lib}","fn":"${g.fn}","multi":${!!g.multi},"batch":${g.batch || 1}}</script>`;
}

/* ---------- 生成文件 ---------- */
let generated = 0, skipped = 0;
for (const t of tools) {
  const outPath = path.join(TOOLS_DIR, `${t.slug}.mjs`);
  const isGenerated = existsSync(outPath) && readFileSync(outPath, 'utf8').startsWith(GEN_MARK);
  if (existsSync(outPath) && !isGenerated) { skipped++; continue; }

  const body = t.body || (t.kind === 'table' ? '' : t.kind === 'transform' ? renderTransform(t)
    : t.kind === 'calc' ? renderCalc(t)
    : t.kind === 'gen' ? renderGen(t)
    : (() => { throw new Error(`工具 ${t.slug} 缺少 kind/body`); })());
  const usage = t.usage || `<ol>
  <li>打开工具页面，按要求输入内容或调整参数。</li>
  <li>点击“${t.kind === 'gen' ? '生成' : t.kind === 'calc' ? '计算' : '转换'}”按钮查看结果，支持一键复制。</li>
  <li>全部处理都在浏览器本地完成，数据不会上传服务器。</li>
</ol>`;
  const faq = t.faq || [
    { q: '这个工具需要联网吗？', a: '不需要。所有计算都在您的浏览器本地完成，输入内容不会离开设备，可放心处理敏感数据。' },
    { q: '结果可以直接复制使用吗？', a: '可以。点击结果下方的“复制结果”按钮即可复制到剪贴板，也可手动选中内容复制。' },
  ];

  const mjs = `${GEN_MARK}
export default {
  slug: '${t.slug}',
  name: '${esc(t.name)}',
  desc: '${esc(t.desc)}',
  keywords: '${esc(t.keywords)}',
  category: '${t.category}',
  kind: '${t.kind}',
  ${t.script ? `script: '${t.script}',` : ''}
  ${t.kind === 'table' ? `table: { columns: ${JSON.stringify(t.table.columns.map((c) => ({ key: c.key, label: c.label, swatch: !!c.swatch, mono: !!c.mono })))}, search: ${t.table.search === false ? 'false' : JSON.stringify(t.table.search ?? true)}, dense: ${!!t.table.dense} },` : ''}
  body: \`${body}\`,
  usage: \`${esc(usage)}\`,
  faq: ${JSON.stringify(faq).replace(/</g, '\\u003c')},
};
`;
  writeFileSync(outPath, mjs);
  generated++;
}
console.log(`生成 ${generated} 个工具文件，跳过 ${skipped} 个手写工具`);
