/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'acrostic-poem',
  name: '藏头诗生成',
  desc: '藏头诗生成器：输入几个字，自动生成藏头诗句，表白祝福神器。',
  keywords: '藏头诗,藏头诗生成,藏头诗在线,表白藏头诗,祝福藏头诗,作诗',
  category: 'life',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入藏头文字，如：我喜欢你"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="acrosticPoem">生成藏头诗</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">藏头诗</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"life","actions":[{"label":"生成藏头诗","fn":"acrosticPoem"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入要藏头的文字（如“我喜欢你”），点击“生成藏头诗”。</li>
  <li>每行首字即你输入的文字，诗句取自古诗意境库。</li>
  <li>表白、生日祝福、纪念日文案都适用。</li>
</ol>`,
  faq: [{"q":"诗句是原创吗？","a":"由经典诗句意象库组合生成（如“春风送暖入屠苏”），非严格格律诗，重在意境。"},{"q":"支持几个字？","a":"任意长度均可；建议 4-8 字效果最佳（每字一行）。"}],
};
