/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'adler32',
  name: 'Adler-32 校验',
  desc: 'Adler-32 校验值计算：zlib 使用的 32 位校验算法，比 CRC32 更快。',
  keywords: 'adler32,adler校验,zlib校验,快速校验,滚动校验',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本计算 Adler-32"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="adler32">计算 Adler-32</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">Adler-32</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"计算 Adler-32","fn":"adler32"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本点击“计算 Adler-32”，得到 8 位十六进制校验值。</li>
  <li>zlib 压缩格式用它做二级校验，也用于快速检测数据损坏。</li>
  <li>与 CRC32 参数一致（Python zlib.adler32 同款）。</li>
</ol>`,
  faq: [{"q":"Adler-32 和 CRC32 哪个好？","a":"Adler-32 计算更快但碰撞更差（对短数据与连续数据不敏感），CRC32 检错能力更强；zlib 选择 Adler-32 是速度与实现简单的折中。"},{"q":"值域多大？","a":"Adler-32 基于 65521 取模的两段累加（a、b 各 16 位），输出 32 位。"},{"q":"与 CRC32 结果能互换吗？","a":"不能。两者算法完全不同，同一个文本得到的校验值不同，校验时必须使用与对方一致的算法。"}],
};
