/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'aes-encrypt',
  name: 'AES 加解密',
  desc: 'AES-256-GCM 文本加解密：密码派生密钥，本地加密，输出 Base64。',
  keywords: 'aes加密,aes解密,文本加密,对称加密,gcm加密,本地加密',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入明文或 Base64 密文"></textarea>
</div>
<div class="field"><label for="xp-0">密码</label><input type="number" id="xp-0" value=""></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="aesEncrypt">加密</button><button id="x-run-1" class="btn btn-ghost" data-fn="aesDecrypt">解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"加密","fn":"aesEncrypt"},{"label":"解密","fn":"aesDecrypt"}],"multi":false,"auto":false,"params":[{"name":"password","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写密码，输入文本。</li>
  <li>“加密”：AES-256-GCM 加密（密码经 PBKDF2 派生密钥），输出 Base64（含随机 IV）。</li>
  <li>“解密”：粘贴密文与相同密码还原；密码错误会提示。</li>
</ol>`,
  faq: [{"q":"安全吗？","a":"使用 WebCrypto 标准 AES-256-GCM，密码经 1 万次 PBKDF2 派生；加密强度取决于密码强度。"},{"q":"换设备能解密吗？","a":"可以，密文是自包含的（含 IV），任何支持 AES-GCM 的工具用相同密码都能解密。"},{"q":"密码忘了怎么办？","a":"无法找回，AES 没有后门；请妥善保管密码。"}],
};
