/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'affine',
  name: '仿射密码',
  desc: '仿射密码加密/解密：y = (ax + b) mod 26 线性变换，带密钥的古典单表替换密码。',
  keywords: '仿射密码,affine,线性密码,单表替换,古典密码,数学密码',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入明文或密文"></textarea>
</div>
<div class="field"><label for="xp-0">乘数 a（与 26 互质）</label><input type="number" id="xp-0" value="5"></div><div class="field"><label for="xp-1">偏移 b</label><input type="number" id="xp-1" value="8"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="affineCipher">加密</button><button id="x-run-1" class="btn btn-ghost" data-fn="affineDecode">解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"加密","fn":"affineCipher"},{"label":"解密","fn":"affineDecode"}],"multi":false,"auto":false,"params":[{"name":"a","type":"number"},{"name":"b","type":"number"}]}</script>`,
  usage: `<ol>
  <li>设置乘数 a 与偏移 b，输入文本。</li>
  <li>加密：y = (a·x + b) mod 26；解密需要 a 与 26 互质（1,3,5,7,9,11,15,17,19,21,23,25）。</li>
  <li>a 决定替换表“斜度”，b 决定起点偏移，组合出 312 种替换表。</li>
</ol>`,
  faq: [{"q":"为什么 a 必须与 26 互质？","a":"解密需要求 a 的模逆元，只有 a 与 26 互质时逆元才存在；否则多个字母会映射到同一个密文字母，无法还原。"},{"q":"仿射密码有多少种组合？","a":"a 有 12 种选择（1-25 中与 26 互质的数），b 有 26 种，共 312 种替换表；暴力穷举很快，只适合教学与谜题。"},{"q":"凯撒密码和仿射密码的关系？","a":"凯撒是仿射密码的特例（a=1），只做平移；仿射增加了乘法变换，两者都属于单表替换。"}],
};
