/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'age-calc',
  name: '年龄计算器',
  desc: '年龄计算器：出生日期一键算出周岁、总天数、下次生日倒计时与星期。',
  keywords: '年龄计算器,周岁计算,年龄查询,出生日期,生日倒计时,活了多少天',
  category: 'date',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">出生日期</label><input type="date" id="ci-0" value="2000-01-01"></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输入出生日期，输出周岁（年/月/天）、累计天数与距下次生日天数。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"ageCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择出生日期，点击“计算”。</li>
  <li>得到周岁（精确到天）、累计活了多少天、距下次生日还有几天。</li>
  <li>办理证件、报名考试、统计年龄结构都适用。</li>
</ol>`,
  faq: [{"q":"周岁和虚岁有什么区别？","a":"周岁按公历生日精确计算；虚岁传统上出生即 1 岁、过年加 1 岁。本工具按周岁（国际通用）计算。"},{"q":"闰年 2 月 29 日出生怎么算？","a":"非闰年时按 2 月 28 日或 3 月 1 日处理（不同地区惯例不同），本工具按 2 月 28 日计算。"}],
};
