/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'align-columns',
  name: '文本分列对齐',
  desc: '文本分列对齐：按分隔符拆列并空格对齐，整理表格数据。',
  keywords: '分列对齐,文本对齐,列对齐,制表符分列,表格整理,对齐工具',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入表格数据（每行一条记录）"></textarea>
</div>
<div class="field"><label for="xp-0">分隔符</label><select id="xp-0"><option value="	" selected>制表符 Tab</option><option value=",">逗号 ,</option><option value=" ">空格</option><option value="|">竖线 |</option></select></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="splitColumns">对齐</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">对齐结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"对齐","fn":"splitColumns"}],"multi":false,"auto":false,"params":[{"name":"sep","type":"select"}]}</script>`,
  usage: `<ol>
  <li>选择分隔符（Tab/逗号/空格/竖线），粘贴多行数据。</li>
  <li>每列按最大宽度补空格对齐，输出整齐的表格文本。</li>
  <li>从终端或日志中整理字段常用。</li>
</ol>`,
  faq: [{"q":"中文宽度对齐吗？","a":"按字符数对齐（非显示宽度）；中英文混排时视觉可能略不齐，属正常。"},{"q":"空列怎么处理？","a":"缺失列以空串补齐，保持每行列数一致。"}],
};
