/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'array-tools',
  name: '数组处理工具',
  desc: '数组处理：去重、排序、反转、频次统计，逗号/空格分隔输入。',
  keywords: '数组去重,数组排序,数组工具,列表处理,元素统计,array tools',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入元素，空格/逗号/分号分隔，如：a b c a b"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="arrayToolsUnique">去重</button><button id="x-run-1" class="btn btn-ghost" data-fn="arrayToolsSort">排序</button><button id="x-run-2" class="btn btn-ghost" data-fn="arrayToolsReverse">反转</button><button id="x-run-3" class="btn btn-ghost" data-fn="arrayToolsCount">频次统计</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev4","actions":[{"label":"去重","fn":"arrayToolsUnique"},{"label":"排序","fn":"arrayToolsSort"},{"label":"反转","fn":"arrayToolsReverse"},{"label":"频次统计","fn":"arrayToolsCount"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol><li>输入数组元素（空格/逗号/分号分隔），选择操作。</li><li>去重保留首次顺序；排序按中文/数字自然序；频次按“元素: 次数”输出。</li><li>标签去重、列表整理、数据清洗常用。</li></ol>`,
  faq: [{"q":"排序规则？","a":"按 Unicode/中文拼音自然排序（数字按数值）。"},{"q":"能处理数字吗？","a":"能，元素按字符串处理；纯数字也会正确排序。"}],
};
