/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ascii-table',
  name: 'ASCII 字符表',
  desc: '完整 ASCII 码表速查：0-127 全部字符的十进制、十六进制、二进制与中文含义。',
  keywords: 'ascii码表,ascii表,字符编码表,ascii对照表,ascii大全,控制字符',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":"code","label":"十进制","swatch":false,"mono":false},{"key":"hex","label":"十六进制","swatch":false,"mono":false},{"key":"char","label":"字符","swatch":false,"mono":false},{"key":"bin","label":"二进制","swatch":false,"mono":false},{"key":"desc","label":"含义","swatch":false,"mono":false}], search: "输入码值（65）、十六进制（0x41）或字符过滤…", dense: true },
  body: ``,
  usage: `<ol>
  <li>表格列出 ASCII 0-127 全部字符：控制字符（0-31、127）给出标准名称，可打印字符直接显示。</li>
  <li>在搜索框输入十进制码值（如 65）、十六进制（0x41）、实际字符（如 A）或含义关键词即可过滤。</li>
  <li>适合调试字符编码问题、理解协议报文中的控制字符。</li>
</ol>`,
  faq: [{"q":"ASCII 只有 128 个字符吗？","a":"是的。标准 ASCII 是 0-127 共 128 个字符，其中 0-31 和 127 是控制字符（换行、回车、退格等），32-126 是可打印字符（空格、数字、字母、符号）。"},{"q":"为什么二进制列是 8 位？","a":"标准 ASCII 只用 7 位（0-127），但存储时占一个字节，高位为 0，所以显示为 8 位便于对照字节值。"},{"q":"中文用什么编码表示？","a":"中文不在 ASCII 范围内。UTF-8 中一个汉字占 3 个字节，码点远大于 127；需要转换可用本站“ASCII 与字符互转”工具。"}],
};
