/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'aspect-ratio',
  name: '屏幕长宽比计算',
  desc: '屏幕长宽比计算：宽高像素求最简比例（16:9、4:3 等），设计切图常用。',
  keywords: '长宽比,宽高比,16比9,4比3,屏幕比例,图片比例,aspect ratio',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">宽（像素）</label>
  <input type="number" id="ci-0" value="1920" placeholder="">
</div><div class="field">
  <label for="ci-1">高（像素）</label>
  <input type="number" id="ci-1" value="1080" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">如 1920×1080 → 16:9；支持任意宽高。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"aspectRatioCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入图片/屏幕的宽与高（像素），点击“计算”。</li>
  <li>得到最简整数比例与宽高比值。</li>
  <li>设计切图、视频制作、海报排版常用。</li>
</ol>`,
  faq: [{"q":"1920×1080 为什么是 16:9？","a":"1920 和 1080 的最大公约数是 120，各除以 120 得 16 和 9。"},{"q":"非整数比例怎么办？","a":"取整近似，如 1.414:1 显示为约 99:70；比值列给出精确小数。"}],
};
