/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'atbash',
  name: 'Atbash 密码',
  desc: 'Atbash 替换密码：字母表首尾对调（A↔Z、B↔Y），经典希伯来密码，可解密还原。',
  keywords: 'atbash,埃特巴什,替换密码,字母反序,古典密码,字母表对调',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要处理的文本（自逆变换）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="atbash">加密/解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"加密/解密","fn":"atbash"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本点击按钮：A↔Z、B↔Y 依次对调，字母大小写保持。</li>
  <li>Atbash 是自逆变换，同一按钮加密与解密。</li>
  <li>源自希伯来语，后用于《圣经》密码与古典文学谜题。</li>
</ol>`,
  faq: [{"q":"Atbash 安全吗？","a":"不安全，它只有一种固定映射且没有密钥，属于教学用古典密码，现代密码学早已弃用。"},{"q":"怎么还原？","a":"再次执行 Atbash 即可还原：对调两次等于原样。"},{"q":"非字母字符怎么处理？","a":"数字、空格、标点与中文全部保留原样，只对 26 个英文字母生效。"}],
};
