/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'bacon',
  name: '培根密码',
  desc: '培根密码编解码：每个字母用 5 位 A/B（或 0/1）表示，可隐藏在普通文本中。',
  keywords: '培根密码,bacon,培根cipher,ab密码,隐写,古典密码',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入字母文本或 A/B 序列"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="baconEncode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="baconDecode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"编码","fn":"baconEncode"},{"label":"解码","fn":"baconDecode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“编码”：输入英文（仅 A-Z），每个字母输出 5 位 A/B 码，如 A=AAAAA、B=AAAAB。</li>
  <li>“解码”：输入 A/B 序列（可含空格），每 5 位还原一个字母；I/J、U/V 共用一组码。</li>
  <li>可把 A/B 映射为两种字体的文本做隐写（经典用法）。</li>
</ol>`,
  faq: [{"q":"培根密码的原理？","a":"培根（Francis Bacon）提出用 5 位二元码表示字母（2^5=32 种组合），可通过两种视觉差异（如字体、粗细）隐藏信息。"},{"q":"I 和 J 怎么区分？","a":"本实现按古典培根密码约定 I/J 与 U/V 共用同一码组，解码时统一还原为 I 和 U；现代变体可用 26 个独立码。"},{"q":"能隐藏中文吗？","a":"不能直接隐藏，需先把中文转成拼音或 Unicode 码点再编码；本工具仅处理 A-Z。"}],
};
