/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'base58',
  name: 'Base58 编码',
  desc: 'Base58 编码/解码（比特币字母表），去除易混淆字符 0/O/I/l，常用于地址与短 ID。',
  keywords: 'base58,base58编码,base58解码,比特币地址,base58check,短id',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或 Base58 字符串"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="base58Encode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="base58Decode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"编码","fn":"base58Encode"},{"label":"解码","fn":"base58Decode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入任意文本，点击“编码”得到 Base58；粘贴 Base58 串点击“解码”还原。</li>
  <li>Base58 字符集为 1-9、A-H、J-N、P-Z、a-k、m-z（去掉了 0、O、I、l 四个易混淆字符）。</li>
  <li>比特币地址、IPFS CID、部分短链接服务都使用 Base58。</li>
</ol>`,
  faq: [{"q":"Base58 和 Base64 有什么区别？","a":"Base58 去掉了 0/O/I/l 等易混淆字符，也不含 +/ 符号，方便人工抄写和语音传达；代价是体积略大（约膨胀 27%）。"},{"q":"Base58Check 是什么？","a":"Base58Check 是在 Base58 前附加 4 字节校验（对原数据做两次 SHA-256 取前 4 字节），比特币地址就是 Base58Check 编码。"},{"q":"支持中文吗？","a":"支持。编码按 UTF-8 处理，中文、emoji 都能正确编码与还原。"}],
};
