/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'base91',
  name: 'Base91 编码',
  desc: 'Base91 编码/解码：使用 91 个可打印字符，膨胀率约 23%，比 Base64 更省空间。',
  keywords: 'base91,base91编码,base91解码,紧凑编码,二进制转文本',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或 Base91 字符串"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="base91Encode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="base91Decode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"编码","fn":"base91Encode"},{"label":"解码","fn":"base91Decode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本点击“编码”，粘贴 Base91 串点击“解码”。</li>
  <li>Base91 使用 91 个可打印字符（不含空格与易混淆字符），编码效率接近理论极限。</li>
  <li>常用于对体积敏感的文本化二进制传输。</li>
</ol>`,
  faq: [{"q":"为什么叫 Base91 而不是 Base85/95？","a":"可打印 ASCII 字符约 95 个，去掉空格等后可用 91 个；91 = 2^13 的近似最优基，13 比特可编码 8192 个值，利用率高于 Base64。"},{"q":"比 Base64 省多少？","a":"Base91 膨胀率约 23%，Base64 约 33%，同样数据 Base91 更短；代价是编解码稍复杂。"},{"q":"支持中文吗？","a":"支持，统一按 UTF-8 字节流处理，与编码文本的语言无关。"}],
};
