/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'base62',
  name: 'Base62 编码',
  desc: 'Base62 编码/解码（0-9a-zA-Z）：短链接、邀请码场景常用的紧凑编码。',
  keywords: 'base62,base62编码,base62解码,短链编码,邀请码,url安全编码',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或 Base62 字符串"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="base62Encode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="base62Decode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"编码","fn":"base62Encode"},{"label":"解码","fn":"base62Decode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本点击“编码”得到 Base62；粘贴 Base62 串点击“解码”。</li>
  <li>字符集为 0-9、A-Z、a-z 共 62 个 URL 安全字符。</li>
  <li>短链接系统、邀请码、数据库 ID 混淆常用。</li>
</ol>`,
  faq: [{"q":"Base62 和 Base64 什么区别？","a":"Base62 不含 + / = 等需转义字符，可直接放入 URL；体积比 Base64 略大（约 38% 膨胀）。"},{"q":"适合什么场景？","a":"短链 ID、邀请码、优惠码等需要“短 + URL 安全”的标识场景。"}],
};
