/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'base36',
  name: 'Base36 编码',
  desc: 'Base36 编码/解码（0-9a-z）：字母数字混合的紧凑编码，短 ID 常用。',
  keywords: 'base36,base36编码,base36解码,短id,36进制,邀请码',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或 Base36 字符串"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="base36Encode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="base36Decode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"编码","fn":"base36Encode"},{"label":"解码","fn":"base36Decode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本点击“编码”；粘贴 Base36 串点击“解码”。</li>
  <li>字符集为 0-9、a-z 共 36 个，全部小写可读性更好。</li>
  <li>短 ID、优惠码、注册码场景常用。</li>
</ol>`,
  faq: [{"q":"和 36 进制转换一样吗？","a":"本质上都是 36 进制，但本工具按 UTF-8 字节流编码任意文本（含中文），而进制转换工具处理数字。"},{"q":"大小写敏感吗？","a":"解码时大小写不敏感（统一按小写处理）；编码输出小写。"}],
};
