/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'base85',
  name: 'Base85 编码',
  desc: 'Base85（RFC 1924）编码/解码，与 Python base64.b85 完全兼容，比 Base64 更紧凑。',
  keywords: 'base85,ascii85,rfc1924,base85编码,base85解码,python b85',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或 Base85 字符串"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="base85Encode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="base85Decode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"编码","fn":"base85Encode"},{"label":"解码","fn":"base85Decode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本点击“编码”，粘贴 Base85 串点击“解码”。</li>
  <li>本实现遵循 RFC 1924 字母表，与 Python 标准库 base64.b85encode/b85decode 输出一致。</li>
  <li>Base85 每 4 字节输出 5 字符，膨胀率约 25%，比 Base64（33%）更紧凑。</li>
</ol>`,
  faq: [{"q":"Base85 和 Ascii85 一样吗？","a":"不同。Ascii85（Adobe）用 \u003c~ ~> 包裹且使用不同的字母表；本工具实现的是 RFC 1924，对应 Python 的 b85。"},{"q":"为什么输出里有特殊符号？","a":"RFC 1924 字母表包含 85 个字符：数字、大小写字母加 !#$%&()*+-;\u003c=>?@^_`{|}~ 等符号，属正常现象。"},{"q":"适合什么场景？","a":"需要紧凑文本传输的二进制场景，如嵌入 URL 参数、配置文件存储二进制数据；解压文件时也要配套解码。"}],
};
