/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'bill-split',
  name: 'AA 账单分摊',
  desc: '聚餐 AA 分摊计算：总金额、人数、小费比例 → 人均应付。',
  keywords: 'aa分摊,账单分摊,AA制,人均消费,小费计算,聚餐计算器',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">总金额（元）</label>
  <input type="number" id="ci-0" value="456" placeholder="">
</div><div class="field">
  <label for="ci-1">人数</label>
  <input type="number" id="ci-1" value="4" placeholder="">
</div><div class="field">
  <label for="ci-2">小费/服务费（%）</label>
  <input type="number" id="ci-2" value="0" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">小费填 0-100，如服务费 10% 填 10。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"billSplit","unit":""}</script>`,
  usage: `<ol>
  <li>输入账单总金额、分摊人数与可选的小费比例，点击“计算”。</li>
  <li>输出小费金额、总支付额与人均应付。</li>
  <li>聚餐、旅行拼房、团购分摊都适用。</li>
</ol>`,
  faq: [{"q":"怎么处理某人不吃某些菜？","a":"本工具按平均分摊；有差异时建议先减去对应金额再输入总数。"},{"q":"小费比例含税吗？","a":"小费按总金额 × 比例计算，不含税；含税场景请先输入含税总额。"}],
};
