/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'blood-match',
  name: '血型配对',
  desc: '血型配对测试：输入两人血型查看趣味契合度评价。',
  keywords: '血型配对,血型测试,血型性格,血型缘分,血型速配',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">血型一</label><select id="ci-0"><option value="A" selected>A 型</option><option value="B">B 型</option><option value="AB">AB 型</option><option value="O">O 型</option></select></div><div class="field"><label for="ci-1">血型二</label><select id="ci-1"><option value="A">A 型</option><option value="B">B 型</option><option value="AB">AB 型</option><option value="O" selected>O 型</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按流行“血型性格论”的组合评价，纯属娱乐。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"bloodMatch","unit":""}</script>`,
  usage: `<ol>
  <li>选择两个血型，点击“计算”。</li>
  <li>查看组合评价（如 A×O 守护组合）。</li>
  <li>血型性格论缺乏科学依据，图个乐。</li>
</ol>`,
  faq: [{"q":"血型和性格有关吗？","a":"现代心理学认为血型与性格无显著关联，本工具仅为流行文化的趣味参考。"},{"q":"输入真实血型安全吗？","a":"所有计算在本地完成，不存储不上传；但仍建议不要随意公开个人血型。"}],
};
