/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'bmr-calc',
  name: 'BMR 基础代谢计算',
  desc: '基础代谢率（BMR）与每日热量需求计算，健身减脂增肌参考。',
  keywords: '基础代谢,bmr,热量需求,每日热量,减脂热量,增肌热量,tdee',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">性别</label><select id="ci-0"><option value="male" selected>男</option><option value="female">女</option></select></div><div class="field">
  <label for="ci-1">体重（公斤）</label>
  <input type="number" id="ci-1" value="65" placeholder="" step="any">
</div><div class="field">
  <label for="ci-2">身高（厘米）</label>
  <input type="number" id="ci-2" value="170" placeholder="">
</div><div class="field">
  <label for="ci-3">年龄</label>
  <input type="number" id="ci-3" value="30" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">Mifflin-St Jeor 公式：男 10×kg+6.25×cm-5×age+5，女 -161。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"bmrCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入性别、体重、身高与年龄，点击“计算”。</li>
  <li>输出 BMR（静息热量消耗）与 5 档活动水平下的每日维持热量。</li>
  <li>减脂（-300~500 千卡）、增肌（+200~300 千卡）以此为基准调整。</li>
</ol>`,
  faq: [{"q":"BMR 和 TDEE 什么区别？","a":"BMR 是躺着不动的基础消耗；TDEE = BMR × 活动系数（久坐 1.2 到极高 1.9），才是每日总消耗。"},{"q":"减脂每天吃多少？","a":"建议 TDEE - 300~500 千卡并保证蛋白质充足；低于 BMR 长期执行会掉代谢，需谨慎。"}],
};
