/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'body-fat',
  name: '体脂率估算',
  desc: '体脂率估算（海军公式）：输入围度估算体脂率与评级。',
  keywords: '体脂率,体脂计算,海军公式,体脂估算,围度计算,健康指标',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">性别</label><select id="ci-0"><option value="male" selected>男</option><option value="female">女</option></select></div><div class="field">
  <label for="ci-1">腰围（cm）</label>
  <input type="number" id="ci-1" value="80" placeholder="">
</div><div class="field">
  <label for="ci-2">颈围（cm）</label>
  <input type="number" id="ci-2" value="38" placeholder="">
</div><div class="field">
  <label for="ci-3">身高（cm）</label>
  <input type="number" id="ci-3" value="175" placeholder="">
</div><div class="field">
  <label for="ci-4">臀围（cm，女性填）</label>
  <input type="number" id="ci-4" value="95" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">海军体脂公式，误差 ±3%；男性不需臀围。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"bodyFatCalc","unit":""}</script>`,
  usage: `<ol><li>测量并输入腰围、颈围、身高（女性加臀围）。</li><li>点击“计算”得到体脂率估算与评级。</li><li>健身监测、减脂进度评估参考。</li></ol>`,
  faq: [{"q":"怎么量腰围？","a":"自然站立，呼气末绕肚脐水平一周；皮尺贴皮肤不勒紧。"},{"q":"体脂率多少正常？","a":"男性健康 14-17%，女性 21-24%；运动员更低属正常。"}],
};
