/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'body-measure',
  name: '三围比例参考',
  desc: '三围比例参考：按身高与性别估算美学比例（胸腰臀）。',
  keywords: '三围比例,标准三围,胸围腰围臀围,身材比例,形体参考',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">性别</label><select id="ci-0"><option value="female" selected>女</option><option value="male">男</option></select></div><div class="field">
  <label for="ci-1">身高（cm）</label>
  <input type="number" id="ci-1" value="165" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">为大众审美比例参考，健康第一。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"bodyMeasureCalc","unit":""}</script>`,
  usage: `<ol><li>输入性别与身高，点击“计算”。</li><li>得到参考胸围、腰围、臀围。</li><li>健身塑形、服装定制参考。</li></ol>`,
  faq: [{"q":"这是标准吗？","a":"不是硬标准，仅为常见美学比例；个体差异极大，无需强求。"},{"q":"腰臀比更健康？","a":"健康维度看腰臀比（男\u003c0.9 女\u003c0.85），比三围绝对值更重要。"}],
};
