/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'bracket-check',
  name: '括号匹配检查',
  desc: '括号匹配检查：检测 ()、[]、{}、中文括号是否配对闭合。',
  keywords: '括号匹配,括号检查,括号校验,代码检查,括号配对,语法检查',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴含括号的代码或文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="bracketCheck">检查</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">检查结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"convert3","actions":[{"label":"检查","fn":"bracketCheck"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴代码，点击“检查”。</li>
  <li>检测 () [] {} 及中文括号的配对与闭合。</li>
  <li>发现未闭合或错配时提示具体行号。</li>
</ol>`,
  faq: [{"q":"能检查字符串里的括号吗？","a":"不区分字符串/注释，全部按括号字符检查；含括号字符串可能误报。"},{"q":"中文括号也检查吗？","a":"检查《》「」『』等常见中文成对符号。"}],
};
