/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'browser-engines',
  name: '浏览器内核速查',
  desc: '浏览器渲染引擎与 JS 引擎速查：Blink/WebKit/Gecko/V8 等。',
  keywords: '浏览器内核,渲染引擎,js引擎,blink webkit,gecko v8,浏览器原理',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"引擎","swatch":false,"mono":false},{"key":1,"label":"使用方","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入引擎（Blink）或浏览器（Chrome）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查浏览器渲染引擎与 JS 引擎。</li><li>搜索支持按引擎或浏览器过滤。</li><li>理解浏览器兼容性差异的基础。</li></ol>`,
  faq: [{"q":"为什么 Chrome 和 Edge 一样？","a":"Edge 已迁移到 Chromium（Blink 内核），与 Chrome 渲染一致。"},{"q":"内核和引擎什么关系？","a":"渲染引擎负责页面布局绘制（Blink/WebKit），JS 引擎负责脚本执行（V8）。"}],
};
