/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'calorie-goal',
  name: '热量目标计算',
  desc: '每日热量目标：按体重、身高、年龄与活动量估算维持/减脂/增肌热量。',
  keywords: '热量目标,每日热量,减脂热量,增肌热量,tdee,热量计算',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">体重（kg）</label>
  <input type="number" id="ci-0" value="70" placeholder="">
</div><div class="field">
  <label for="ci-1">身高（cm）</label>
  <input type="number" id="ci-1" value="175" placeholder="">
</div><div class="field">
  <label for="ci-2">年龄</label>
  <input type="number" id="ci-2" value="30" placeholder="">
</div><div class="field"><label for="ci-3">性别</label><select id="ci-3"><option value="male" selected>男</option><option value="female">女</option></select></div><div class="field"><label for="ci-4">活动量</label><select id="ci-4"><option value="sedentary">久坐</option><option value="light">轻度</option><option value="moderate" selected>中度</option><option value="active">高度</option><option value="very">极高</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">TDEE = BMR × 活动系数；减脂 -400 千卡、增肌 +300 千卡为参考值。</div>
<script type="application/json" id="c-cfg">{"lib":"dev2","fn":"calorieGoalCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入身体数据与活动量，点击“计算”。</li>
  <li>输出 BMR、维持热量与减脂/增肌建议热量。</li>
  <li>饮食计划与运动目标制定参考。</li>
</ol>`,
  faq: [{"q":"和 BMR 计算器区别？","a":"本工具聚焦“吃多少”，直接给减脂/增肌热量目标；BMR 工具侧重代谢率本身。"},{"q":"数字会随运动变化吗？","a":"活动量按日常整体评估；单日大运动量消耗另计，建议记录后微调。"}],
};
