/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'calorie-burn',
  name: '运动消耗计算',
  desc: '运动卡路里消耗计算：按体重、时长与运动类型估算消耗热量。',
  keywords: '运动消耗,卡路里消耗,热量计算,减肥运动,跑步消耗,健身消耗',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">体重（kg）</label>
  <input type="number" id="ci-0" value="60" placeholder="">
</div><div class="field">
  <label for="ci-1">时长（分钟）</label>
  <input type="number" id="ci-1" value="30" placeholder="">
</div><div class="field"><label for="ci-2">运动类型</label><select id="ci-2"><option value="步行">步行</option><option value="慢跑" selected>慢跑</option><option value="快跑">快跑</option><option value="骑行">骑行</option><option value="游泳">游泳</option><option value="跳绳">跳绳</option><option value="瑜伽">瑜伽</option><option value="健身">健身</option><option value="羽毛球">羽毛球</option><option value="篮球">篮球</option><option value="足球">足球</option><option value="跳舞">跳舞</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按 MET 代谢当量估算：kcal = MET × 3.5 × 体重kg ÷ 200 × 分钟。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"calorieBurn","unit":""}</script>`,
  usage: `<ol>
  <li>输入体重、运动时长并选择运动类型，点击“计算”。</li>
  <li>得到估算消耗热量。</li>
  <li>减脂期记录消耗、制定运动计划参考。</li>
</ol>`,
  faq: [{"q":"估算准吗？","a":"MET 是群体平均值，个体差异 ±20%；实际消耗受强度、心率影响。"},{"q":"跑步 30 分钟消耗多少？","a":"60kg 慢跑 30 分钟约 220 千卡，快跑约 315 千卡；强度越高消耗越大。"}],
};
