/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'captcha-image',
  name: '验证码图片生成',
  desc: '验证码图片生成器：随机字母数字 + 干扰线，可下载 PNG 用于测试。',
  keywords: '验证码图片,验证码生成,图形验证码,验证码png,随机验证码',
  category: 'image',
  kind: 'image',
  script: 'image-gen',
  
  body: `<div class="field">
  <label for="ig-run" class="field-label">参数</label>
</div>

<div class="field">
  <label for="ig-p-length" class="field-label">字符数</label>
  <input type="number" id="ig-p-length" value="4" min="4">
</div>
<div class="row">
  <div class="field grow">
    <label for="ig-p-noise" class="field-label">干扰强度</label>
    <input type="range" id="ig-p-noise" min="10" max="100" value="30">
  </div>
  <span class="range-val" id="ig-p-noise-v">30%</span>
</div>
<div class="toolbar">
  <button id="ig-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button id="ig-download" class="btn btn-ghost" disabled>下载 PNG</button>
</div>
<div class="output">
  <canvas id="ig-canvas" aria-label="生成结果"></canvas>
</div>
<script type="application/json" id="ig-cfg">{"type":"captcha","params":[{"name":"length","type":"number"},{"name":"noise","type":"range"}]}</script>`,
  usage: `<ol><li>设置字符数与干扰强度，点击“生成”。</li><li>生成随机验证码图片（不含易混淆字符 0/O/1/l/I）。</li><li>用于系统测试、登录页演示，下载 PNG 使用。</li></ol>`,
  faq: [{"q":"验证码会被机器识别吗？","a":"本工具用于演示与测试，干扰较弱；生产环境请使用专业验证码服务。"},{"q":"字符集有哪些？","a":"去除了 0/O/1/l/I 等易混淆字符，保留大小写字母与数字。"}],
};
