/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'cheesy-lines',
  name: '土味情话生成',
  desc: '土味情话生成器：经典土味情话，表白调侃两相宜。',
  keywords: '土味情话,情话大全,表白情话,撩人语录,土味表白',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="1" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">内置 16 条经典土味情话，慎用于正式场合。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomCheesy","multi":false,"batch":1}</script>`,
  usage: `<ol><li>设置数量，点击“生成”。</li><li>输出土味情话。</li><li>情侣互动、朋友圈文案、逗趣开场常用。</li></ol>`,
  faq: [{"q":"适合表白吗？","a":"适合活跃气氛，正式表白建议搭配真诚的心里话。"},{"q":"内容健康吗？","a":"健康幽默，无低俗内容。"}],
};
