/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'chinese-extract',
  name: '中文提取',
  desc: '从文本中提取全部中文字符（含成语、词组），过滤掉字母数字与符号。',
  keywords: '提取中文,中文提取,汉字提取,筛选汉字,文字过滤',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴混合文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractChinese">提取中文</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取中文","fn":"extractChinese"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴含中英混排的文本，点击“提取中文”。</li>
  <li>保留全部汉字（CJK 统一表意文字），去掉字母、数字、标点与空格。</li>
  <li>适合统计纯汉字内容、生成中文语料。</li>
</ol>`,
  faq: [{"q":"标点会保留吗？","a":"不会，只保留汉字字符；需要保留中文标点请使用字符频率工具统计后自行处理。"},{"q":"生僻字能提取吗？","a":"可以，CJK 扩展区的汉字也在正则范围内（\\u4e00-\\u9fff 为主）。"}],
};
