/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'chinese-zodiac',
  name: '生肖查询',
  desc: '生肖查询：输入年份即得生肖、五行与本命年判断。',
  keywords: '生肖查询,生肖,属相,十二生肖,五行,本命年',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">年份</label>
  <input type="number" id="ci-0" value="2024" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按农历正月初一划分；本工具简化按公历年份对应（1984 年为鼠年基准）。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"zodiacAnimalCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入出生年份，点击“计算”。</li>
  <li>输出生肖、五行属性与本命年提示。</li>
  <li>注：生肖传统上按农历新年（正月初一）划分，公历年初出生请按农历确认。</li>
</ol>`,
  faq: [{"q":"2024 年是什么年？","a":"2024 是甲辰年（龙年），五行属木（木龙）。"},{"q":"1 月出生生肖按哪年算？","a":"按农历算：公历 2024 年 2 月 10 日（春节）前出生仍是兔年，之后才是龙年。"}],
};
