/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'clothes-size',
  name: '衣服尺码推荐',
  desc: '衣服尺码推荐：输入身高体重与性别，估算 S-XXL 建议尺码。',
  keywords: '衣服尺码,尺码推荐,身高体重尺码,衣服码数,买衣服尺码,S M L XL',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">身高（cm）</label>
  <input type="number" id="ci-0" value="175" placeholder="">
</div><div class="field">
  <label for="ci-1">体重（kg）</label>
  <input type="number" id="ci-1" value="70" placeholder="">
</div><div class="field"><label for="ci-2">性别</label><select id="ci-2"><option value="male" selected>男</option><option value="female">女</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按身高定基础码、BMI 修正；版型差异大，网购前看尺码表更准。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"clothesSizeCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入身高、体重与性别，点击“计算”。</li>
  <li>得到建议尺码（S-XXL）与对应 BMI。</li>
  <li>作为参考快速定位尺码区间，再对照商家尺码表确认。</li>
</ol>`,
  faq: [{"q":"网上买衣服选什么码？","a":"先看商品页尺码表（胸围/肩宽/衣长），结合本工具估算后选最接近的。"},{"q":"修身和宽松版怎么选？","a":"修身按估算码或小一码；宽松款可大一码；模特穿着效果仅供参考。"}],
};
