/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'code-escape',
  name: '代码转义',
  desc: '代码转义工具：JS/HTML/URL 转义与反转义，注入防护与调试。',
  keywords: '代码转义,js转义,html转义,url转义,转义还原,特殊字符转义',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要转义的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="escapeJs">JS 转义</button><button id="x-run-1" class="btn btn-ghost" data-fn="unescapeJs">JS 反转义</button><button id="x-run-2" class="btn btn-ghost" data-fn="escapeHtmlStr">HTML 转义</button><button id="x-run-3" class="btn btn-ghost" data-fn="escapeUrl">URL 转义</button><button id="x-run-4" class="btn btn-ghost" data-fn="unescapeUrl">URL 反转义</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev2","actions":[{"label":"JS 转义","fn":"escapeJs"},{"label":"JS 反转义","fn":"unescapeJs"},{"label":"HTML 转义","fn":"escapeHtmlStr"},{"label":"URL 转义","fn":"escapeUrl"},{"label":"URL 反转义","fn":"unescapeUrl"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>选择转义类型：JS 字符串、HTML 实体或 URL 编码。</li>
  <li>“转义”把特殊字符转为安全形式，“反转义”还原。</li>
  <li>XSS 防护、接口参数编码、日志排查常用。</li>
</ol>`,
  faq: [{"q":"HTML 转义防什么？","a":"把 \u003c > & 等转为实体，防止用户输入被当作标签执行（XSS 基础防护）。"},{"q":"URL 转义和编码一样吗？","a":"encodeURIComponent 编码所有特殊字符，适合参数值；整 URL 请用 encodeURI。"}],
};
