/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'code-stats',
  name: '代码行数统计',
  desc: '代码行数统计：总行数、代码行、注释行、空行分类统计。',
  keywords: '代码行数,统计代码,loc,代码统计,注释统计,项目行数',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴代码（支持 JS/Python/CSS 等常见注释）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="codeStats">统计</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">统计结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"convert3","actions":[{"label":"统计","fn":"codeStats"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴代码，点击“统计”。</li>
  <li>输出总行数、代码行、注释行与空行。</li>
  <li>汇报工作量、评估代码规模时快速统计。</li>
</ol>`,
  faq: [{"q":"注释识别规则？","a":"识别 //、#、/* */、*、\u003c!-- --> 开头的行；行内尾注释计入代码行。"},{"q":"能统计整个项目吗？","a":"需手动合并文件内容后粘贴；超大数据建议分批。"}],
};
