/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'coin-flip',
  name: '抛硬币',
  desc: '抛硬币：模拟硬币正反面，支持批量抛掷统计，决策困难症救星。',
  keywords: '抛硬币,硬币正反面,掷硬币,随机决策,正反面,硬币模拟',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">次数</label><input type="number" id="gp-0" value="1" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">每次独立随机，正反面概率各 50%。</div>
<script type="application/json" id="g-cfg">{"lib":"life","fn":"coinFlip","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>设置抛掷次数，点击“生成”。</li>
  <li>输出每次结果（正面/反面）。</li>
  <li>选择困难时用它做决定吧！</li>
</ol>`,
  faq: [{"q":"真的 50% 吗？","a":"使用加密级随机源，理论正反各 50%；物理硬币受抛掷手法影响会略有偏差。"},{"q":"能连续抛很多次吗？","a":"支持批量（最多 100 次），可统计分布。"}],
};
