/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'color-format',
  name: '颜色格式转换',
  desc: '颜色格式转换：HEX、RGB、HSL 三种格式互转，支持常用颜色名。',
  keywords: '颜色转换,hex转rgb,rgb转hex,颜色格式,hex转hsl,色值转换',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入颜色，如 #FF6347、rgb(255,99,71)、tomato"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="colorFormat">转换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">转换结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev3","actions":[{"label":"转换","fn":"colorFormat"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入任意格式颜色（HEX/RGB/常用颜色名），点击“转换”。</li>
  <li>同时输出 HEX、RGB、HSL 三种表示。</li>
  <li>前端样式、设计稿取色、颜色调试常用。</li>
</ol>`,
  faq: [{"q":"支持缩写 HEX 吗？","a":"支持，如 #f00 自动展开为 #FF0000。"},{"q":"颜色名支持哪些？","a":"内置常用颜色名（red/green/blue/black 等）；更多名称见“CSS 颜色名速查”。"}],
};
