/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'color-palette',
  name: '配色方案生成',
  desc: '配色方案生成：输入主色生成单色/互补/类似色配色方案。',
  keywords: '配色方案,配色生成,色板生成,互补色,类似色,颜色搭配',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入主色（HEX），如 #3498DB"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="paletteGen">生成方案</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">配色方案</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev5","actions":[{"label":"生成方案","fn":"paletteGen"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol><li>输入主色（HEX），点击“生成方案”。</li><li>输出单色、互补色、类似色、三色组等方案。</li><li>设计选色、UI 主题、图表配色常用。</li></ol>`,
  faq: [{"q":"配色方案科学吗？","a":"基于 HSL 色环关系（互补/类似/三角），是经典配色理论。"},{"q":"能导出吗？","a":"复制结果即可，每行一个色值。"}],
};
