/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'cookie-parse',
  name: 'Cookie 解析',
  desc: 'Cookie 字符串解析：将 Set-Cookie/Cookie 文本拆分为名称与值列表。',
  keywords: 'cookie解析,cookie查看,cookie工具,会话cookie,浏览器cookie',
  category: 'web',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 Cookie，如：session=abc123; theme=dark; lang=zh-CN"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="parseCookies">解析</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">解析结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"web","actions":[{"label":"解析","fn":"parseCookies"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 Cookie 字符串（分号分隔），点击“解析”。</li>
  <li>输出每个名称/值对，便于查看与调试。</li>
  <li>可粘贴浏览器 DevTools 中复制的 Cookie 或响应头 Set-Cookie。</li>
</ol>`,
  faq: [{"q":"Cookie 和 Set-Cookie 有区别吗？","a":"有。Cookie 是请求头发送的值对；Set-Cookie 是响应头（含 Domain/Path/Expires 等属性）。本工具解析值对部分。"},{"q":"值里有分号怎么办？","a":"分号是 Cookie 分隔符，值内含分号属少见情况；如遇截断请手工处理。"}],
};
