/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'country-codes',
  name: '国家区号速查',
  desc: '世界各国国际电话区号速查表：+86 中国、+1 美国等 64 个国家/地区。',
  keywords: '国际区号,国家区号,电话区号,国际电话,拨打国际,country code',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"区号","swatch":false,"mono":true},{"key":1,"label":"国家/地区","swatch":false,"mono":false}], search: "输入区号（+86）或国家名（日本）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查国际电话区号。</li><li>搜索支持按区号或国家名过滤。</li><li>国际通话、表单国家选择、地址信息处理常用。</li></ol>`,
  faq: [{"q":"国际拨打格式？","a":"中国打美国：00 或 + 开头，即 +1 电话号码（去掉本地 0 前缀）。"},{"q":"+1 为什么包含加拿大？","a":"北美号码计划（NANP）让美加共用 +1 区号，按前三位区号区分。"}],
};
