/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'country-info',
  name: '国家信息查询',
  desc: '国家信息查询：输入国家名查询首都、人口、货币、语言、区号等（内置数据，离线可用）。',
  keywords: '国家查询,国家信息,首都查询,人口查询,货币查询,国家百科',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="api-form">
  <div class="field grow">
    <label for="api-country">国家名（中文/英文/代码）</label>
    <input type="text" id="api-country" placeholder="如：中国 / China / CN">
  </div>
  <button id="api-run" class="btn">查询</button>
</div>
<div class="output">
  <div class="output-label">国家信息</div>
  <div id="api-out"></div>
</div>
<div class="note">内置 60+ 常用国家/地区数据（离线可用，无需联网）。支持中文名、英文名与 ISO 代码查询。</div>
<script type="application/json" id="api-cfg">{"type":"country"}</script>`,
  usage: `<ol><li>输入国家名（中英文或代码），点击"查询"。</li><li>查看首都、货币、语言、区号、人口、时区等信息。</li><li>内置数据离线可用，查询即时返回。</li></ol>`,
  faq: [{"q":"支持中文名吗？","a":"支持，如输入\"中国\"或\"China\"或\"CN\"均可查询。"},{"q":"数据需要联网吗？","a":"不需要，内置 60+ 常用国家/地区数据，完全离线。"},{"q":"没找到的国家怎么办？","a":"当前覆盖常见国家/地区；如需补充可在反馈中告知。"}],
};
