/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'crc16',
  name: 'CRC16 校验',
  desc: 'CRC16 校验值计算（CCITT-FALSE 参数）：Modbus、X.25 等工业协议常用的 16 位校验。',
  keywords: 'crc16,modbus crc,crc16校验,ccitt,循环冗余校验,工业协议校验',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本计算 CRC16（4 位十六进制）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="crc16">计算 CRC16</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">CRC16</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"计算 CRC16","fn":"crc16"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本（UTF-8），点击“计算 CRC16”得到 4 位十六进制校验值。</li>
  <li>本工具使用 CRC-16/CCITT-FALSE（poly 0x1021、初值 0xFFFF），常见于 Modbus、PPP 等协议。</li>
  <li>适合嵌入式开发、串口协议调试时快速核对报文校验。</li>
</ol>`,
  faq: [{"q":"CRC16 有多少种参数？","a":"很多。CCITT-FALSE、XMODEM、MODBUS、USB 等使用不同初值/反射/异或输出。请先确认协议要求的参数，本工具固定为 CCITT-FALSE。"},{"q":"Modbus 的 CRC16 一样吗？","a":"Modbus 使用 CRC-16/MODBUS（初值 0xFFFF、输入反射、输出异或 0x0000），与本工具的 CCITT-FALSE 不同，注意区分。"},{"q":"能校验文件吗？","a":"本工具接受文本输入；大文件请先用其他工具读取为文本/十六进制后校验，或使用本站 SHA 工具的“文件哈希”能力。"}],
};
