/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'crc32',
  name: 'CRC32 校验',
  desc: 'CRC32 校验值计算：文本或文件的 32 位循环冗余校验，用于数据完整性检测。',
  keywords: 'crc32,crc32校验,循环冗余校验,文件校验,数据完整性,crc计算',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本计算 CRC32（小写十六进制）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="crc32">计算 CRC32</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">CRC32</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"计算 CRC32","fn":"crc32"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入任意文本（UTF-8），点击“计算 CRC32”得到 8 位十六进制校验值。</li>
  <li>常见压缩包（zip/gzip）与网络协议用它检测传输/存储损坏。</li>
  <li>校验值会随内容任何一位变化而剧烈改变。</li>
</ol>`,
  faq: [{"q":"CRC32 能防篡改吗？","a":"不能。CRC32 只有 32 位且是线性校验，容易构造碰撞，只用于检测随机损坏（误码），不适用于安全校验；安全场景用 SHA-256。"},{"q":"为什么有时和别人算的不一样？","a":"CRC32 有多种变体（初始值、反射、异或输出不同）。本工具采用标准 zlib/PKZIP 参数（init 0xFFFFFFFF、reflected），即 Python zlib.crc32 的结果。"},{"q":"和 MD5 有什么区别？","a":"MD5 是密码学哈希（128 位），CRC32 是检错码（32 位）；CRC32 速度快得多但碰撞概率高，两者用途不同。"}],
};
