/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'css-units',
  name: 'CSS 单位速查',
  desc: 'CSS 单位速查表：长度、视口、角度、时间、分辨率 24 种单位。',
  keywords: 'css单位,px rem em,视口单位,单位换算,长度单位,前端单位',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"单位","swatch":false,"mono":true},{"key":1,"label":"说明","swatch":false,"mono":false}], search: "输入单位（rem）或用途（视口）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查 CSS 单位：长度、视口、角度、时间。</li><li>搜索支持按单位或用途过滤。</li><li>响应式布局、动画、打印样式常用。</li></ol>`,
  faq: [{"q":"px 和 rem 怎么选？","a":"固定尺寸用 px；需随根字号缩放的用 rem；组件内部相对缩放用 em。"},{"q":"vw/vh 和百分比什么区别？","a":"vw/vh 相对视口（不受父级影响），% 相对父元素；全屏布局用 vh 更方便。"}],
};
