/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'css-minify',
  name: 'CSS 压缩',
  desc: 'CSS 压缩：去注释、去空格、合并选择器空白，减小样式体积。',
  keywords: 'css压缩,css精简,去除注释,css优化,样式减肥',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 CSS 源码"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="minifyCss">压缩</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">压缩结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"压缩","fn":"minifyCss"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 CSS，点击“压缩”。</li>
  <li>删除注释与空格，如 a { color: red; } → a{color:red}。</li>
  <li>适合构建发布前的样式精简。</li>
</ol>`,
  faq: [{"q":"字符串里的空格会误删吗？","a":"content: \"a b\" 内的空格不会被删除（正则不处理引号内），基本安全。"},{"q":"支持嵌套语法吗？","a":"纯 CSS 压缩；Less/Sass 嵌套需先编译为 CSS。"}],
};
