/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'css-layout',
  name: 'CSS 布局技巧速查',
  desc: 'CSS 布局技巧速查：居中、两栏三栏、响应式等 20 个实用方案。',
  keywords: 'css布局,布局技巧,水平垂直居中,flex布局,grid布局,响应式',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"场景","swatch":false,"mono":false},{"key":1,"label":"方案","swatch":false,"mono":true}], search: "输入场景（居中）或方案（flex）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查常见布局问题的最佳实践。</li><li>搜索支持按场景或方案过滤。</li><li>写页面布局时快速参考，避免踩坑。</li></ol>`,
  faq: [{"q":"居中用 flex 还是 grid？","a":"单元素居中两者皆可；现代推荐 grid 的 place-items:center 更简洁。"},{"q":"为什么 vertical-align 不生效？","a":"vertical-align 只对行内元素生效；块级元素垂直居中用 flex/grid。"}],
};
