/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'css-colors',
  name: 'CSS 颜色名速查',
  desc: 'CSS 颜色关键字大全：全部 140+ 颜色名称、十六进制值与中文名，带色块预览。',
  keywords: 'css颜色,颜色名称,色值对照,颜色大全,十六进制颜色,颜色表',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"颜色名","swatch":false,"mono":true},{"key":1,"label":"色值","swatch":true,"mono":true},{"key":2,"label":"中文名","swatch":false,"mono":false}], search: "输入颜色名（tomato）、色值（#FF6347）或中文名…", dense: false },
  body: ``,
  usage: `<ol>
  <li>表格列出 CSS 全部颜色关键字及对应十六进制值，带色块预览。</li>
  <li>搜索支持按颜色名、色值或中文名过滤，方便挑色。</li>
  <li>在 CSS 中可直接使用颜色名（如 color: tomato）或色值（#FF6347）。</li>
</ol>`,
  faq: [{"q":"颜色名和十六进制值完全等价吗？","a":"是的，每个颜色关键字都有对应的标准 RGB 值，本表展示的十六进制即其精确值，两种写法渲染结果完全一致。"},{"q":"为什么不同系统显示颜色有差异？","a":"显示器色域、系统色彩管理都会影响观感。颜色名/色值是标准数据，但最终显示取决于设备和环境光。"},{"q":"还有别的颜色写法吗？","a":"还有 rgb()/rgba()、hsl()/hsla()、以及 CSS 颜色 4 级的 hwb()、lab()、oklch() 等，色域更广，可表示超出 sRGB 的颜色。"}],
};
