/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'currencies',
  name: '货币符号速查',
  desc: '世界各国货币速查：ISO 代码、货币符号、中文名称与所属国家或地区。',
  keywords: '货币符号,货币代码,iso货币,各国货币,人民币符号,美元符号,欧元符号',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"代码","swatch":false,"mono":true},{"key":1,"label":"符号","swatch":false,"mono":false},{"key":2,"label":"货币名","swatch":false,"mono":false},{"key":3,"label":"国家/地区","swatch":false,"mono":false}], search: "输入代码（CNY）、符号（¥）或国家名…", dense: false },
  body: ``,
  usage: `<ol>
  <li>表格列出主要国家/地区的 ISO 4217 货币代码、常用符号与名称。</li>
  <li>开发支付、汇率、国际化（i18n）功能时可快速核对货币代码。</li>
  <li>注意同一符号可能对应多种货币（如 $ 也用于加元、澳元），需结合代码区分。</li>
</ol>`,
  faq: [{"q":"为什么日元也用 ¥ 符号？","a":"人民币（CNY）和日元（JPY）都使用 ¥ 符号，但 Unicode 码点不同（人民币 U+00A5，日元 U+FFE5），且货币代码不同，处理时要以代码为准。"},{"q":"货币代码有什么规律？","a":"ISO 4217 代码前两位通常是国家/地区代码（如 CN、US、JP），最后一位是货币首字母（Y 元、D 元/dollar、E 欧元），如 CNY、USD、JPY。"},{"q":"有些符号是文字不是符号，正常吗？","a":"正常。部分货币没有专用符号（如越南盾常用 ₫，但也有用 “đ”），一些中东货币直接用阿拉伯文缩写，本表按当地习惯收录。"}],
};
