/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'currency-rate',
  name: '实时汇率换算',
  desc: '实时汇率换算：30+ 种货币实时汇率查询与换算（联网查询）。',
  keywords: '汇率换算,实时汇率,货币换算,外汇查询,美元人民币,汇率查询',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="api-form">
  <div class="field">
    <label for="api-amount">金额</label>
    <input type="number" id="api-amount" value="1" min="0" step="any">
  </div>
  <div class="field">
    <label for="api-from">从</label>
    <select id="api-from">
      <option value="CNY" selected>CNY 人民币</option><option value="USD">USD 美元</option>
      <option value="EUR">EUR 欧元</option><option value="JPY">JPY 日元</option>
      <option value="GBP">GBP 英镑</option><option value="HKD">HKD 港币</option>
      <option value="TWD">TWD 台币</option><option value="KRW">KRW 韩元</option>
      <option value="SGD">SGD 新加坡元</option><option value="AUD">AUD 澳元</option>
      <option value="CAD">CAD 加元</option><option value="CHF">CHF 瑞士法郎</option>
      <option value="RUB">RUB 卢布</option><option value="THB">THB 泰铢</option>
      <option value="VND">VND 越南盾</option><option value="MYR">MYR 林吉特</option>
      <option value="PHP">PHP 比索</option><option value="IDR">IDR 印尼盾</option>
      <option value="INR">INR 卢比</option><option value="MXN">MXN 比索</option>
      <option value="BRL">BRL 雷亚尔</option><option value="TRY">TRY 里拉</option>
    </select>
  </div>
  <div class="field">
    <label for="api-to">到</label>
    <select id="api-to">
      <option value="USD" selected>USD 美元</option><option value="CNY">CNY 人民币</option>
      <option value="EUR">EUR 欧元</option><option value="JPY">JPY 日元</option>
      <option value="GBP">GBP 英镑</option><option value="HKD">HKD 港币</option>
      <option value="TWD">TWD 台币</option><option value="KRW">KRW 韩元</option>
      <option value="SGD">SGD 新加坡元</option><option value="AUD">AUD 澳元</option>
      <option value="CAD">CAD 加元</option><option value="CHF">CHF 瑞士法郎</option>
      <option value="RUB">RUB 卢布</option><option value="THB">THB 泰铢</option>
      <option value="VND">VND 越南盾</option><option value="MYR">MYR 林吉特</option>
      <option value="PHP">PHP 比索</option><option value="IDR">IDR 印尼盾</option>
      <option value="INR">INR 卢比</option><option value="MXN">MXN 比索</option>
      <option value="BRL">BRL 雷亚尔</option><option value="TRY">TRY 里拉</option>
    </select>
  </div>
  <button id="api-run" class="btn">换算</button>
</div>
<div class="output">
  <div class="output-label">汇率结果</div>
  <div id="api-out"></div>
</div>
<div class="note">数据源：欧洲央行（frankfurter.dev，免费）。汇率每个工作日更新，为中间价，实际换汇有买卖差价。</div>
<script type="application/json" id="api-cfg">{"source":"欧洲央行 frankfurter.dev（免费）","provider":"欧洲央行 frankfurter.dev","url":"https://api.frankfurter.dev/v1/latest","type":"exchange"}</script>`,
  usage: `<ol><li>输入金额，选择源货币与目标货币，点击"换算"。</li><li>查看实时汇率与换算结果。</li><li>海淘比价、出行预算、跨境支付参考。</li></ol>`,
  faq: [{"q":"汇率多久更新？","a":"欧洲央行每个工作日更新一次（中间价），非实时波动价；高频交易请用券商实时报价。"},{"q":"为什么和银行牌价不同？","a":"银行牌价含买卖差价与服务费，通常比中间价高 1%-3%；本工具显示中间价。"},{"q":"支持哪些货币？","a":"支持约 30 种主要货币，覆盖常见贸易与旅游币种。"}],
};
