/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'daily-calorie',
  name: '每日热量计算',
  desc: '每日热量需求：BMR + 活动系数估算维持/减脂/增肌热量。',
  keywords: '每日热量,热量需求,基础代谢,bmr,减脂热量,增肌热量',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">体重（kg）</label>
  <input type="number" id="ci-0" value="70" placeholder="">
</div><div class="field">
  <label for="ci-1">身高（cm）</label>
  <input type="number" id="ci-1" value="175" placeholder="">
</div><div class="field">
  <label for="ci-2">年龄</label>
  <input type="number" id="ci-2" value="30" placeholder="">
</div><div class="field"><label for="ci-3">性别</label><select id="ci-3"><option value="male" selected>男</option><option value="female">女</option></select></div><div class="field"><label for="ci-4">活动量</label><select id="ci-4"><option value="1">久坐</option><option value="2">轻度</option><option value="3" selected>中度</option><option value="4">高度</option><option value="5">极高</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">Mifflin-St Jeor 公式；减脂建议 -300 千卡。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"dailyCalorie","unit":""}</script>`,
  usage: `<ol><li>输入身体数据与活动量，点击“计算”。</li><li>得到 BMR 与维持/减脂/增肌热量。</li><li>饮食计划、健身目标设定基础。</li></ol>`,
  faq: [{"q":"减脂热量越低越好？","a":"不是，低于 BMR 会掉代谢；建议 TDEE-300 并保证蛋白质。"},{"q":"和热量目标工具区别？","a":"功能相近，本工具更精简；两者可交叉验证。"}],
};
