/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'data-units',
  name: '数据单位换算速查',
  desc: '数据存储单位速查：KB/MB/GB 与 KiB/MiB/GiB 的十进制二进制对照。',
  keywords: '数据单位,存储单位,kb mb gb,进制换算,kib mib,硬盘容量',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"单位","swatch":false,"mono":true},{"key":1,"label":"换算","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入单位（GB）或说明（进制）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查数据存储单位与换算关系。</li><li>搜索支持按单位或说明过滤。</li><li>硬盘容量、文件大小、带宽换算时对照。</li></ol>`,
  faq: [{"q":"为什么 1TB 硬盘只有 931GB？","a":"厂商按十进制（1TB=1000GB），系统按二进制（1TiB=1024GiB）显示，差约 7%。"},{"q":"KB 和 KiB 用哪个？","a":"行业标准：KB=1000，KiB=1024；Windows 仍用 KiB 标成 KB，macOS 已用十进制。"}],
};
