/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'date-add',
  name: '日期加减计算',
  desc: '日期加/减 N 天：一键得到新日期与星期。',
  keywords: '日期加减,日期加天数,日期计算器,加n天,推算日期',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">起始日期</label><input type="date" id="ci-0" value="2024-08-20"></div><div class="field">
  <label for="ci-1">加减天数（负数为减）</label>
  <input type="number" id="ci-1" value="30" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">如 8 月 20 日 +30 天 = 9 月 19 日；减天数填负数。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"dateAddCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择起始日期，输入要加（或减）的天数，点击“计算”。</li>
  <li>输出新日期与对应星期。</li>
  <li>推算交货日期、还款日、签证有效期等常用。</li>
</ol>`,
  faq: [{"q":"跨月/跨年正确吗？","a":"正确，Date 对象自动处理月份与年份进位，如 1 月 31 日 +1 天 = 2 月 1 日。"},{"q":"能加月份吗？","a":"本工具按天加减；按月计算存在“月末歧义”，建议先换算成天数。"}],
};
