/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'date-format',
  name: '日期格式转换',
  desc: '日期格式转换器：一种输入输出 8 种常用格式（含 Unix 时间戳）。',
  keywords: '日期格式转换,日期格式化,时间戳转日期,日期格式,iso日期,日期转时间戳',
  category: 'date',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">日期（YYYY-MM-DD）</label><input type="date" id="ci-0" value="2024-08-20"></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">一次输出国际、中国、美国、欧洲格式与 Unix 时间戳。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"dateFormatCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择日期，点击“计算”。</li>
  <li>同时得到 ISO、YYYY/MM/DD、美式 MM/DD/YYYY、欧式 DD/MM/YYYY、中文格式与时间戳。</li>
  <li>接口对接、数据库日期处理、跨地区协作时格式互转常用。</li>
</ol>`,
  faq: [{"q":"时间戳是秒还是毫秒？","a":"输出秒级（Unix timestamp），这是接口中最常见的单位；毫秒级 = 秒级 × 1000。"},{"q":"能输入时间戳反向转换吗？","a":"请使用本站“时间戳转换”工具，支持秒/毫秒自动识别。"}],
};
