/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'date-diff',
  name: '日期差计算',
  desc: '两个日期相差多少天：天数、周+天、月数一键算出。',
  keywords: '日期差,相差天数,两个日期相隔,天数计算,日期间隔,倒计时天数',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">起始日期</label><input type="date" id="ci-0" value="2024-01-01"></div><div class="field"><label for="ci-1">结束日期</label><input type="date" id="ci-1" value="2024-01-11"></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">支持前后顺序任意，自动区分“后/前/当天”。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"daysBetweenCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择两个日期，点击“计算”。</li>
  <li>输出相差天数、周+天、约几个月，并标明方向（后/前）。</li>
  <li>计算项目工期、合同期限、纪念日倒计时都适用。</li>
</ol>`,
  faq: [{"q":"包含起始当天吗？","a":"按“两个时刻相减”计算：1 月 1 日到 1 月 11 日相差 10 天（不含起始日当天）。"},{"q":"结果能取负数吗？","a":"输出绝对值天数 + 方向说明，更直观；不需要方向时忽略该行即可。"}],
};
