/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'day-of-year',
  name: '一年中的第几天',
  desc: '日期转一年中第几天、第几周、星期与剩余天数。',
  keywords: '一年第几天,第几周,星期查询,剩余天数,日期统计,年中第几天',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">日期</label><input type="date" id="ci-0" value="2024-08-20"></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出一年中第几天（如 8/20 是第 233 天）、粗略周数与星期。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"dayOfYearCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择日期，点击“计算”。</li>
  <li>得到一年中的第几天（共 365/366）、第几周、星期与剩余天数。</li>
  <li>项目管理、进度统计、年终总结场景常用。</li>
</ol>`,
  faq: [{"q":"周数标准一样吗？","a":"本工具按自然周（第 N 周 = 天数 ÷7 向上取整）粗略计算；ISO 周有独立标准，周一开始。"},{"q":"闰年天数怎么变？","a":"闰年全年 366 天，2 月 29 日之后“第几天”比平年多 1。"}],
};
