/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'dice-roller',
  name: '掷骰子',
  desc: '掷骰子：自定义骰子数量与面数，输出每次点数与总和，桌游必备。',
  keywords: '掷骰子,骰子,骰子模拟,dice,桌游骰子,掷骰',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">骰子数量</label><input type="number" id="gp-0" value="2" min="1"></div><div class="field"><label for="gp-1">面数</label><input type="number" id="gp-1" value="6" min="2"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">支持 4/6/8/10/12/20 面骰等任意面数。</div>
<script type="application/json" id="g-cfg">{"lib":"life","fn":"rollDice","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>设置骰子数量（1-20）与面数（2-100），点击“生成”。</li>
  <li>输出每次点数与总和。</li>
  <li>跑团、桌游、酒桌游戏都能用。</li>
</ol>`,
  faq: [{"q":"D20 是什么？","a":"20 面骰（D20），TRPG 跑团常用；本工具面数可设为 20。"},{"q":"点数分布均匀吗？","a":"加密级随机，每个面等概率出现。"}],
};
