/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'discount-calc',
  name: '折扣计算器',
  desc: '折扣计算：输入原价与折扣，一键得出折后价、节省金额与比例。',
  keywords: '折扣计算器,打折计算,优惠计算,折后价,省钱计算,折扣工具',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">原价（元）</label>
  <input type="number" id="ci-0" value="199" placeholder="">
</div><div class="field">
  <label for="ci-1">折扣（%，如 8 折=80）</label>
  <input type="number" id="ci-1" value="80" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">折扣填 0-100：80 表示八折（付 80%）、50 表示五折。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"discountCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入商品原价与折扣（8 折填 80），点击“计算”。</li>
  <li>输出折后价、节省金额与节省比例。</li>
  <li>促销比价、凑单决策时快速算清实际支出。</li>
</ol>`,
  faq: [{"q":"“8 折”应该填 80 还是 0.8？","a":"填 80（百分比）。工具按 原价 × 折扣% 计算，8 折 = 原价 × 80%。"},{"q":"折扣能超过 100 吗？","a":"不能，范围 0-100；超过 100 相当于加价，工具会提示。"}],
};
