/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'dns-records',
  name: 'DNS 记录类型速查',
  desc: 'DNS 记录类型速查表：A/AAAA/CNAME/MX/TXT 等 16 种记录及用途。',
  keywords: 'dns记录,dns类型,域名记录,解析记录,ns记录,mx记录',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"记录","swatch":false,"mono":true},{"key":1,"label":"说明","swatch":false,"mono":false},{"key":2,"label":"用途","swatch":false,"mono":false}], search: "输入记录（CNAME）或用途（邮件）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查DNS 记录类型。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"D","a":"N"},{"q":"T","a":"T"}],
};
