/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'drunk-calc',
  name: '酒驾程度估算',
  desc: '酒驾程度估算：按体重、饮酒量与时间估算 BAC，科普警示工具。',
  keywords: '酒驾,酒精浓度,血液酒精,bac,酒驾标准,醉驾标准,酒后驾车',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">体重（kg）</label>
  <input type="number" id="ci-0" value="70" placeholder="">
</div><div class="field">
  <label for="ci-1">啤酒（瓶，约 500ml）</label>
  <input type="number" id="ci-1" value="3" placeholder="">
</div><div class="field">
  <label for="ci-2">饮酒后小时数</label>
  <input type="number" id="ci-2" value="1" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">简化模型科普参考；中国标准：≥0.02% 酒驾，≥0.08% 醉驾。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"drunkCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入体重、啤酒数量与饮酒后时间，点击“计算”。</li>
  <li>查看估算 BAC 与酒驾/醉驾判定。</li>
  <li>科普工具，实际以呼气/血液检测为准。</li>
</ol>`,
  faq: [{"q":"喝酒多久能开车？","a":"因人而异，一般每小时代谢约 0.015% BAC；稳妥起见饮酒后至少 12 小时再开车。"},{"q":"白酒/红酒怎么算？","a":"本工具按啤酒估算；白酒酒精含量高，实际 BAC 更高，请务必不要酒后驾车。"}],
};
