/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'due-date',
  name: '预产期计算器',
  desc: '预产期计算：按末次月经日期推算预产期与当前孕周，准妈妈工具。',
  keywords: '预产期,预产期计算,怀孕周期,孕周计算,末次月经,预产期推算',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">末次月经日期</label><input type="date" id="ci-0" value=""></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">Naegele 法则：末次月经 + 280 天（40 周）；实际以医生 B 超为准。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"dueDateCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择末次月经第一天，点击“计算”。</li>
  <li>得到预产期、估算孕周与剩余天数。</li>
  <li>仅作参考，产检请遵医嘱。</li>
</ol>`,
  faq: [{"q":"预产期准吗？","a":"只有约 5% 婴儿在预产期当天出生；前后两周内出生都属正常。"},{"q":"周期不规律怎么办？","a":"早期 B 超（孕 8-12 周）推算更准确，请以医生判断为准。"}],
};
