/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'electricity-cost',
  name: '电器电费计算',
  desc: '电器耗电与电费计算：功率 × 时长 → 度数与电费（按天/月）。',
  keywords: '电费计算,电器耗电,千瓦时,功率计算,电费查询,一度电',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">功率（瓦 W）</label>
  <input type="number" id="ci-0" value="1000" placeholder="">
</div><div class="field">
  <label for="ci-1">每天使用（小时）</label>
  <input type="number" id="ci-1" value="3" placeholder="" step="any">
</div><div class="field">
  <label for="ci-2">电费单价（元/度）</label>
  <input type="number" id="ci-2" value="0.6" placeholder="" step="any">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">1 度电 = 1 千瓦时；如 1000W 电器用 3 小时 = 3 度电。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"electricityCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入电器功率（W）、每天使用时长与电费单价，点击“计算”。</li>
  <li>输出每天耗电量（度）、每天电费与每月（30 天）电费。</li>
  <li>比较不同电器能耗、预估家庭电费常用。</li>
</ol>`,
  faq: [{"q":"怎么查电费单价？","a":"各地居民电价约 0.5-0.9 元/度（含阶梯价）；查看电费单或当地发改委公告。"},{"q":"空调/冰箱是恒功率吗？","a":"不是，压缩机启停导致实际功耗波动；本工具按标称功率估算，实际以电表为准。"}],
};
