/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'elements',
  name: '化学元素周期表',
  desc: '化学元素速查：全部 118 种元素的符号、中文名、英文名、原子序数与原子量。',
  keywords: '化学元素,元素周期表,元素符号,原子序数,原子量,化学元素表',
  category: 'ref',
  kind: 'table',
  table: { columns: [{"key":4,"label":"序数","swatch":false,"mono":true},{"key":0,"label":"符号","swatch":false,"mono":true},{"key":1,"label":"中文名","swatch":false,"mono":false},{"key":2,"label":"英文名","swatch":false,"mono":false},{"key":3,"label":"原子量","swatch":false,"mono":true}], search: "输入元素名（铁）、符号（Fe）或序数（26）…", dense: false },
  body: ``,
  usage: `<ol>
  <li>表格列出全部 118 种化学元素：原子序数、符号、中英文名与标准原子量。</li>
  <li>搜索支持按中文名、英文名、符号或序数过滤。</li>
  <li>适合化学学习、材料命名、化合物书写时快速查元素数据。</li>
</ol>`,
  faq: [{"q":"原子量为什么不是整数？","a":"标准原子量是各天然同位素按丰度加权的平均值（如氯 35.45），而单一同位素的质量数是整数（如 Cl-35、Cl-37）。"},{"q":"118 号之后的元素存在吗？","a":"目前确认到 118 号（鿫 Og），更重的元素理论上存在但极不稳定，尚未被合成确认；119 号以后仍在理论探索中。"},{"q":"为什么有些元素有两个中文名？","a":"部分超重元素的简体中文名是近年由全国科技名词委定名的新造字（如𬬻、𬭊），早期资料中可能使用音译名，均指同一元素。"}],
};
