/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'email-extract',
  name: '邮箱提取',
  desc: '从文本中提取全部邮箱地址，识别标准邮箱格式并逐行列出。',
  keywords: '提取邮箱,邮箱提取,email提取,批量提取邮箱,邮箱筛选',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴含邮箱的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractEmails">提取邮箱</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取邮箱","fn":"extractEmails"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本，点击“提取邮箱”，识别标准格式邮箱（本地部分@域名.顶级域）。</li>
  <li>结果逐行列出，可复制后用“文本行处理”去重。</li>
</ol>`,
  faq: [{"q":"会误识别吗？","a":"偶尔。如 123@456 这种缺少顶级域的不会匹配；带 .con 等拼写错误的也匹配不上，属正常。"},{"q":"支持中文域名邮箱吗？","a":"支持域名中的 IDN 有一定限制，常见英文域名邮箱均可正确提取。"}],
};
