/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'emoji-remove',
  name: 'Emoji 去除',
  desc: '删除文本中的 emoji 与特殊符号，保留文字内容，数据清洗常用。',
  keywords: '去emoji,emoji去除,表情符号删除,emoji过滤,符号清理',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴含 emoji 的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="removeEmoji">去除 Emoji</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"去除 Emoji","fn":"removeEmoji"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本点击“去除 Emoji”，删除表情符号（含肤色修饰符与 ZWJ 组合）。</li>
  <li>适合把社交媒体文本清理后做分析、入库。</li>
</ol>`,
  faq: [{"q":"会误删普通符号吗？","a":"只删 emoji 区段（U+1F300 起、杂项符号、修饰符等），普通标点不受影响。"},{"q":"多人组合 emoji 能删干净吗？","a":"能，ZWJ 序列（如家庭 emoji）通过连接符匹配整体删除。"}],
};
