/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'emoji-list',
  name: 'Emoji 大全',
  desc: '常用 emoji 列表：表情、手势、爱心、动植物、食物、符号，点击即可复制。',
  keywords: 'emoji大全,emoji列表,表情符号,emoji复制,颜文字,符号大全',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"Emoji","swatch":false,"mono":false},{"key":1,"label":"含义","swatch":false,"mono":false}], search: "输入 emoji 或含义（爱心）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>浏览常用 emoji 与含义。</li><li>点击复制按钮直接复制 emoji 字符。</li><li>社交文案、文档标注、聊天表情常用。</li></ol>`,
  faq: [{"q":"为什么同一 emoji 显示不同？","a":"emoji 外观由操作系统/平台决定（Apple/Google/微软风格不同），字符本身一致。"},{"q":"能组合 emoji 吗？","a":"部分可用 ZWJ 连接符组合（如 ❤️‍🔥），兼容性因平台而异。"}],
};
