/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'encoding-detect',
  name: '文本编码检测',
  desc: '文本编码分析：检测 UTF-8 合法性、是否含中文、字节数统计。',
  keywords: '编码检测,字符编码,utf8检测,乱码检测,编码分析,文本编码',
  category: 'web',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴要检测的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="detectEncoding">检测</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">检测结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"web","actions":[{"label":"检测","fn":"detectEncoding"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本，点击“检测”。</li>
  <li>输出 UTF-8 合法性（字节序列检查）、是否含中文与字节数。</li>
  <li>排查乱码问题时判断内容是否为合法 UTF-8。</li>
</ol>`,
  faq: [{"q":"能检测 GBK 吗？","a":"浏览器环境输入已是 Unicode；本工具检查内容是否构成合法 UTF-8 序列，无法反推原始字节编码。"},{"q":"乱码文本能修复吗？","a":"无法直接修复，需知道原始编码；可先用“十六进制互转”查看字节再判断。"}],
};
