/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'english-name',
  name: '英文名生成器',
  desc: '随机英文名生成器：经典英文名 + 姓氏组合，支持性别选择。',
  keywords: '英文名生成,英文名字,取英文名,英文姓名,英文昵称,name generator',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="5" min="1"></div><div class="field"><label for="gp-1">性别</label><select id="gp-1"><option value="any" selected>随机</option><option value="male">男</option><option value="female">女</option></select></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">英美常见名库：James/Mary 等 + 常见姓氏。</div>
<script type="application/json" id="g-cfg">{"lib":"gen2","fn":"randomEnglishName","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>选择性别与数量，点击“生成”。</li>
  <li>输出“名 + 姓”格式的英文姓名。</li>
  <li>注册海外账号、取英文名、测试数据常用。</li>
</ol>`,
  faq: [{"q":"名字地道吗？","a":"使用英美常用名库（Top 20 名 + Top 30 姓），组合自然。"},{"q":"能生成中文名拼音吗？","a":"英文名生成器产出英文姓名；中文拼音可用“姓名生成器”。"}],
};
