/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'extract-between',
  name: '提取标记间内容',
  desc: '提取两个标记之间的全部内容：日志解析、报文提取常用。',
  keywords: '提取内容,标记提取,区间提取,日志解析,报文提取,截取片段',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本（支持多次匹配，逐行输出）"></textarea>
</div>
<div class="field"><label for="xp-0">起始标记</label><input type="number" id="xp-0" value="<title>"></div><div class="field"><label for="xp-1">结束标记</label><input type="number" id="xp-1" value="</title>"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractBetween">提取</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"提取","fn":"extractBetween"}],"multi":false,"auto":false,"params":[{"name":"start","type":"text"},{"name":"end","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写起始与结束标记，粘贴文本。</li>
  <li>提取所有“起始标记…结束标记”之间的内容，每段一行。</li>
  <li>从 HTML/日志/报文中批量抽取字段常用。</li>
</ol>`,
  faq: [{"q":"能匹配多次吗？","a":"能，循环提取所有匹配段并逐行输出。"},{"q":"标记含正则字符会怎样？","a":"按纯文本查找（非正则），\u003c> 等符号直接使用即可。"}],
};
