/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'factorial',
  name: '阶乘计算',
  desc: '阶乘计算器：n! 精确计算（BigInt 支持超大数），附科学计数法。',
  keywords: '阶乘,阶乘计算,factorial,n!,排列,大数阶乘',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">n（0-170）</label>
  <input type="number" id="ci-0" value="10" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">BigInt 精确计算，10! = 3628800；超过 170 位自动截断显示并附科学计数法。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"factorialCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入整数 n（0-170），点击“计算”。</li>
  <li>输出 n! 的精确值（超长数字截断显示）与科学计数法。</li>
  <li>排列组合、概率统计、级数计算常用。</li>
</ol>`,
  faq: [{"q":"0! 等于多少？","a":"0! = 1（数学定义，保证组合公式 C(n,0)=1 成立）。"},{"q":"为什么限制 170？","a":"170! 约 7.26×10³⁰⁶，已超出常规数值范围；BigInt 虽能算更大，但显示与后续运算不便。"}],
};
