/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'first-lines',
  name: '取前 N 行',
  desc: '取文本前 N 行 / 跳过前 N 行：日志、配置文件的快速预览与裁剪。',
  keywords: '取前几行,跳过行数,行裁剪,head,文本预览,截取行',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入多行文本"></textarea>
</div>
<div class="field"><label for="xp-0">行数 N</label><input type="number" id="xp-0" value="10" min="1"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractFirstLines">取前 N 行</button><button id="x-run-1" class="btn btn-ghost" data-fn="removeFirstLines">跳过前 N 行</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"取前 N 行","fn":"extractFirstLines"},{"label":"跳过前 N 行","fn":"removeFirstLines"}],"multi":false,"auto":false,"params":[{"name":"count","type":"number"}]}</script>`,
  usage: `<ol>
  <li>输入文本与行数 N，点击“取前 N 行”或“跳过前 N 行”。</li>
  <li>前者保留开头 N 行；后者删除开头 N 行保留剩余。</li>
  <li>预览大日志、去掉配置文件头部注释常用。</li>
</ol>`,
  faq: [{"q":"N 大于总行数会怎样？","a":"取前 N 行返回全部；跳过前 N 行返回空。"},{"q":"空行算行吗？","a":"算，按真实换行符分行。"}],
};
