/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'fraction-decimal',
  name: '分数小数互转',
  desc: '分数与小数互转：分数化小数/百分数/最简分数，小数化分数。',
  keywords: '分数转小数,小数转分数,分数计算器,最简分数,百分数转换,分数化简',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">分子</label>
  <input type="number" id="ci-0" value="1" placeholder="">
</div><div class="field">
  <label for="ci-1">分母</label>
  <input type="number" id="ci-1" value="4" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出小数、百分数、最简分数与带分数；用“小数→分数”模式反向转换。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"fractionToDecimal","unit":""}</script>`,
  usage: `<ol>
  <li>输入分子与分母，点击“计算”，得到小数、百分数、最简分数。</li>
  <li>负数与假分数（如 7/4）也能正确处理，输出带分数。</li>
  <li>教学、配方换算、工程计算常用。</li>
</ol>`,
  faq: [{"q":"1/4 和 0.25 完全等价吗？","a":"数学上等价；本工具同时给出小数、百分数（25%）与最简分数（1/4）。"},{"q":"分母能为 0 吗？","a":"不能，除零无意义，工具会提示“分母不能为 0”。"}],
};
