/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'frameworks',
  name: '前端框架速查',
  desc: '前端框架与库速查：React/Vue/Angular 等 20 个框架的定位与生态。',
  keywords: '前端框架,框架对比,react vue angular,next nuxt,技术选型',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"框架","swatch":false,"mono":false},{"key":1,"label":"维护方","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入框架（React）或定位（全栈）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查主流前端框架与生态。</li><li>搜索支持按框架名或定位过滤。</li><li>项目技术选型、学习路线参考。</li></ol>`,
  faq: [{"q":"React 和 Vue 怎么选？","a":"两者都优秀：React 生态大、职位多；Vue 上手平缓、中文文档好。"},{"q":"Next.js 是什么？","a":"React 的全栈框架（SSR/SSG），当前前端主流选择之一。"}],
};
