/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'fuel-cost',
  name: '油费计算',
  desc: '自驾油费计算：里程、油耗、油价 → 耗油量与总油费。',
  keywords: '油费计算,自驾费用,油耗成本,加油费用,出行成本,每公里油费',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">里程（公里）</label>
  <input type="number" id="ci-0" value="300" placeholder="">
</div><div class="field">
  <label for="ci-1">百公里油耗（L/100km）</label>
  <input type="number" id="ci-1" value="8" placeholder="" step="any">
</div><div class="field">
  <label for="ci-2">油价（元/升）</label>
  <input type="number" id="ci-2" value="7.5" placeholder="" step="any">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">耗油量 = 里程 ÷ 100 × 百公里油耗；附每公里成本。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"fuelCostCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入里程、车辆百公里油耗与当前油价，点击“计算”。</li>
  <li>输出耗油量、总油费与每公里成本。</li>
  <li>自驾出行预算、网约车成本核算、油耗对比常用。</li>
</ol>`,
  faq: [{"q":"怎么知道自己的百公里油耗？","a":"加满油后记录里程，下次加满看加油量：油量 ÷ 行驶里程 × 100。"},{"q":"电车怎么算？","a":"电车按“度/百公里”同理：耗电量 ÷ 100 × 电价，可套用本工具的数值逻辑。"}],
};
