/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'fuel-convert',
  name: '油耗换算',
  desc: '百公里油耗与 mpg 油耗单位互转：L/100km、mpg、km/L 一键换算。',
  keywords: '油耗换算,百公里油耗,mpg换算,升每百公里,油耗计算,英里加仑',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数值</label>
  <input type="number" id="ci-0" value="8" placeholder="">
</div><div class="field"><label for="ci-1">输入单位</label><select id="ci-1"><option value="l100" selected>升/100公里</option><option value="mpg">英里/加仑(美)</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">L/100km 与 mpg 是倒数关系：8 L/100km ≈ 29.4 mpg(美)。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"fuelConvert","unit":""}</script>`,
  usage: `<ol>
  <li>输入油耗数值并选择单位（L/100km 或 mpg），点击“计算”。</li>
  <li>输出三种油耗单位对照。</li>
  <li>看海外评测（mpg）或国内标称（L/100km）时快速换算。</li>
</ol>`,
  faq: [{"q":"为什么 mpg 越大越省油？","a":"mpg = 每加仑英里数，数值越大说明一加仑油跑得越远，越省油；而 L/100km 数值越小越省油，两者方向相反。"},{"q":"美制与英制加仑一样吗？","a":"不一样（美制 3.785L、英制 4.546L）；本工具默认美制 mpg，与主流汽车媒体一致。"}],
};
