/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ganzhi',
  name: '干支纪年',
  desc: '干支纪年查询：年份转天干地支，如 2024 年 = 甲辰年。',
  keywords: '干支纪年,天干地支,甲子,农历年,纪年法,六十甲子',
  category: 'date',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">年份</label>
  <input type="number" id="ci-0" value="2024" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">1984 年 = 甲子年（六十甲子起始基准）。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"ganzhiCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入公历年份，点击“计算”。</li>
  <li>输出天干地支纪年，如 2024 甲辰、2025 乙巳。</li>
  <li>传统历法、命理、年号纪年场景常用。</li>
</ol>`,
  faq: [{"q":"六十甲子怎么轮回？","a":"天干 10 个与地支 12 个最小公倍数为 60，每 60 年一轮回，如 1984 甲子、2044 又是甲子。"},{"q":"和生肖什么关系？","a":"地支对应生肖：子鼠、丑牛、寅虎…如辰年即龙年，两者来自同一套纪年系统。"}],
};
