/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ganzhi-table',
  name: '六十甲子表',
  desc: '六十甲子速查：1984-2043 年天干地支与生肖对照表。',
  keywords: '六十甲子,天干地支表,干支表,生肖对照,甲子年,干支纪年',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"干支","swatch":false,"mono":true},{"key":1,"label":"生肖","swatch":false,"mono":false},{"key":2,"label":"年份","swatch":false,"mono":true}], search: "输入干支（甲子）或年份（2024）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查 1984-2043 年干支与生肖。</li><li>搜索支持按干支或年份过滤。</li><li>传统纪年换算、命理参考、文化学习常用。</li></ol>`,
  faq: [{"q":"为什么 60 年一轮回？","a":"天干 10 个 × 地支 12 个的最小公倍数为 60，形成六十甲子循环。"},{"q":"1984 年为什么是甲子？","a":"以 1984 甲子年为基准表（历史上甲子年多次轮回），向前每 60 年一个甲子。"}],
};
