/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'gcd-lcm',
  name: '最大公约数/最小公倍数',
  desc: 'GCD/LCM 计算：两数的最大公约数与最小公倍数一键算出。',
  keywords: '最大公约数,最小公倍数,gcd,lcm,公约数,公倍数,约分',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数字 A</label>
  <input type="number" id="ci-0" value="12" placeholder="">
</div><div class="field">
  <label for="ci-1">数字 B</label>
  <input type="number" id="ci-1" value="18" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">GCD(12,18)=6，LCM(12,18)=36；两数相乘 = GCD × LCM。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"gcdLcmCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入两个正整数，点击“计算”。</li>
  <li>输出最大公约数（GCD）与最小公倍数（LCM）。</li>
  <li>分数约分、齿轮比、排班周期、工程协调常用。</li>
</ol>`,
  faq: [{"q":"互质数的 GCD 是多少？","a":"互质（如 8 和 15）时 GCD=1，LCM=两数乘积 120。"},{"q":"支持 0 吗？","a":"不支持，请输入正整数；0 与任何数的 GCD 定义特殊，容易误解。"}],
};
