/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'genshin-image',
  name: '随机原神图',
  desc: '随机原神图片：游戏角色与场景壁纸，一键换图（联网获取）。',
  keywords: '原神图,原神壁纸,原神角色,genshin,随机原神,游戏壁纸',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="toolbar">
  <button id="api-run" class="btn">换一张</button>
  <span class="spacer"></span>
  <span class="text-3" style="font-size:13px">数据源：randompic.pldduck.com</span>
</div>
<div class="output">
  <div class="output-label">随机原神图</div>
  <div id="api-out"></div>
</div>
<div class="note">打开自动加载；图片为《原神》相关同人/壁纸图。版权归米哈游与原作者所有，请勿商用。</div>
<script type="application/json" id="api-cfg">{"type":"randomImage","url":"https://randompic.pldduck.com/ys","alt":"随机原神图"}</script>`,
  usage: `<ol><li>打开页面自动获取随机原神图。</li><li>点击"换一张"刷新。</li><li>可保存为壁纸或收藏。</li></ol>`,
  faq: [{"q":"图片版权归谁？","a":"《原神》角色版权归米哈游，图片版权归原作者；仅限个人使用。"},{"q":"能指定角色吗？","a":"当前随机获取；如需指定角色请自行搜索相关图库。"}],
};
