/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'gold-karat',
  name: 'K 金纯度换算',
  desc: 'K 金纯度换算：24K/18K/14K 等含金量百分比换算，买金饰参考。',
  keywords: 'k金纯度,含金量,24k,18k金,黄金纯度,足金,金饰',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">K 数（1-24）</label>
  <input type="number" id="ci-0" value="18" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">纯度 = K数 ÷ 24 × 100%；24K 足金、18K 含金 75%。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"goldKaratCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入 K 数（如 18、24、14），点击“计算”。</li>
  <li>得到含金量百分比、千分数与常见叫法。</li>
  <li>买金饰、回收估价时对照纯度。</li>
</ol>`,
  faq: [{"q":"18K 和 24K 哪个好？","a":"24K 足金纯度高但软，易变形；18K（75%）硬度好，适合镶嵌与日常佩戴。"},{"q":"千足金/万足金是什么？","a":"千足金=99.9%（已规范为“足金”），万足金≈99.99%；国标 2016 年后统一称足金。"}],
};
