/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'hash-detect',
  name: '哈希类型识别',
  desc: '哈希指纹识别：根据长度与格式推断 MD5、SHA 系列、bcrypt、crypt 等哈希类型。',
  keywords: '哈希识别,hash识别,哈希类型,md5判断,sha256判断,哈希检测',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴要识别的哈希值"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="identifyHash">识别</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">识别结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"识别","fn":"identifyHash"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴哈希值（可含空格），点击“识别”。</li>
  <li>根据长度、字符集与前缀特征列出所有可能类型及说明。</li>
  <li>注意：MD5 与 NTLM、SHA-256 与 SHA3-256 长度相同，仅凭指纹无法 100% 区分，需结合上下文。</li>
</ol>`,
  faq: [{"q":"识别一定准确吗？","a":"不一定。很多哈希长度相同（如 MD5 与 NTLM 都是 32 位十六进制），指纹只能缩小范围，最终需结合来源判断。"},{"q":"bcrypt 为什么是 $2a$ 开头？","a":"bcrypt 哈希自带算法标识（$2a/$2b/$2y）与迭代次数（$10$ 表示 2^10 轮），格式固定，容易识别。"},{"q":"能识别哪些类型？","a":"MD5、SHA-1/256/384/512、SHA3-256、CRC32、Adler-32、NTLM、MySQL、bcrypt、crypt-SHA512/256 及长 Base64。"}],
};
