/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'hmac',
  name: 'HMAC 消息认证码',
  desc: 'HMAC-MD5/SHA-1/SHA-256 计算：带密钥的哈希，用于 API 签名、消息完整性验证。',
  keywords: 'hmac,hmac-sha256,hmac-md5,消息认证码,api签名,密钥哈希',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入要签名的消息"></textarea>
</div>
<div class="field"><label for="xp-0">算法</label><select id="xp-0"><option value="SHA-256" selected>SHA-256</option><option value="SHA-1">SHA-1</option><option value="MD5">MD5</option><option value="SHA-384">SHA-384</option><option value="SHA-512">SHA-512</option></select></div><div class="field"><label for="xp-1">密钥</label><input type="text" id="xp-1" value="secret"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="hmac">计算 HMAC</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">HMAC 结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"计算 HMAC","fn":"hmac"}],"multi":false,"auto":false,"params":[{"name":"algorithm","type":"select"},{"name":"key","type":"text"}]}</script>`,
  usage: `<ol>
  <li>选择算法、填写密钥，输入消息文本。</li>
  <li>点击“计算 HMAC”得到十六进制摘要；对方用相同密钥与算法可验证。</li>
  <li>HMAC 比单纯“哈希(密钥+消息)”更安全，能抵抗长度扩展攻击。</li>
</ol>`,
  faq: [{"q":"HMAC 和哈希有什么区别？","a":"HMAC 在哈希基础上引入了密钥（两次异或填充），只有知道密钥才能计算/验证，用于认证而非内容公开校验。"},{"q":"API 签名怎么用？","a":"常见做法：把请求参数按规则拼接成字符串，用 HMAC-SHA256(密钥, 字符串) 生成签名附在请求头，服务端用同一密钥重算比对。"},{"q":"密钥应该多长？","a":"建议与哈希输出等长或更长（如 HMAC-SHA256 用 32 字节以上随机密钥）；过短密钥可被暴力猜测。"}],
};
