/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'holidays',
  name: '节日倒计时',
  desc: '节日提醒：列出未来 1 年内最近的中外节日及倒计时天数。',
  keywords: '节日倒计时,节日提醒,节日查询,纪念日,还有几天过节',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">

</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">覆盖元旦、情人节、劳动节、国庆节、圣诞等常见节日，实时计算。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"upcomingHolidayCalc","unit":""}</script>`,
  usage: `<ol>
  <li>点击“计算”查看从今天起最近的 5 个节日与倒计时。</li>
  <li>适合运营排期、活动策划、礼物提醒。</li>
  <li>农历节日（春节、中秋）不在本列表，见“农历查询”。</li>
</ol>`,
  faq: [{"q":"包含哪些节日？","a":"公历常见节日：元旦、情人节、妇女节、植树节、愚人节、劳动节、青年节、儿童节、建党节、建军节、教师节、国庆节、平安夜、圣诞节。"},{"q":"今天是节日会显示什么？","a":"显示“今天”，便于当天提醒。"}],
};
