/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'html-minify',
  name: 'HTML 压缩',
  desc: 'HTML 压缩/去注释：去除注释与多余空白，减少页面体积。',
  keywords: 'html压缩,html精简,去除注释,html优化,页面减肥',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 HTML 源码"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="minifyHtml">压缩</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">压缩结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"压缩","fn":"minifyHtml"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 HTML，点击“压缩”。</li>
  <li>删除注释、标签间空白与多余空格，压缩为单行紧凑格式。</li>
  <li>注意：压缩会改变代码可读性，生产构建时使用。</li>
</ol>`,
  faq: [{"q":"会破坏 script 内容吗？","a":"标签间的空白压缩不影响 script 内部字符串，但 \u003cpre>/\u003ctextarea> 内的空白可能变化，谨慎使用。"},{"q":"能还原吗？","a":"不能，压缩不可逆；请保留原文件。"}],
};
