/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'html-strip',
  name: 'HTML 转纯文本',
  desc: '去除 HTML 标签与实体，保留文字内容，网页内容清洗工具。',
  keywords: 'html转文本,去除html标签,标签剥离,html清洗,纯文本提取',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 HTML 源码"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="stripHtml">去除 HTML</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">纯文本</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"去除 HTML","fn":"stripHtml"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 HTML 代码，点击“去除 HTML”。</li>
  <li>剥离所有标签（<...>），还原 &amp;nbsp; &amp;lt; 等常见实体，压缩多余空行。</li>
  <li>适合抓取网页内容、邮件正文转纯文本。</li>
</ol>`,
  faq: [{"q":"script/style 里的内容会保留吗？","a":"标签会被剥离，但 script/style 标签内部的 JS/CSS 文本仍会保留；需先手动删除。"},{"q":"图片 alt 文字会提取吗？","a":"不会，只保留标签外的文本节点；需要 alt 建议用 DOM 解析器处理。"},{"q":"会保留段落换行吗？","a":"会尽力保留：块级标签之间的换行会压缩为单个空行，方便阅读。"}],
};
