/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'html-tags',
  name: 'HTML 标签速查',
  desc: 'HTML 常用标签速查表：标签名、用途与说明，覆盖结构、文本、表单、多媒体等。',
  keywords: 'html标签大全,html标签速查,html元素,标签列表,html教程参考',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"标签","swatch":false,"mono":true},{"key":1,"label":"名称","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入标签名（form）、用途（表格）或说明…", dense: true },
  body: ``,
  usage: `<ol>
  <li>表格列出常用 HTML 标签及其用途说明。</li>
  <li>按语义分组：结构（header/nav/main）、文本（p/strong/em）、表单（form/input）、媒体（img/video）等。</li>
  <li>写页面时优先使用语义化标签，对 SEO 和无障碍友好。</li>
</ol>`,
  faq: [{"q":"div 和语义标签怎么选？","a":"能表达含义时优先用语义标签（nav、article、aside 等），它们对搜索引擎和无障碍工具更友好；div/span 只是通用容器，留给没有合适语义的场景。"},{"q":"details/summary 需要 JS 吗？","a":"不需要，它们是原生的折叠交互元素，浏览器内置展开/收起行为，还能配合 CSS 定制样式，非常适合 FAQ 场景。"},{"q":"dialog 元素兼容性如何？","a":"现代浏览器均已支持原生 dialog（模态框），配合 showModal() 可替代自建弹窗，自带焦点管理和 Esc 关闭，无需额外 JS 库。"}],
};
