/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'html-colors',
  name: 'HTML 基础颜色速查',
  desc: 'HTML 基础颜色速查：20 个经典颜色的十六进制值与名称。',
  keywords: 'html颜色,基础颜色,颜色名称,十六进制颜色,网页颜色,color names',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"颜色名","swatch":false,"mono":false},{"key":1,"label":"色值","swatch":true,"mono":true},{"key":2,"label":"英文","swatch":false,"mono":false}], search: "输入颜色名（红）或色值（FF0000）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查 HTML 经典颜色与十六进制值，带色块预览。</li><li>搜索支持按名称或色值过滤。</li><li>快速取基础色；完整色表见“CSS 颜色名速查”。</li></ol>`,
  faq: [{"q":"和 CSS 颜色名速查什么区别？","a":"本表为基础 20 色快速参考；CSS 速查含全部 140+ 颜色名。"},{"q":"颜色名大小写敏感吗？","a":"不敏感，HTML/CSS 颜色名不区分大小写。"}],
};
