/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'http-cache',
  name: 'HTTP 缓存头速查',
  desc: 'HTTP 缓存机制速查：Cache-Control、ETag、条件请求等。',
  keywords: 'http缓存,缓存头,cache-control,etag,缓存策略,浏览器缓存',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"头/指令","swatch":false,"mono":true},{"key":1,"label":"类型","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入头名（ETag）或用途（缓存）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查HTTP 缓存头。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"C","a":"a"},{"q":"缓","a":"存"}],
};
