/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'http-methods',
  name: 'HTTP 方法速查',
  desc: 'HTTP 请求方法速查：GET/POST/PUT/PATCH/DELETE 等方法的用途、安全性与幂等性。',
  keywords: 'http方法,请求方法,get post,put patch,http协议,restful方法',
  category: 'ref',
  kind: 'table',
  table: { columns: [{"key":0,"label":"方法","swatch":false,"mono":true},{"key":1,"label":"用途","swatch":false,"mono":false},{"key":2,"label":"安全/幂等","swatch":false,"mono":false},{"key":3,"label":"典型场景","swatch":false,"mono":false}], search: "输入方法名（POST）、属性（幂等）或场景…", dense: false },
  body: ``,
  usage: `<ol>
  <li>表格列出标准 HTTP 方法及扩展方法：用途、是否安全、是否幂等与典型场景。</li>
  <li>“安全”指不会改变服务器状态（GET/HEAD/OPTIONS）；“幂等”指多次执行结果一致（PUT/DELETE）。</li>
  <li>设计 REST API 时按语义选择方法，能获得更好的缓存与重试行为。</li>
</ol>`,
  faq: [{"q":"PUT 和 PATCH 有什么区别？","a":"PUT 是整体替换资源（客户端提交完整表示），幂等；PATCH 是部分更新（只提交要改的字段），不保证幂等。"},{"q":"浏览器只支持 GET/POST，怎么办？","a":"HTML 表单只支持 GET 和 POST，但可在 POST 中携带 _method 字段由服务端解释为 PUT/DELETE，或直接用 fetch/XHR 发送任意方法。"},{"q":"OPTIONS 预检请求是什么？","a":"跨域请求若触发 CORS 预检，浏览器会先发 OPTIONS 询问服务器允许哪些方法/头，服务器响应 Access-Control-Allow-* 头后才会发真实请求。"}],
};
