/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ideal-weight',
  name: '理想体重计算',
  desc: '理想体重范围：由身高与性别算出健康体重区间（BMI 18.5-23.9）。',
  keywords: '理想体重,标准体重,健康体重,bmi范围,体重区间,身高体重',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">身高（厘米）</label>
  <input type="number" id="ci-0" value="170" placeholder="">
</div><div class="field"><label for="ci-1">性别</label><select id="ci-1"><option value="male" selected>男</option><option value="female">女</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">健康体重 = 身高² × BMI（18.5-23.9），附 Devine 公式理想体重。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"idealWeightCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入身高与性别，点击“计算”。</li>
  <li>输出健康体重范围（BMI 18.5-23.9）与 Devine 公式理想体重。</li>
  <li>健康管理、体检对照、健身目标设定常用。</li>
</ol>`,
  faq: [{"q":"BMI 适合所有人吗？","a":"不完美：肌肉量大的人 BMI 偏高但健康；老人与儿童参考标准不同。请结合体脂率综合判断。"},{"q":"亚洲标准更严格吗？","a":"中国标准 18.5-23.9 为正常，24-27.9 超重，≥28 肥胖；比 WHO 标准略严。"}],
};
