/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ideal-waist',
  name: '理想腰围计算',
  desc: '理想腰围估算：按身高与性别给出健康腰围参考值。',
  keywords: '理想腰围,健康腰围,腰围标准,身高腰围,体型参考,腰围计算',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">身高（cm）</label>
  <input type="number" id="ci-0" value="175" placeholder="">
</div><div class="field"><label for="ci-1">性别</label><select id="ci-1"><option value="male" selected>男</option><option value="female">女</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">经验公式：男 身高×0.47，女 身高×0.42；健康腰围上限男 85cm、女 80cm。</div>
<script type="application/json" id="c-cfg">{"lib":"dev2","fn":"idealWaistCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入身高与性别，点击“计算”。</li>
  <li>得到经验理想腰围与健康上限参考。</li>
  <li>健身目标设定、体型管理参考。</li>
</ol>`,
  faq: [{"q":"公式准确吗？","a":"为经验估算，个体骨架差异大；健康核心标准是腰围不超过上限。"},{"q":"腰围超标一定不健康吗？","a":"腰围只是风险指标之一，结合体脂率、血压血脂综合判断。"}],
};
