/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-invert',
  name: '图片反色',
  desc: '图片反色（负片）效果：RGB 通道取反，生成负片风格图片。',
  keywords: '图片反色,负片效果,反相,invert,照片反转,颜色取反',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<div class="note">反色即每个像素 RGB 值取 255-原值，得到底片效果。</div><script type="application/json" id="ie-cfg">{"effect":"invert","params":[]}</script>`,
  usage: `<ol><li>上传图片，自动预览反色效果。</li><li>下载保存结果。</li><li>X 光片、暗房效果、创意设计常用。</li></ol>`,
  faq: [{"q":"反色能还原吗？","a":"可以！再执行一次反色即恢复原图（255-(255-x)=x）。"},{"q":"适合什么图片？","a":"高对比构图效果强烈；人像肤色会变得奇怪，慎用。"}],
};
