/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-sepia',
  name: '图片怀旧滤镜',
  desc: '图片怀旧（棕褐）滤镜：一键给照片添加复古色调，本地处理。',
  keywords: '怀旧滤镜,棕褐,老照片,复古滤镜,sepia,照片做旧',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<div class="note">棕褐色调（Sepia）模拟老照片质感，适合怀旧风格处理。</div><script type="application/json" id="ie-cfg">{"effect":"sepia","params":[]}</script>`,
  usage: `<ol><li>上传图片，自动预览怀旧效果。</li><li>下载 PNG 保存。</li><li>老照片翻新、复古海报常用。</li></ol>`,
  faq: [{"q":"Sepia 滤镜的原理？","a":"按经典系数矩阵（0.393R+0.769G+0.189B 等）混合 RGB 通道，模拟银盐照片老化色调。"},{"q":"会损失画质吗？","a":"PNG 无损输出；颜色信息被替换，无法还原原彩色。"}],
};
