/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-hue',
  name: '图片色相旋转',
  desc: '图片色相旋转：整体改变色调（0-360°），创意调色效果。',
  keywords: '图片色相,色相旋转,色调调整,hue,调色,色彩变换',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="row">
  <div class="field grow">
    <label for="ie-p-amount" class="field-label">色相旋转（%360°）</label>
    <input type="range" id="ie-p-amount" min="0" max="100" value="30">
  </div>
  <span class="range-val" id="ie-p-amount-v">30%</span>
</div>
<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<script type="application/json" id="ie-cfg">{"effect":"hue","params":[{"name":"amount","type":"range"}]}</script>`,
  usage: `<ol><li>上传图片，拖动色相滑块实时预览。</li><li>30% ≈ 旋转 108°，整体色调漂移。</li><li>下载保存创意调色结果。</li></ol>`,
  faq: [{"q":"色相旋转会改变亮度吗？","a":"只旋转色相环，明度与饱和度保持不变（近似）。"},{"q":"适合什么场景？","a":"创意海报、赛博朋克风格、UI 配色快速试色。"}],
};
