/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-rounded',
  name: '图片圆角',
  desc: '图片圆角处理：给图片加圆角，滑块控制圆角大小，头像卡片常用。',
  keywords: '图片圆角,圆角图片,头像圆角,圆角处理,rounded,圆角裁剪',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="row">
  <div class="field grow">
    <label for="ie-p-radius" class="field-label">圆角大小</label>
    <input type="range" id="ie-p-radius" min="0" max="50" value="15">
  </div>
  <span class="range-val" id="ie-p-radius-v">15%</span>
</div>
<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<script type="application/json" id="ie-cfg">{"effect":"rounded","params":[{"name":"radius","type":"range"}]}</script>`,
  usage: `<ol><li>上传图片，拖动圆角大小实时预览。</li><li>生成透明背景的圆角 PNG，适合头像、卡片。</li><li>下载保存结果。</li></ol>`,
  faq: [{"q":"圆角图片背景透明吗？","a":"是，导出 PNG 保留透明通道，可直接叠加到任意背景。"},{"q":"圆角最大值是多少？","a":"滑块最大为短边 50%，即完全椭圆/圆形效果。"}],
};
