/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-mirror',
  name: '图片镜像翻转',
  desc: '图片水平/垂直镜像：左右翻转、上下翻转，一键处理。',
  keywords: '图片镜像,水平翻转,垂直翻转,左右镜像,上下翻转,图片翻转',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<div class="note">水平镜像=左右翻转（selfie 效果），垂直镜像=上下翻转。</div><script type="application/json" id="ie-cfg">{"effect":"mirror","params":[]}</script>`,
  usage: `<ol><li>上传图片，自动预览镜像效果。</li><li>下载保存结果。</li><li>水平镜像常用于自拍修正；垂直镜像用于创意设计。</li></ol>`,
  faq: [{"q":"镜像会改变图片尺寸吗？","a":"不会，仅翻转方向，宽高不变。"},{"q":"文字会变反吗？","a":"会，镜像后文字左右颠倒；这是镜像的正常效果。"}],
};
