/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-sharpen',
  name: '图片锐化',
  desc: '图片锐化：增强边缘细节，让照片更清晰，可调节强度。',
  keywords: '图片锐化,锐化工具,照片清晰,边缘增强,sharpen,清晰度',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="row">
  <div class="field grow">
    <label for="ie-p-amount" class="field-label">锐化强度</label>
    <input type="range" id="ie-p-amount" min="10" max="100" value="50">
  </div>
  <span class="range-val" id="ie-p-amount-v">50%</span>
</div>
<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<script type="application/json" id="ie-cfg">{"effect":"sharpen","params":[{"name":"amount","type":"range"}]}</script>`,
  usage: `<ol><li>上传图片，拖动锐化强度实时预览。</li><li>适度锐化让边缘更利落；过度会出现白边与噪点。</li><li>下载保存结果。</li></ol>`,
  faq: [{"q":"锐化能修复模糊照片吗？","a":"只能视觉上增强边缘对比，无法恢复已丢失的细节；对轻微模糊有效。"},{"q":"为什么会出现光晕？","a":"锐化在边缘产生过冲（overshoot），强度过高时光晕明显；建议强度 30-60%。"}],
};
