/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-info',
  name: '图片信息查看',
  desc: '图片信息查看：尺寸、宽高比、文件大小、类型一键分析。',
  keywords: '图片信息,图片尺寸,查看图片,图片属性,宽高比,图片详情',
  category: 'image',
  kind: 'image',
  script: 'image-analyze',
  
  body: `<div class="field">
  <div class="dropzone" id="ia-drop" tabindex="0" role="button" aria-label="选择图片">
    点击或拖拽图片到此处<br><small>JPG / PNG / WebP，本地分析不上传</small>
    <input type="file" id="ia-file" accept="image/*" class="hidden">
  </div>
</div>
<div class="output">
  <div class="output-label">分析结果</div>
  <div id="ia-out">等待选择图片…</div>
</div>
<script type="application/json" id="ia-cfg">{"mode":"info"}</script>`,
  usage: `<ol><li>上传图片，自动分析尺寸、比例、大小与类型。</li><li>所有分析在浏览器本地完成。</li><li>检查图片是否超限、确认比例适配场景常用。</li></ol>`,
  faq: [{"q":"能看 EXIF 吗？","a":"当前显示尺寸/大小/类型；EXIF 信息受浏览器安全限制，部分图片可读。"},{"q":"支持哪些格式？","a":"浏览器可解码的格式均可：JPG、PNG、WebP、GIF、SVG 等。"}],
};
