/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-resize',
  name: '图片缩放',
  desc: '图片缩放：按最长边像素等比缩小，适合压缩超大图片。',
  keywords: '图片缩放,图片改尺寸,压缩图片,等比缩放,resize,缩小图片',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="row">
  <div class="field grow">
    <label for="ie-p-scale" class="field-label">最长边（%原尺寸）</label>
    <input type="range" id="ie-p-scale" min="10" max="100" value="50">
  </div>
  <span class="range-val" id="ie-p-scale-v">50%</span>
</div>
<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<div class="note">等比缩放，保持宽高比；缩到 50% 时 PNG 体积约降为 1/4。</div><script type="application/json" id="ie-cfg">{"effect":"resize","params":[{"name":"scale","type":"range"}]}</script>`,
  usage: `<ol><li>上传图片，拖动比例实时预览缩放结果。</li><li>等比缩小大图（如 4000px → 2000px）。</li><li>下载保存；进一步减小体积可配合“图片压缩”。</li></ol>`,
  faq: [{"q":"能放大图片吗？","a":"可以（比例>100%），但放大是插值，画质不会提升；建议只缩小。"},{"q":"输出格式？","a":"当前导出 PNG；需要 JPG 请用“图片格式转换”工具。"}],
};
