/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-colors',
  name: '图片主色提取',
  desc: '图片主色提取：自动分析图片主色调与占比，配色灵感工具。',
  keywords: '图片取色,主色提取,配色提取,图片配色,色卡生成,dominant color',
  category: 'image',
  kind: 'image',
  script: 'image-analyze',
  
  body: `<div class="field">
  <div class="dropzone" id="ia-drop" tabindex="0" role="button" aria-label="选择图片">
    点击或拖拽图片到此处<br><small>JPG / PNG / WebP，本地分析不上传</small>
    <input type="file" id="ia-file" accept="image/*" class="hidden">
  </div>
</div>
<div class="output">
  <div class="output-label">分析结果</div>
  <div id="ia-out">等待选择图片…</div>
</div>
<script type="application/json" id="ia-cfg">{"mode":"colors"}</script>`,
  usage: `<ol><li>上传图片，自动提取 Top 8 主色与占比。</li><li>输出十六进制色值，可直接用于设计。</li><li>品牌配色分析、网页取色、海报灵感常用。</li></ol>`,
  faq: [{"q":"提取准确吗？","a":"基于缩略图统计（近似），适合主色调分析；精确取色请用“图片取色”工具。"},{"q":"透明区域怎么处理？","a":"透明像素会被忽略，不影响主色统计。"}],
};
