/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'image-blur',
  name: '图片模糊',
  desc: '图片高斯模糊：调节模糊强度，隐私遮挡、背景虚化效果。',
  keywords: '图片模糊,高斯模糊,模糊处理,背景虚化,打码模糊,blur',
  category: 'image',
  kind: 'image',
  script: 'image-effect',
  
  body: `<div class="field">
  <div class="dropzone" id="ie-drop" tabindex="0" role="button" aria-label="选择图片">
  点击或拖拽图片到此处<br><small>JPG / PNG / WebP，处理在本地完成，不上传</small>
  <input type="file" id="ie-file" accept="image/*" class="hidden">
</div>
</div>

<div class="row">
  <div class="field grow">
    <label for="ie-p-amount" class="field-label">模糊强度</label>
    <input type="range" id="ie-p-amount" min="5" max="100" value="15">
  </div>
  <span class="range-val" id="ie-p-amount-v">15%</span>
</div>
<div class="toolbar">
  <button id="ie-download" class="btn" disabled>下载 PNG</button>
  <span class="spacer"></span>
  <button id="ie-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="img-meta" id="ie-meta"></div>
<div class="output">
  <canvas id="ie-canvas" style="display:none" aria-label="处理后的图片预览"></canvas>
</div>
<script type="application/json" id="ie-cfg">{"effect":"blur","params":[{"name":"amount","type":"range"}]}</script>`,
  usage: `<ol><li>上传图片，拖动模糊强度实时预览。</li><li>适合脸部打码、背景虚化、隐私遮挡。</li><li>下载保存结果。</li></ol>`,
  faq: [{"q":"是高斯模糊吗？","a":"实现为两遍盒式模糊（近似高斯），效果柔和；强度越大处理越慢。"},{"q":"模糊能还原吗？","a":"不能，模糊丢失高频细节；隐私打码请用不可逆的强模糊。"}],
};
