/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'imperial-units',
  name: '英制单位换算',
  desc: '英制与公制单位换算速查：英寸、磅、加仑、华氏度等对照。',
  keywords: '英制单位,单位换算,英寸厘米,磅公斤,加仑升,华氏度',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"英制","swatch":false,"mono":false},{"key":1,"label":"公制","swatch":false,"mono":false}], search: "输入单位（加仑）或数值过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查英制单位换算。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"英","a":"制"},{"q":"美","a":"制"}],
};
