/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'income-tax',
  name: '个人所得税计算器',
  desc: '个人所得税计算器：综合所得年度汇算，含专项附加扣除估算。',
  keywords: '个税计算,个人所得税,个税计算器,工资个税,年度汇算,税率表',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">年收入（元）</label>
  <input type="number" id="ci-0" value="200000" placeholder="">
</div><div class="field">
  <label for="ci-1">专项附加扣除（元/年）</label>
  <input type="number" id="ci-1" value="0" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按综合所得 7 级超额累进税率估算；五险一金未计入，实际以税务系统为准。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"incomeTaxCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入年收入与专项附加扣除（子女教育、房贷、赡养老人等合计），点击“计算”。</li>
  <li>得到应纳税所得额、税率、全年税额与月均税额。</li>
  <li>仅供参考，汇算清缴以个税 APP 为准。</li>
</ol>`,
  faq: [{"q":"起征点是多少？","a":"每月 5000 元，即年 6 万元；超过部分按 3%-45% 七级累进。"},{"q":"专项附加扣除有哪些？","a":"子女教育、继续教育、大病医疗、住房贷款利息、住房租金、赡养老人、3 岁以下婴幼儿照护。"}],
};
