/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ip-convert',
  name: 'IP 进制转换',
  desc: 'IPv4 与十进制/二进制/十六进制互转：点分十进制 ↔ 整数。',
  keywords: 'ip转换,ip进制,ipv4转十进制,ip转二进制,ip转整数,ip计算',
  category: 'web',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入 IP（192.168.1.1）或十进制整数"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="ipConvert">转换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev2","actions":[{"label":"转换","fn":"ipConvert"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入点分 IP 或 0-4294967295 的十进制整数，点击“转换”。</li>
  <li>输出对应的十进制、32 位二进制与十六进制。</li>
  <li>理解 IP 存储、数据库存整数 IP、日志分析常用。</li>
</ol>`,
  faq: [{"q":"为什么要转整数？","a":"数据库存整数 IP 比字符串省空间、查询快；很多日志/GeoIP 库用整数表示。"},{"q":"支持 IPv6 吗？","a":"暂不支持；IPv6 为 128 位，需专门工具。"}],
};
