/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ip-extract',
  name: 'IP 地址提取',
  desc: '从文本中提取全部 IPv4 地址，校验合法范围后逐行列出。',
  keywords: '提取ip,ip提取,ipv4提取,ip地址筛选,日志ip,批量提取ip',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴日志或文本（含 IP 地址）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractIpv4">提取 IPv4</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取 IPv4","fn":"extractIpv4"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本点击“提取 IPv4”，识别 0.0.0.0-255.255.255.255 范围的合法地址。</li>
  <li>结果逐行列出；如需统计出现次数可复制到文本统计工具按词频查看。</li>
  <li>适合分析访问日志、防火墙规则中的 IP。</li>
</ol>`,
  faq: [{"q":"支持 IPv6 吗？","a":"目前仅提取 IPv4；IPv6 地址格式复杂（含 :: 缩写），后续版本考虑支持。"},{"q":"192.168.1.999 会提取吗？","a":"不会，超过 255 的段不符合 IPv4 规则会被忽略。"},{"q":"端口号会一起提取吗？","a":"只提取 IP 本身（如 1.2.3.4），:8080 端口号不会包含。"}],
};
