/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'iso-langs',
  name: 'ISO 语言代码速查',
  desc: 'ISO 639 语言代码速查表：zh/en/ja 等 32 种语言代码。',
  keywords: '语言代码,iso639,语言标识,zh en,国际化,i18n',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"代码","swatch":false,"mono":true},{"key":1,"label":"中文名","swatch":false,"mono":false},{"key":2,"label":"英文名","swatch":false,"mono":false}], search: "输入代码（zh）或语言（英语）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查ISO 语言代码。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"语","a":"言"},{"q":"代","a":"码"}],
};
