/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'js-minify',
  name: 'JS 压缩',
  desc: 'JS 基础压缩：去除注释、行尾空白与多余空格，保留可读性。',
  keywords: 'js压缩,javascript压缩,去注释,js精简,代码压缩',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 JavaScript 源码"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="minifyJs">压缩</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">压缩结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"压缩","fn":"minifyJs"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 JS，点击“压缩”。</li>
  <li>删除注释、多余空格与空行，保留换行结构便于阅读。</li>
  <li>比完整 minifier 保守，保证语法不被破坏。</li>
</ol>`,
  faq: [{"q":"能压缩变量名吗？","a":"不能（需完整 AST 分析）；本工具只做空白与注释清理，安全性优先。"},{"q":"模板字符串里的内容会变吗？","a":"不会，字符串与模板字面量内容保持原样。"}],
};
