/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'json-yaml',
  name: 'JSON 转 YAML',
  desc: 'JSON 转 YAML 配置：粘贴 JSON 一键生成 YAML 缩进格式。',
  keywords: 'json转yaml,yaml转换,配置转换,json格式化,yaml生成',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 JSON，如 {"name":"x","age":18}"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="jsonToYaml">转换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">YAML</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"convert3","actions":[{"label":"转换","fn":"jsonToYaml"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 JSON，点击“转换”。</li>
  <li>生成缩进格式的 YAML 配置。</li>
  <li>Docker Compose、CI 配置、K8s 清单转写常用。</li>
</ol>`,
  faq: [{"q":"嵌套对象支持吗？","a":"支持，任意深度嵌套与数组都会转成 YAML 缩进结构。"},{"q":"字符串什么时候加引号？","a":"含特殊字符（冒号空格、# 等）的字符串自动加引号，保证合法。"}],
};
