/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'json-diff',
  name: 'JSON 对比',
  desc: '两个 JSON 差异对比：逐路径输出新增、删除与修改，接口联调神器。',
  keywords: 'json对比,json diff,json差异,接口对比,json比较工具',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="旧 JSON 粘贴在这里

---

新 JSON 粘贴在分隔线下面"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="jsonDiff">对比</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">差异结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>
<div class="note">两个 JSON 用<b>仅含 --- 的一行</b>分隔（旧 JSON 在上，新 JSON 在下），点击"对比"即可逐路径查看差异。</div>
<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"对比","fn":"jsonDiff"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>把旧 JSON 粘贴在上方，写一行 <code>---</code> 分隔线，再把新 JSON 粘贴在下方。</li>
  <li>点击“对比”，按路径列出差异：- 删除/修改前，+ 新增/修改后。</li>
  <li>完全一致时提示“两个 JSON 完全一致”。</li>
</ol>`,
  faq: [{"q":"两个 JSON 怎么分隔？","a":"在两个 JSON 之间加一行仅含 --- 的分隔线（至少三个减号），工具会自动按行拆分对比。"},{"q":"支持数组对比吗？","a":"支持，数组按下标逐项比较（a[0]、a[1]…），并输出增删项。"},{"q":"键顺序不同算差异吗？","a":"不算。JSON 对象键无序，工具按键名对比，顺序不影响结果。"}],
};
