/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'json-path',
  name: 'JSON 路径提取',
  desc: 'JSON 路径列表：列出全部叶子节点的路径与值，调试解析逻辑。',
  keywords: 'json路径,jsonpath,字段路径,json结构分析,key路径',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 JSON"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="jsonPaths">提取路径</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">路径列表</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"提取路径","fn":"jsonPaths"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 JSON，点击“提取路径”。</li>
  <li>输出每个叶子字段的完整路径（a.b.c）与值类型。</li>
  <li>写 JSONPath 查询、理解接口结构时快速参考。</li>
</ol>`,
  faq: [{"q":"路径格式是什么？","a":"点号分隔：{\"a\":{\"b\":1}} 的叶子路径为 a.b，值 1 (number)。"},{"q":"数组元素怎么表示？","a":"数组元素按下标并入路径：list.0.name。"}],
};
