/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'json-to-go',
  name: 'JSON 转 Go 结构体',
  desc: 'JSON 转 Go struct：字段名自动转驼峰，附 json tag，Go 开发必备。',
  keywords: 'json转go,go结构体,struct生成,go类型,json tag',
  category: 'dev',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 JSON，如 {"user_name":"x","age":18}"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="jsonToGo">转换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">Go 结构体</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"转换","fn":"jsonToGo"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 JSON，点击“转换”。</li>
  <li>生成 Go struct：字段名转驼峰（user_name→UserName），整数转 int64、小数转 float64。</li>
  <li>带 json:"原名" tag，可直接粘贴使用。</li>
</ol>`,
  faq: [{"q":"时间字段怎么处理？","a":"当前按字符串处理；需要 time.Time 请手动修改字段类型。"},{"q":"嵌套结构体呢？","a":"当前只生成顶层结构体，嵌套对象内联展开；复杂结构建议逐层转换。"}],
};
