/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'json-to-ts',
  name: 'JSON 转 TypeScript 接口',
  desc: 'JSON 转 TypeScript 接口定义：一键生成 interface，前后端类型对齐。',
  keywords: 'json转ts,json转typescript,ts接口生成,type生成,类型定义',
  category: 'dev',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 JSON，如 {"name":"张三","age":18}"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="jsonToTs">转换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">TS 接口</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"转换","fn":"jsonToTs"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴接口返回的 JSON 示例，点击“转换”。</li>
  <li>生成嵌套 interface Data，字段类型按值推断（string/number/boolean/数组）。</li>
  <li>直接复制进 .ts 文件使用。</li>
</ol>`,
  faq: [{"q":"嵌套对象怎么处理？","a":"内嵌对象会生成扁平化的 interface 结构（内部展开），字段层级完整保留。"},{"q":"数组元素类型怎么推断？","a":"取数组第一个元素的类型作为元素类型；空数组生成 any[]。"}],
};
