/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'key-symbols',
  name: '键盘符号速查',
  desc: '键盘特殊符号速查：~!@# 等符号的键位与输入方法。',
  keywords: '键盘符号,特殊符号键位,shift键,符号输入,键盘大全',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"符号","swatch":false,"mono":true},{"key":1,"label":"名称","swatch":false,"mono":false},{"key":2,"label":"输入","swatch":false,"mono":false}], search: "输入符号（@）或键位（Shift）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查键盘符号。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"多","a":"数"},{"q":"中","a":"文"}],
};
