/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'keyboard-shift',
  name: '键盘移位密码',
  desc: '键盘移位密码：按 QWERTY 键盘同行左右移动字符，趣味文本变换。',
  keywords: '键盘移位,键盘密码,qwerty,手滑密码,错位输入,字符移位',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本（如 hello → jr;;p）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="keyboardShiftRight">右移一位</button><button id="x-run-1" class="btn btn-ghost" data-fn="keyboardShiftLeft">左移一位</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"右移一位","fn":"keyboardShiftRight"},{"label":"左移一位","fn":"keyboardShiftLeft"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“右移”：每个字符在同一键盘行向右移一格（h→j）；“左移”反向。</li>
  <li>模拟手放在错误位置打字的“手滑密码”。</li>
  <li>左移可还原右移结果（反之亦然）。</li>
</ol>`,
  faq: [{"q":"还原需要几次？","a":"一次反向移动即可还原；连续右移两次需左移两次还原。"},{"q":"特殊字符会处理吗？","a":"只在同一键盘行内移动（含数字行与符号），行首行尾循环，中文保留原样。"}],
};
