/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'keyword-count',
  name: '关键词计数',
  desc: '统计指定关键词在文本中出现的次数，支持长词与多关键词（逗号分隔）。',
  keywords: '关键词统计,关键词计数,词频统计,关键词出现次数,文本计数',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴待统计的文本"></textarea>
</div>
<div class="field"><label for="xp-0">关键词（逗号分隔多个）</label><input type="number" id="xp-0" value=""></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="countKeywords">统计次数</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">统计结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"统计次数","fn":"countKeywords"}],"multi":false,"auto":false,"params":[{"name":"keyword","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写关键词（多个用逗号分隔），粘贴文本。</li>
  <li>点击“统计次数”，输出每个关键词及其出现次数。</li>
  <li>适合检查文案关键词密度、统计日志中的错误码出现次数。</li>
</ol>`,
  faq: [{"q":"关键词是精确匹配吗？","a":"是的，按字符串精确匹配（区分大小写），重叠部分各计一次。"},{"q":"能统计全部词频吗？","a":"单关键词计数适合固定词；全文词频请使用“字符频率统计”工具。"}],
};
