/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'keyword-density',
  name: '关键词密度分析',
  desc: '文本关键词密度分析：分词统计高频词占比，SEO 内容优化参考。',
  keywords: '关键词密度,词频分析,seo关键词,密度检测,关键词优化',
  category: 'dev',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴网页文本或文章内容"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="keywordDensity">分析</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">词频统计</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"分析","fn":"keywordDensity"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本，点击“分析”。</li>
  <li>按出现次数降序列出 Top 30 词与占比。</li>
  <li>单字中文按字统计；英文按单词统计。</li>
</ol>`,
  faq: [{"q":"关键词密度多少合适？","a":"主流建议 1%-3%，过度堆砌会被判关键词堆砌；内容自然优先。"},{"q":"为什么单字也算？","a":"中文无空格分词，本工具以单字+英文单词为最小单位；短语密度建议用“关键词计数”。"}],
};
