/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'km-miles',
  name: '公里英里换算',
  desc: '公里与英里、千米与海里快速互转，跑步与自驾换算常用。',
  keywords: '公里英里,km英里,英里换算,千米海里,跑步距离换算,英里公里',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数值</label>
  <input type="number" id="ci-0" value="5" placeholder="">
</div><div class="field"><label for="ci-1">输入单位</label><select id="ci-1"><option value="km" selected>公里</option><option value="mi">英里</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">1 英里 = 1.609344 公里；更多长度单位见“单位换算”。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"kmMiles","unit":""}</script>`,
  usage: `<ol>
  <li>输入数值，选择输入单位（公里或英里），点击“计算”。</li>
  <li>输出对应公里/英里对照。</li>
  <li>海外跑步配速、自驾里程估算、地图距离换算常用。</li>
</ol>`,
  faq: [{"q":"马拉松 42.195 公里是几英里？","a":"约 26.22 英里，对应英文 marathon 的 26.2 英里说法。"},{"q":"海里和英里一样吗？","a":"不一样：1 海里 = 1.852 公里（用于航海/航空），1 英里 = 1.609 公里。"}],
};
