/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'latex-symbols',
  name: 'LaTeX 符号速查',
  desc: 'LaTeX 常用符号速查表：数学公式、希腊字母、矩阵、箭头等 35 个命令。',
  keywords: 'latex符号,latex公式,数学公式,latex命令,latex速查,公式排版',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"LaTeX","swatch":false,"mono":true},{"key":1,"label":"含义","swatch":false,"mono":false}], search: "输入命令（\\sum）或含义（积分）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查 LaTeX 常用命令：分式、根号、求和、希腊字母。</li><li>搜索支持按命令或含义过滤。</li><li>学术论文、Markdown 数学公式、Obsidian/Notion 写作常用。</li></ol>`,
  faq: [{"q":"在哪里用 LaTeX？","a":"LaTeX 文档、Markdown 的 $...$ 行内公式、$$...$$ 块级公式（如 GitHub、Typora）。"},{"q":"希腊字母大小写怎么写？","a":"小写 \\alpha、\\beta…；大写 \\Alpha 等首字母大写（部分大写希腊字母与英文相同则无命令）。"}],
};
