/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'leap-year',
  name: '闰年判断',
  desc: '闰年判断：输入年份即知是否闰年、二月天数与全年天数。',
  keywords: '闰年判断,闰年计算,二月天数,366天,平年闰年,闰年查询',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">年份</label>
  <input type="number" id="ci-0" value="2024" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">规则：能被 4 整除且不能被 100 整除，或能被 400 整除。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"leapYearCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入年份，点击“计算”。</li>
  <li>输出是否闰年、二月天数与全年天数。</li>
  <li>排期、合同日期、程序开发判断日期合法时常用。</li>
</ol>`,
  faq: [{"q":"1900 年是闰年吗？","a":"不是。1900 能被 100 整除但不能被 400 整除，所以是平年；2000 年才是闰年。"},{"q":"为什么要有闰年？","a":"公历年约 365.2422 天，每 4 年加一天（闰日）补偿，再用百年/四百年的规则修正误差。"}],
};
