/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'line-numbers',
  name: '文本加行号',
  desc: '给文本每行添加行号（可自定义起始值），代码展示、日志整理常用。',
  keywords: '加行号,行号工具,文本行号,代码行号,行号前缀',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要加行号的文本"></textarea>
</div>
<div class="field"><label for="xp-0">起始值</label><input type="number" id="xp-0" value="1" min="0"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="numberLines">加行号</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"加行号","fn":"numberLines"}],"multi":false,"auto":false,"params":[{"name":"start","type":"number"}]}</script>`,
  usage: `<ol>
  <li>输入文本，设置起始行号（默认 1），点击“加行号”。</li>
  <li>行号以 4 位宽度右对齐前缀（如 0001），便于对齐阅读。</li>
  <li>粘贴代码、配置或日志片段后加行号，方便引用具体位置。</li>
</ol>`,
  faq: [{"q":"起始值可以是 0 吗？","a":"可以，设为 0 即可从 0 开始编号；设为负数也会从 0 截断为 0。"},{"q":"行号会和代码一起复制吗？","a":"会，结果就是“行号 + 内容”的纯文本，适合粘贴到文档中。"},{"q":"空行也编号吗？","a":"是的，所有行（含空行）都会编号，保证与原文行数一致。"}],
};
