/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'log-calc',
  name: '对数计算',
  desc: '对数计算器：任意底对数、自然对数、常用对数与以 2 为底对数。',
  keywords: '对数计算,log,自然对数,常用对数,log2,对数求解',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">真数（>0）</label>
  <input type="number" id="ci-0" value="1000" placeholder="">
</div><div class="field">
  <label for="ci-1">底数（>0 且 ≠1）</label>
  <input type="number" id="ci-1" value="10" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">默认底数 10：log10(1000)=3。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"logCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入真数与底数（默认 10），点击“计算”。</li>
  <li>输出任意底对数、ln、log10 与 log2 四种结果。</li>
  <li>信息论（log2）、酸碱度（pH=-log10）、复杂度分析常用。</li>
</ol>`,
  faq: [{"q":"底数为什么不能是 1？","a":"log₁(x) = x÷log(1) 分母为 0，数学上 1 的任何次幂都是 1，无法表示其他数。"},{"q":"真数能为 0 或负数吗？","a":"不能，实数范围内对数只在正数上有定义，工具会提示。"}],
};
