/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'lorem-cn',
  name: '中文占位文本',
  desc: '中文占位文本生成：随机中文句子，排版预览与设计稿占位。',
  keywords: '中文占位,假文生成,占位文本,中文lorem,排版预览,内容占位',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">句子数</label><input type="number" id="gp-0" value="3" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">生成通顺的中文占位句（我们/生活/梦想…组合）。</div>
<script type="application/json" id="g-cfg">{"lib":"text3","fn":"loremCn","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>设置句子数量，点击“生成”。</li>
  <li>输出随机中文占位文本。</li>
  <li>设计稿、页面排版预览、内容占位常用。</li>
</ol>`,
  faq: [{"q":"和 Lorem ipsum 什么区别？","a":"Lorem 是拉丁文占位，本工具生成可读中文，更贴近中文排版观感。"},{"q":"句子通顺吗？","a":"模板化组合基本通顺，偶有抽象组合属正常。"}],
};
