/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'love-letter',
  name: '情书生成器',
  desc: '情书生成器：输入对方名字，一键生成一封温暖的小情书。',
  keywords: '情书生成,情书,表白信,情书模板,写情书,告白文案',
  category: 'life',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="（无需输入，直接点击生成）"></textarea>
</div>
<div class="field"><label for="xp-0">对方名字</label><input type="text" id="xp-0" value="亲爱的"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="loveLetter">生成情书</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">情书</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"life","actions":[{"label":"生成情书","fn":"loveLetter"}],"multi":false,"auto":false,"params":[{"name":"name","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写对方名字（可选），点击“生成情书”。</li>
  <li>随机组合温柔词句，生成一封真挚的小情书。</li>
  <li>多生成几次挑选最顺眼的一封。</li>
</ol>`,
  faq: [{"q":"情书内容会重复吗？","a":"由多个词库随机组合，每次略有不同；多生成几次挑喜欢的。"},{"q":"可以直接发吗？","a":"建议稍作修改加入你们的专属回忆，会更打动人心。"}],
};
