/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'lucky-number',
  name: '幸运数字查询',
  desc: '幸运数字与幸运颜色：按名字生成专属幸运数字、颜色与星期。',
  keywords: '幸运数字,幸运颜色,幸运星期,幸运查询,每日幸运,专属数字',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">名字</label><input type="text" id="ci-0" value="小明" placeholder=""></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按名字码点确定性生成（同名结果一致），趣味参考。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"luckyNumber","unit":""}</script>`,
  usage: `<ol>
  <li>输入名字，点击“计算”。</li>
  <li>得到幸运数字（1-9）、幸运颜色与幸运星期。</li>
  <li>选彩票号、挑颜色时参考，娱乐为主。</li>
</ol>`,
  faq: [{"q":"为什么选 1-9？","a":"按码点和对 9 取模映射 1-9，对应传统数字文化中的单数吉位。"},{"q":"结果稳定吗？","a":"稳定，同名永远得到相同结果。"}],
};
