/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'magic-numbers',
  name: '文件魔数识别',
  desc: '文件头魔数速查：PNG/JPEG/PDF/ZIP 等 30+ 格式的十六进制文件头。',
  keywords: '文件魔数,文件头,文件签名,十六进制文件头,文件格式识别,file signature',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"魔数(hex)","swatch":false,"mono":true},{"key":1,"label":"格式","swatch":false,"mono":false}], search: "输入魔数（8950）或格式（PDF）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查常见文件格式的十六进制文件头（魔数）。</li><li>搜索支持按魔数或格式名过滤。</li><li>配合十六进制查看工具识别无扩展名文件的真实格式。</li></ol>`,
  faq: [{"q":"什么是魔数？","a":"文件开头固定的几个字节，用于标识文件类型（如 PNG 固定 89 50 4E 47）。"},{"q":"怎么用魔数识别文件？","a":"用十六进制工具查看文件头，对照本表即可判断真实格式，与扩展名无关。"}],
};
