/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'markdown-strip',
  name: 'Markdown 转纯文本',
  desc: '去除 Markdown 语法符号保留文字：标题、加粗、链接、代码块、列表。',
  keywords: 'markdown转文本,去除markdown,md转纯文本,markdown清洗,markdown预览',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 Markdown 内容"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="stripMarkdown">去除 Markdown</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">纯文本</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"去除 Markdown","fn":"stripMarkdown"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 Markdown 文本，点击“去除 Markdown”。</li>
  <li>去掉 # 标题符、**加粗**、*斜体*、[文字](链接) 语法等，保留可读文字。</li>
  <li>适合把文档转换成纯文本做字数统计或进一步处理。</li>
</ol>`,
  faq: [{"q":"代码块怎么处理？","a":"代码块围栏（```）被移除，代码内容保留；行内代码 `x` 转为 x。"},{"q":"链接保留文字还是 URL？","a":"保留链接文字并移除 URL：[文字](url) 变“文字”。"},{"q":"表格会被转换吗？","a":"表格的分隔符会被剥离但管道符 | 保留；如需表格转 CSV 请用 CSV 工具。"}],
};
