/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'math-symbols',
  name: '数学符号速查',
  desc: '常用数学符号速查表：运算符、集合、逻辑、几何符号与含义，可复制使用。',
  keywords: '数学符号,数学符号大全,运算符符号,集合符号,逻辑符号,公式符号',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"符号","swatch":false,"mono":true},{"key":1,"label":"含义","swatch":false,"mono":false}], search: "输入符号（∑）或名称（积分）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查数学符号含义，符号列可直接复制使用。</li><li>搜索支持按符号或名称过滤。</li><li>写公式、LaTeX、文档时快速取符号。</li></ol>`,
  faq: [{"q":"符号能直接复制吗？","a":"可以，点击复制按钮或选中符号复制，Unicode 字符在文档中通用。"},{"q":"LaTeX 里怎么写这些符号？","a":"多数有对应命令，如 sum、int、in、\forall；本站另有 LaTeX 符号速查可参考。"}],
};
