/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'meme-words',
  name: '网络流行语速查',
  desc: '网络流行语大全：YYDS、破防、内卷等热词含义速查。',
  keywords: '网络流行语,网络热词,流行语大全,梗百科,yyds,热词解释',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"热词","swatch":false,"mono":true},{"key":1,"label":"含义","swatch":false,"mono":false}], search: "输入热词（YYDS）或含义（网络）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查网络流行语含义。</li><li>搜索支持按热词或含义过滤。</li><li>刷社交平台、看懂评论区的必备词典。</li></ol>`,
  faq: [{"q":"更新频率如何？","a":"收录近年流行热词；新词层出不穷，会持续更新。"},{"q":"有谐音梗吗？","a":"有，如“尊嘟假嘟”标注为谐音用法。"}],
};
