/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'meme-words',
  name: '网络流行语速查',
  desc: '网络流行语速查：YYDS、破防、内卷等热词含义，一键生成随机热词。',
  keywords: '网络流行语,网络热词,梗百科,yyds,破防,流行语大全',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="5" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">内置 20 条网络热词与含义解释，刷社交平台必备。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomMeme","multi":false,"batch":1}</script>`,
  usage: `<ol><li>设置数量，点击“生成”。</li><li>输出热词与含义，每行一个。</li><li>看懂评论区、写文案、聊天不落伍。</li></ol>`,
  faq: [{"q":"热词更新及时吗？","a":"收录近年流行热词；新词层出不穷，会持续更新。"},{"q":"有谐音梗吗？","a":"有，如“尊嘟假嘟”标注为谐音用法。"}],
};
