/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'mock-data',
  name: 'Mock 数据生成器',
  desc: '假数据生成器：姓名/手机/邮箱/城市/公司等字段的 JSON 测试数据一键生成。',
  keywords: 'mock数据,假数据,测试数据生成,json假数据,模拟数据,接口测试数据',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量（1-50）</label><input type="number" id="gp-0" value="5" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">输出含 id/name/phone/email/age/city/company/score 等字段的 JSON 数组。</div>
<script type="application/json" id="g-cfg">{"lib":"gen-extra","fn":"randomMockData","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>设置数据条数（1-50），点击“生成”。</li>
  <li>输出格式化的 JSON 数组，字段含姓名、手机号、邮箱、年龄、城市等。</li>
  <li>前端联调、接口 mock、表格演示数据直接复制使用。</li>
</ol>`,
  faq: [{"q":"能自定义字段吗？","a":"暂不支持自定义结构；需要特定字段可复制结果后用文本工具修改。"},{"q":"输出格式？","a":"JSON 数组（格式化缩进），前端可直接 JSON.parse 使用。"}],
};
