/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'moment-copy',
  name: '朋友圈文案生成',
  desc: '朋友圈文案生成器：日常/心情/晒图文案，配图灵感来源。',
  keywords: '朋友圈文案,文案生成,发圈文案,心情文案,晒图配文',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="1" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">内置 16 条日常与心情文案，可直接使用。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomMoment","multi":false,"batch":1}</script>`,
  usage: `<ol><li>设置数量，点击“生成”。</li><li>输出朋友圈文案。</li><li>晒图配文、心情记录、社交运营常用。</li></ol>`,
  faq: [{"q":"文案能商用吗？","a":"短文案通用性高，但建议稍作个性化修改。"},{"q":"有节日文案吗？","a":"当前以日常为主，节日文案后续补充。"}],
};
