/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'name-match',
  name: '姓名配对测试',
  desc: '姓名缘分测试：输入两人名字计算缘分值，娱乐向趣味测试。',
  keywords: '姓名配对,名字配对,缘分测试,姓名缘分,情侣测试,配对测试',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">名字一</label><input type="text" id="ci-0" value="张伟" placeholder=""></div><div class="field"><label for="ci-1">名字二</label><input type="text" id="ci-1" value="李娜" placeholder=""></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按名字 Unicode 码点加权生成 60-99 的稳定缘分值（同名字结果一致）。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"nameMatch","unit":""}</script>`,
  usage: `<ol>
  <li>输入两个人的名字，点击“计算”。</li>
  <li>得到缘分值（60-99）与趣味评价。</li>
  <li>仅供娱乐，结果请一笑了之。</li>
</ol>`,
  faq: [{"q":"为什么同名字结果一样？","a":"基于名字码点的确定性算法，保证可复现；不同名组合结果不同。"},{"q":"结果会变吗？","a":"不会，同名字永远是同一结果（非随机）。"}],
};
