/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'network-terms',
  name: '网络术语速查',
  desc: '网络基础术语速查：IP、DNS、TCP、CDN 等 24 个术语解释。',
  keywords: '网络术语,网络基础,ip地址,dns,tcp,网络知识',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"术语","swatch":false,"mono":true},{"key":1,"label":"类型","swatch":false,"mono":false},{"key":2,"label":"解释","swatch":false,"mono":false}], search: "输入术语（DNS）或解释（加密）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查网络术语。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"理","a":"解"},{"q":"T","a":"C"}],
};
