/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'number-extract',
  name: '数字提取',
  desc: '从文本中提取全部数字（整数或含小数），逐行列出，统计汇总方便。',
  keywords: '提取数字,数字提取,提取整数,提取小数,数值筛选,数字抽取',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴含数字的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractNumbers">提取整数</button><button id="x-run-1" class="btn btn-ghost" data-fn="extractNumbersDecimal">含小数</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取整数","fn":"extractNumbers"},{"label":"含小数","fn":"extractNumbersDecimal"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本，点击“提取整数”或“含小数”。</li>
  <li>负号会保留（-5），小数模式匹配 -3.14 格式；科学计数法暂不支持。</li>
  <li>提取后可复制到计算工具做求和、平均值。</li>
</ol>`,
  faq: [{"q":"支持千分位逗号吗？","a":"不支持，1,234 会提取出 1 和 234 两个数；建议先去除逗号再提取。"},{"q":"能排除版本号吗？","a":"不能自动区分语义；若只想取纯数值，可先删除版本号文本。"}],
};
