/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'number-english',
  name: '数字转英文',
  desc: '整数与小数的英文读法（含分数部分），支票、发票、英文文书场景。',
  keywords: '数字转英文,英文数字,英文读法,支票大写,number to english,英文金额',
  category: 'convert',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入数字，如 1234.56"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="numberToEnglish">转换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">英文读法</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"convert-extra","actions":[{"label":"转换","fn":"numberToEnglish"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入数字（支持负数与两位小数），点击“转换”。</li>
  <li>整数部分用英文读法（thousand/million…），小数部分以分数形式输出。</li>
  <li>填写英文支票、发票、合同金额时规范表达。</li>
</ol>`,
  faq: [{"q":"小数部分怎么读？","a":"按百分比分数读：1234.56 → one thousand two hundred thirty-four and 56/100，符合英文支票写法。"},{"q":"最大支持多大数字？","a":"支持到 quadrillion（10¹⁵）量级，更大数值请用科学计数法工具。"}],
};
