/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'number-format',
  name: '数字格式化',
  desc: '数字格式化：千分位、小数位、百分比格式化工具。',
  keywords: '数字格式化,千分位,小数位,百分比格式,数字显示,格式化数字',
  category: 'text',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数字</label>
  <input type="number" id="ci-0" value="1234567.891" placeholder="" step="any">
</div><div class="field">
  <label for="ci-1">小数位</label>
  <input type="number" id="ci-1" value="2" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出千分位分隔的格式化数字（zh-CN 格式）。</div>
<script type="application/json" id="c-cfg">{"lib":"text3","fn":"formatNumberWith","unit":""}</script>`,
  usage: `<ol>
  <li>输入数字与小数位，点击“计算”。</li>
  <li>输出千分位分隔的格式化结果。</li>
  <li>金额展示、数据报表、图表标签常用。</li>
</ol>`,
  faq: [{"q":"能转百分比吗？","a":"百分比格式见“百分比格式化”工具（需先把数字除以 100）。"},{"q":"支持负数吗？","a":"支持，负号保留。"}],
};
