/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pace-table',
  name: '跑步配速对照',
  desc: '跑步配速对照：距离+用时 → 配速、速度与马拉松预估。',
  keywords: '跑步配速,马拉松预估,配速对照,半马全马,跑步计算,比赛配速',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">距离（km）</label>
  <input type="number" id="ci-0" value="10" placeholder="" step="0.1">
</div><div class="field"><label for="ci-1">用时（时:分:秒）</label><input type="text" id="ci-1" value="1:00:00" placeholder=""></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">时间格式：1:30:00（时分秒）或 30:00（分秒）。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"paceTable","unit":""}</script>`,
  usage: `<ol><li>输入跑步距离与用时，点击“计算”。</li><li>得到配速、速度与半马/全马完赛预估。</li><li>制定训练目标、比赛配速策略常用。</li></ol>`,
  faq: [{"q":"全马 3 小时配速多少？","a":"42.195km ÷ 3h ≈ 4分15秒/公里；用本工具可反推。"},{"q":"能输入英里吗？","a":"当前按公里；英里×1.609 换算后输入。"}],
};
