/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pace-calc',
  name: '跑步配速计算',
  desc: '跑步配速计算：距离与用时 → 配速（分/公里）与速度。',
  keywords: '跑步配速,配速计算,马拉松配速,跑步速度,配速表,pacing',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">距离（公里）</label>
  <input type="number" id="ci-0" value="5" placeholder="" step="any">
</div><div class="field">
  <label for="ci-1">时（小时）</label>
  <input type="number" id="ci-1" value="0" placeholder="">
</div><div class="field">
  <label for="ci-2">分</label>
  <input type="number" id="ci-2" value="30" placeholder="">
</div><div class="field">
  <label for="ci-3">秒</label>
  <input type="number" id="ci-3" value="0" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">如 5 公里用时 30 分钟 → 配速 6分00秒 /公里。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"paceCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入跑步距离与用时（时/分/秒），点击“计算”。</li>
  <li>输出配速（每公里用时）与平均速度。</li>
  <li>训练计划、比赛目标设定、跑量记录常用。</li>
</ol>`,
  faq: [{"q":"马拉松 3 小时完赛配速多少？","a":"42.195 公里 ÷ 3 小时 ≈ 4分15秒 /公里，速度约 14 公里/小时。"},{"q":"配速单位能换成每英里吗？","a":"当前输出每公里配速；换算英里需 × 1.609。"}],
};
