/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pad-lines',
  name: '文本填充对齐',
  desc: '文本填充工具：左/右/居中对齐并按宽度补空格，排版整理。',
  keywords: '文本填充,对齐填充,左对齐,右对齐,居中,补空格',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入多行文本"></textarea>
</div>
<div class="field"><label for="xp-0">宽度</label><input type="number" id="xp-0" value="20" min="1"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="padLinesLeft">左对齐</button><button id="x-run-1" class="btn btn-ghost" data-fn="padLinesRight">右对齐</button><button id="x-run-2" class="btn btn-ghost" data-fn="padLinesCenter">居中</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"左对齐","fn":"padLinesLeft"},{"label":"右对齐","fn":"padLinesRight"},{"label":"居中","fn":"padLinesCenter"}],"multi":false,"auto":false,"params":[{"name":"width","type":"number"}]}</script>`,
  usage: `<ol>
  <li>输入文本与目标宽度，选择对齐方式。</li>
  <li>每行按宽度补空格：左对齐（右补）、右对齐（左补）、居中。</li>
  <li>终端输出、ASCII 排版、注释对齐常用。</li>
</ol>`,
  faq: [{"q":"行超宽怎么办？","a":"超过宽度的行保持原样不裁剪。"},{"q":"中文对齐效果如何？","a":"按字符数补空格；中文与英文混排时视觉宽度不同，建议按列处理。"}],
};
