/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'paper-sizes',
  name: '纸张尺寸速查',
  desc: '纸张尺寸速查：A/B/C 系列、开本、照片尺寸毫米对照表。',
  keywords: '纸张尺寸,a4尺寸,纸张大小,a4纸,开本尺寸,打印尺寸',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"规格","swatch":false,"mono":false},{"key":1,"label":"尺寸(mm)","swatch":false,"mono":true},{"key":2,"label":"用途","swatch":false,"mono":false}], search: "输入规格（A4）或用途（打印）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查纸张与照片尺寸（毫米）。</li><li>搜索支持按规格或用途过滤。</li><li>打印设置、设计排版、证件照尺寸常用。</li></ol>`,
  faq: [{"q":"A 系列纸张的规律？","a":"A 系列长宽比 √2:1，对半裁切后仍是同比例；每大一号面积翻倍。"},{"q":"正度/大度开本什么区别？","a":"正度（787×1092）与大度（889×1194）是印刷用纸规格，开本尺寸略有差异。"}],
};
