/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'passphrase',
  name: '密码短语生成',
  desc: '密码短语生成：可读单词组合（correct-horse-battery 风格），易记且安全。',
  keywords: '密码短语,口令生成,易记密码,单词密码,passphrase,安全口令',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="3" min="1"></div><div class="field"><label for="gp-1">单词数</label><input type="number" id="gp-1" value="4" min="2"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">形容词+名词组合加数字后缀，如 Bright-Moon-Star-Cloud42。</div>
<script type="application/json" id="g-cfg">{"lib":"text3","fn":"passphrase","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>设置数量与单词数，点击“生成”。</li>
  <li>输出易读的密码短语。</li>
  <li>比随机字符好记，安全性取决于单词数（建议 4+）。</li>
</ol>`,
  faq: [{"q":"密码短语安全吗？","a":"4 个随机单词组合约有数十亿种可能；配合特殊字符替换更安全。"},{"q":"单词库有多大？","a":"内置 16 名词 + 10 形容词，组合空间有限；重要账号建议用随机密码生成器。"}],
};
