/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'password-leak',
  name: '密码泄露检查',
  desc: '密码泄露检查：查询密码是否出现在公开泄露数据库中（k-anonymity 保护隐私）。',
  keywords: '密码泄露,密码安全,泄露检查,have i been pwned,密码风险,安全检测',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="api-form">
  <div class="field grow">
    <label for="api-password">要检查的密码</label>
    <input type="password" id="api-password" placeholder="输入密码（仅本地计算哈希）">
  </div>
  <button id="api-run" class="btn">检查</button>
</div>
<div class="output">
  <div class="output-label">检查结果</div>
  <div id="api-out"></div>
</div>
<div class="note">🔒 隐私保护：采用 k-anonymity 方案，仅发送密码 SHA-1 哈希的前 5 位，完整密码绝不出浏览器。</div>
<script type="application/json" id="api-cfg">{"type":"pwned"}</script>`,
  usage: `<ol><li>输入要检查的密码，点击"检查"。</li><li>查询 Have I Been Pwned 泄露数据库。</li><li>若显示已泄露，请立即更换该密码。</li></ol>`,
  faq: [{"q":"密码会发送到服务器吗？","a":"不会。仅发送 SHA-1 哈希前 5 位（k-anonymity），服务端返回前缀匹配列表，完整密码与哈希都不会离开浏览器。"},{"q":"泄露数据来源？","a":"Have I Been Pwned 收集了历次公开数据泄露事件（约 100 亿条记录）的哈希。"},{"q":"没泄露就安全吗？","a":"只说明不在已知泄露库中；仍需使用强密码、不同网站不同密码并开启双重认证。"}],
};
