/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pbkdf2',
  name: 'PBKDF2 密钥派生',
  desc: 'PBKDF2-SHA256 密码派生：把弱密码经多轮迭代转成强密钥，用于口令存储与加密密钥。',
  keywords: 'pbkdf2,密码派生,密钥派生,口令哈希,加盐哈希,密码存储',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入密码（口令）"></textarea>
</div>
<div class="field"><label for="xp-0">盐（Salt）</label><input type="text" id="xp-0" value="random-salt"></div><div class="field"><label for="xp-1">迭代次数</label><input type="number" id="xp-1" value="10000"></div><div class="field"><label for="xp-2">输出长度（字节）</label><input type="number" id="xp-2" value="32"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="pbkdf2">派生</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">派生密钥（十六进制）</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"派生","fn":"pbkdf2"}],"multi":false,"auto":false,"params":[{"name":"salt","type":"text"},{"name":"iterations","type":"number"},{"name":"length","type":"number"}]}</script>`,
  usage: `<ol>
  <li>填写盐与迭代次数，输入密码。</li>
  <li>点击“派生”得到十六进制密钥（默认 32 字节 = 256 位）。</li>
  <li>存储口令时应为每个用户使用随机盐，并选择尽量高的迭代次数（如 60 万次以上）。</li>
</ol>`,
  faq: [{"q":"为什么要加盐？","a":"盐让相同密码产生不同哈希，阻止彩虹表预计算攻击，也使两个相同密码的存储值不同。"},{"q":"迭代次数越多越好吗？","a":"迭代次数越大破解成本越高，但服务端验证也越慢；业界建议在可接受延迟内取最大值（OWASP 建议 SHA-256 60 万次+）。"},{"q":"PBKDF2 和 bcrypt/argon2 比如何？","a":"PBKDF2 是 NIST 标准、内置广泛，但对 GPU 并行破解不够抵抗；argon2id 是最新推荐，bcrypt 次之。"}],
};
