/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'percent-error',
  name: '百分比误差',
  desc: '计算测量值与真实值的相对误差百分比，实验数据评估常用。',
  keywords: '百分比误差,相对误差,误差计算,测量误差,实验误差',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">测量值</label>
  <input type="number" id="ci-0" value="98" placeholder="">
</div><div class="field">
  <label for="ci-1">真实值</label>
  <input type="number" id="ci-1" value="100" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">误差 = |测量值-真实值| ÷ |真实值| × 100%。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"percentError","unit":""}</script>`,
  usage: `<ol>
  <li>输入测量值与真实值（理论值），点击“计算”。</li>
  <li>输出相对误差百分比。</li>
  <li>物理实验、仪器校准、生产质量评估常用。</li>
</ol>`,
  faq: [{"q":"误差和偏差一样吗？","a":"相对误差是误差与真实值的比值；偏差通常指与平均值的差，概念不同。"},{"q":"真实值为 0 怎么办？","a":"真实值为 0 时相对误差无定义，工具会提示；此时应使用绝对误差。"}],
};
