/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'percent-calc',
  name: '百分比计算器',
  desc: '百分比计算：求一个数的百分比、占比、变化率，一键出结果。',
  keywords: '百分比计算器,百分比计算,占比计算,变化率,百分之几,百分数',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数值</label>
  <input type="number" id="ci-0" value="200" placeholder="">
</div><div class="field">
  <label for="ci-1">百分比（%）</label>
  <input type="number" id="ci-1" value="15" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">如 200 的 15% = 30；求占比（部分÷总数）可用“占比计算”功能。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"percentOf","unit":""}</script>`,
  usage: `<ol>
  <li>输入数值与百分比，点击“计算”。</li>
  <li>结果即“数值 × 百分比 ÷ 100”，如 200 的 15% = 30。</li>
  <li>求“某数是总数的百分之几”请用占比计算工具。</li>
</ol>`,
  faq: [{"q":"怎么求一个数占总数的百分比？","a":"用本工具的“占比”模式：部分 ÷ 总数 × 100%，如 30/200 = 15%。"},{"q":"支持小数吗？","a":"支持，输入 12.5% 这样的小数百分比也能正确计算。"}],
};
