/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'percent-format',
  name: '百分比格式化',
  desc: '百分比格式化：小数转百分比并控制小数位（0.156 → 15.60%）。',
  keywords: '百分比格式,小数转百分比,百分比显示,比例格式化,格式化工具',
  category: 'text',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">小数（0-1）</label>
  <input type="number" id="ci-0" value="0.156" placeholder="" step="any">
</div><div class="field">
  <label for="ci-1">小数位</label>
  <input type="number" id="ci-1" value="2" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">0.156 → 15.60%；输入 1 表示 100%。</div>
<script type="application/json" id="c-cfg">{"lib":"text3","fn":"formatPercent","unit":""}</script>`,
  usage: `<ol>
  <li>输入小数（0-1）与小数位，点击“计算”。</li>
  <li>输出带 % 的格式化结果。</li>
  <li>统计占比、数据可视化、报告排版常用。</li>
</ol>`,
  faq: [{"q":"大于 1 会怎样？","a":"按比例输出，如 1.5 → 150.00%。"},{"q":"和百分比计算器区别？","a":"计算器算“某数的百分之几”，本工具只做显示格式化。"}],
};
