/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'percent-change',
  name: '百分比变化率',
  desc: '计算两个数值之间的变化量与变化率（涨跌幅），投资与数据分析常用。',
  keywords: '百分比变化,变化率计算,涨跌幅,环比,同比,增长率',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">原值</label>
  <input type="number" id="ci-0" value="100" placeholder="">
</div><div class="field">
  <label for="ci-1">新值</label>
  <input type="number" id="ci-1" value="120" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出变化量（新值-原值）与变化率（变化量÷原值×100%）。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"percentChange","unit":""}</script>`,
  usage: `<ol>
  <li>输入原值（基准值）与新值，点击“计算”。</li>
  <li>得到绝对变化量与相对变化率，如 100→120 变化率 +20%。</li>
  <li>计算涨跌幅、业绩环比、价格波动率都适用。</li>
</ol>`,
  faq: [{"q":"原值可以为 0 吗？","a":"不能。原值为 0 时变化率无定义（任何数÷0 都是无穷大），工具会提示“原值不能为 0”。"},{"q":"负值怎么处理？","a":"原值或新值为负时按公式正常计算，变化率会给出带正负号的结果。"}],
};
