/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'perm-comb',
  name: '排列组合计算',
  desc: '排列 P(n,r) 与组合 C(n,r) 计算器，精确大数运算。',
  keywords: '排列组合,排列计算,组合计算,p(n,r),c(n,r),概率计算,阶乘组合',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">总数 n</label>
  <input type="number" id="ci-0" value="10" placeholder="">
</div><div class="field">
  <label for="ci-1">选取 r</label>
  <input type="number" id="ci-1" value="3" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">P 考虑顺序（排列），C 不考虑顺序（组合）；需 0 ≤ r ≤ n。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"permCombCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入总数 n 与选取数 r（0≤r≤n），点击“计算”。</li>
  <li>输出排列数 P(n,r)（有顺序）与组合数 C(n,r)（无顺序）。</li>
  <li>彩票概率、抽奖方案、密码组合数计算常用。</li>
</ol>`,
  faq: [{"q":"P 和 C 什么区别？","a":"P(10,3)=720（选出 3 个并排序），C(10,3)=120（只选不排）；C = P ÷ r!。"},{"q":"n 能多大？","a":"上限 170（与阶乘一致），结果用 BigInt 精确输出，可能很长。"}],
};
