/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pet-name',
  name: '宠物名生成器',
  desc: '宠物名生成器：猫咪狗狗名字批量生成，支持种类选择。',
  keywords: '宠物名,宠物起名,猫咪名字,狗狗名字,宠物名字大全',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="5" min="1"></div><div class="field"><label for="gp-1">宠物类型</label><select id="gp-1"><option value="any" selected>随机</option><option value="cat">猫咪</option><option value="dog">狗狗</option></select></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">组合式生成（小豆/奶糖/旺财…），含专属名库。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomPetName","multi":false,"batch":1}</script>`,
  usage: `<ol><li>选择宠物类型与数量，点击“生成”。</li><li>输出候选宠物名。</li><li>领养取名、开宠物店、游戏宠物命名常用。</li></ol>`,
  faq: [{"q":"名字会重复吗？","a":"组合式生成重复率低；多生成几次挑选。"},{"q":"有英文名吗？","a":"当前为中文名；英文名可用“英文名生成器”。"}],
};
