/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pet-age',
  name: '宠物年龄换算',
  desc: '宠物年龄换算：狗狗/猫咪年龄转人类年龄，了解毛孩子的成长阶段。',
  keywords: '宠物年龄,狗年龄,猫年龄,狗狗几岁,猫咪年龄换算,宠物年龄计算',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">宠物年龄</label>
  <input type="number" id="ci-0" value="3" placeholder="">
</div><div class="field"><label for="ci-1">宠物类型</label><select id="ci-1"><option value="dog" selected>狗狗</option><option value="cat">猫咪</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">常见估算：1 岁≈15 人岁，2 岁≈24 人岁，之后每年≈4 人岁。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"petAge","unit":""}</script>`,
  usage: `<ol>
  <li>输入宠物年龄并选择类型，点击“计算”。</li>
  <li>查看对应的人类年龄估算。</li>
  <li>帮助理解宠物所处生命阶段（幼年/成年/老年）。</li>
</ol>`,
  faq: [{"q":"大型犬和小型犬一样吗？","a":"不完全一样：大型犬衰老更快（2 岁后每年约 5-6 人岁），小型犬约 4 人岁；本工具按通用值。"},{"q":"猫咪怎么算？","a":"猫 1 岁≈15 人岁、2 岁≈24 人岁，之后每年≈4 人岁；与小型犬接近。"}],
};
