/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'phone-extract',
  name: '手机号提取',
  desc: '从文本中提取手机号与固话号码，支持 86 前缀，去重后列出。',
  keywords: '提取手机号,手机号提取,电话号码提取,号码筛选,批量提取手机号',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴含电话号码的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractPhones">提取号码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取号码","fn":"extractPhones"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本，点击“提取号码”。</li>
  <li>支持 1[3-9] 开头的 11 位手机号（可带 +86/086 前缀与连字符）及 0 开头的固话。</li>
  <li>适合从报名表、聊天记录中批量收集联系电话。</li>
</ol>`,
  faq: [{"q":"为什么有些号码没提取到？","a":"号段必须符合 1[3-9] 规则；虚拟号段、被空格或符号分隔的号码可能漏检。"},{"q":"隐私合规要注意什么？","a":"批量处理他人手机号需确保已获得授权并遵守个人信息保护法；本站工具纯本地运行。"}],
};
