/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'phone-mask',
  name: '手机号脱敏',
  desc: '手机号、身份证、邮箱、姓名、银行卡一键脱敏，分享数据时保护隐私。',
  keywords: '手机号脱敏,脱敏工具,数据脱敏,隐私保护,掩码,打码工具',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴需要脱敏的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="maskPhone">手机号</button><button id="x-run-1" class="btn btn-ghost" data-fn="maskIdCard">身份证</button><button id="x-run-2" class="btn btn-ghost" data-fn="maskEmail">邮箱</button><button id="x-run-3" class="btn btn-ghost" data-fn="maskName">中文姓名</button><button id="x-run-4" class="btn btn-ghost" data-fn="maskBankCard">银行卡</button><button id="x-run-5" class="btn btn-ghost" data-fn="maskAll">全部打码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">脱敏结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"手机号","fn":"maskPhone"},{"label":"身份证","fn":"maskIdCard"},{"label":"邮箱","fn":"maskEmail"},{"label":"中文姓名","fn":"maskName"},{"label":"银行卡","fn":"maskBankCard"},{"label":"全部打码","fn":"maskAll"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本，选择脱敏类型（可多次执行叠加不同规则）。</li>
  <li>手机号：138****1234；身份证：前 6 后 4；邮箱：a***@；姓名：张*；银行卡：6222 **** **** 1234。</li>
  <li>适合开发测试数据、日志上报前的隐私处理。</li>
</ol>`,
  faq: [{"q":"脱敏能逆推吗？","a":"不能。本工具用 * 直接替换中间位，原数据不保留、不加密存储，无法还原。"},{"q":"姓名脱敏规则？","a":"保留姓（首字），其余汉字用 * 替代；两个字的姓名如“张伟”变“张*”。"},{"q":"能识别所有格式吗？","a":"按常见格式匹配：11 位手机号、18 位身份证、标准邮箱、12-19 位银行卡。特殊格式可能漏配。"}],
};
