/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pigpen',
  name: '猪圈密码',
  desc: '猪圈密码（Pigpen Cipher）编解码：经典网格替换密码，趣味解密工具。',
  keywords: '猪圈密码,pigpen,网格密码,古典密码,密文解密,趣味密码',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入字母或 [网格符号] 编码文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="pigpenEncode">编码</button><button id="x-run-1" class="btn btn-ghost" data-fn="pigpenDecode">解码</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"编码","fn":"pigpenEncode"},{"label":"解码","fn":"pigpenDecode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“编码”：字母转为网格位置符号 [行列]（带点/叉标记区分三组网格）。</li>
  <li>“解码”：粘贴符号文本还原字母。</li>
  <li>解密题、游戏彩蛋、密室逃脱谜题常用。</li>
</ol>`,
  faq: [{"q":"猪圈密码安全吗？","a":"不安全，只是历史上用于简单保密与共济会装饰；现在主要用于谜题与娱乐。"},{"q":"I 和 J 怎么处理？","a":"传统猪圈密码 26 字母分 3×9 网格，I/J 共用一个位置；编码时 J 归为 I。"}],
};
