/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'pinyin-first',
  name: '汉字拼音首字母',
  desc: '提取汉字的拼音首字母（覆盖约 3000 常用字），用于姓名缩写、索引生成。',
  keywords: '拼音首字母,汉字转拼音,首字母提取,姓名缩写,拼音索引',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入中文（如：张三 → ZS）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="cjkToPinyinFirst">提取首字母</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取首字母","fn":"cjkToPinyinFirst"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入中文文本，点击“提取首字母”。</li>
  <li>每个汉字输出拼音首字母（大写），如“中国”→“ZG”；非汉字原样保留。</li>
  <li>适合姓名缩写、通讯录索引、编码简写。</li>
</ol>`,
  faq: [{"q":"生僻字能转换吗？","a":"内置约 3000 个一级常用字；生僻字、多音字无法识别时原样保留该字。"},{"q":"多音字怎么办？","a":"按常用读音取首字母（如“行”默认 H），如需精确多音字需专用词典。"}],
};
