/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'placeholder-image',
  name: '占位图生成',
  desc: '占位图生成器：指定宽高与文字生成灰色占位图，页面开发常用。',
  keywords: '占位图,占位图片,placeholder,图片占位,默认图生成,灰图',
  category: 'image',
  kind: 'image',
  script: 'image-gen',
  
  body: `<div class="field">
  <label for="ig-run" class="field-label">参数</label>
</div>

<div class="field">
  <label for="ig-p-width" class="field-label">宽度（px）</label>
  <input type="number" id="ig-p-width" value="400" min="32">
</div>
<div class="field">
  <label for="ig-p-height" class="field-label">高度（px）</label>
  <input type="number" id="ig-p-height" value="300" min="32">
</div>
<div class="field">
  <label for="ig-p-text" class="field-label">文字</label>
  <input type="text" id="ig-p-text" value="400 × 300">
</div>
<div class="toolbar">
  <button id="ig-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button id="ig-download" class="btn btn-ghost" disabled>下载 PNG</button>
</div>
<div class="output">
  <canvas id="ig-canvas" aria-label="生成结果"></canvas>
</div>
<script type="application/json" id="ig-cfg">{"type":"placeholder","params":[{"name":"width","type":"number"},{"name":"height","type":"number"},{"name":"text","type":"text"}]}</script>`,
  usage: `<ol><li>设置宽高与文字，点击“生成”。</li><li>生成灰色带边框占位图，可下载 PNG。</li><li>前端布局开发、图片加载前占位、设计稿演示常用。</li></ol>`,
  faq: [{"q":"能生成 SVG 吗？","a":"当前输出 PNG；需要 SVG 可用文本占位替代。"},{"q":"最大尺寸？","a":"支持最大 1600×1600，更大建议用图片处理工具缩放。"}],
};
