/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'port-lookup',
  name: '端口服务查询',
  desc: '常用端口查询：输入端口号查看对应服务（MySQL 3306、Redis 6379 等）。',
  keywords: '端口查询,端口服务,常用端口,端口号,服务端口,端口速查',
  category: 'web',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入端口号，如 3306"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="portLookup">查询</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">查询结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev2","actions":[{"label":"查询","fn":"portLookup"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入端口号（0-65535），点击“查询”。</li>
  <li>返回常用服务对应关系；未收录提示为动态/私有端口。</li>
  <li>排查端口占用、配置防火墙、联调服务常用。</li>
</ol>`,
  faq: [{"q":"端口冲突怎么办？","a":"netstat -ano 查看占用进程（Windows），lsof -i:端口 查看（Linux/Mac），改配置换端口。"},{"q":"所有端口都有固定服务吗？","a":"0-1023 为知名端口（约定俗成），其余可自由使用；本表收录开发常用端口。"}],
};
