/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'power-root',
  name: '幂与根计算',
  desc: '幂、平方根、立方根、倒数计算器，指数与开方快速求解。',
  keywords: '幂计算,平方根,立方根,倒数,指数运算,开方计算器',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">底数</label>
  <input type="number" id="ci-0" value="16" placeholder="" step="any">
</div><div class="field">
  <label for="ci-1">指数</label>
  <input type="number" id="ci-1" value="2" placeholder="" step="any">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">支持小数指数，如 2^0.5 = √2。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"powerRootCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入底数与指数（可为小数），点击“计算”。</li>
  <li>输出幂、平方根、立方根与倒数。</li>
  <li>物理公式计算、利率折算（开根号）、几何计算常用。</li>
</ol>`,
  faq: [{"q":"负底数开根号会怎样？","a":"JS 对负数开偶次根返回 NaN（数学上为虚数），工具会显示“—”，请改用正数或复数工具。"},{"q":"指数可以是分数吗？","a":"可以，如 8^(1/3) 直接输入 0.333 会近似；建议输入精确小数如 0.5。"}],
};
