/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ppi-calc',
  name: 'PPI 像素密度计算',
  desc: '屏幕 PPI 计算：由分辨率与对角线尺寸算出像素密度与物理尺寸。',
  keywords: 'ppi计算,像素密度,屏幕密度,分辨率计算,视网膜屏,retina',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">宽（像素）</label>
  <input type="number" id="ci-0" value="1920" placeholder="">
</div><div class="field">
  <label for="ci-1">高（像素）</label>
  <input type="number" id="ci-1" value="1080" placeholder="">
</div><div class="field">
  <label for="ci-2">对角线（英寸）</label>
  <input type="number" id="ci-2" value="24" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">PPI = √(宽²+高²) ÷ 对角线英寸数。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"ppiCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入屏幕分辨率（宽×高像素）与对角线尺寸（英寸），点击“计算”。</li>
  <li>输出 PPI、物理宽高尺寸。</li>
  <li>挑选显示器、对比手机清晰度时判断细腻程度。</li>
</ol>`,
  faq: [{"q":"PPI 多少算清晰？","a":"一般 200+ 可接受，300+（Retina 级别）肉眼难辨像素；同样 PPI 下观看距离越远越显清晰。"},{"q":"2K/4K 显示器的 PPI 怎么算？","a":"2K（2560×1440）27 英寸约 109 PPI，4K（3840×2160）27 英寸约 163 PPI；填入对应数值即可。"}],
};
