/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'prime-check',
  name: '质数判断',
  desc: '质数判断与质因数分解：输入整数即得是否质数、因数列表与分解式。',
  keywords: '质数判断,质数,素数,质因数分解,因数,素数检测',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">整数（≥2）</label>
  <input type="number" id="ci-0" value="97" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出是否为质数、质因数分解式、因数个数与全部因数。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"primeCheck","unit":""}</script>`,
  usage: `<ol>
  <li>输入一个 ≥2 的整数，点击“计算”。</li>
  <li>得到是否为质数、质因数分解（如 84 = 2×2×3×7）与完整因数列表。</li>
  <li>密码学、数论学习、分数约分时常用。</li>
</ol>`,
  faq: [{"q":"1 是质数吗？","a":"不是。质数定义为“大于 1 且只有 1 和自身两个因数”的自然数，1 只有 1 个因数。"},{"q":"大数判断快吗？","a":"使用试除法（到 √n），万级以下瞬间完成；超大数（10¹⁸ 以上）建议用专业工具。"}],
};
