/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'programming-langs',
  name: '编程语言速查',
  desc: '主流编程语言速查：20 种语言的定位、生态与适用场景。',
  keywords: '编程语言,语言对比,编程语言大全,javascript python,java go rust',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"语言","swatch":false,"mono":false},{"key":1,"label":"领域","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入语言（Python）或领域（前端）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查主流编程语言定位与生态。</li><li>搜索支持按语言名或领域过滤。</li><li>选型学习、职业规划、项目技术栈参考。</li></ol>`,
  faq: [{"q":"新手学什么语言？","a":"兴趣导向：前端学 JS/TS，数据学 Python，后端可 Go/Java；先精通一门再扩展。"},{"q":"语言越多越好吗？","a":"不是，深度比广度重要；建议主攻一门 + 了解 2-3 门。"}],
};
