/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'provinces',
  name: '中国省份速查',
  desc: '中国 34 个省级行政区速查：简称与省会城市对照表。',
  keywords: '省份速查,省级行政区,省份简称,省会城市,中国地图,行政区划',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"省份","swatch":false,"mono":false},{"key":1,"label":"简称","swatch":false,"mono":true},{"key":2,"label":"省会/首府","swatch":false,"mono":false}], search: "输入省份（广东）或简称（粤）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查 34 个省级行政区、简称与省会。</li><li>搜索支持按省名或简称过滤。</li><li>车牌简称、地址填写、数据统计常用。</li></ol>`,
  faq: [{"q":"为什么河北简称冀？","a":"简称多取自古代州名（冀州）、河流（湘江）或历史名称，约定俗成沿用至今。"},{"q":"包括港澳台吗？","a":"包括，台湾、香港、澳门均列入省级行政区速查。"}],
};
