/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'punctuation',
  name: '中文标点速查',
  desc: '中文标点符号大全：用法与写法速查，可复制使用。',
  keywords: '中文标点,标点符号,标点大全,标点用法,标点复制,写作标点',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"符号","swatch":false,"mono":true},{"key":1,"label":"名称","swatch":false,"mono":false}], search: "输入符号（，）或名称（逗号）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查中文标点符号与名称。</li><li>搜索支持按符号或名称过滤，符号可直接复制。</li><li>写作规范、排版输入、文档校对常用。</li></ol>`,
  faq: [{"q":"省略号是几个点？","a":"中文规范为六个点“……”，占两格；三个点“…”是英文用法。"},{"q":"破折号和连接号区别？","a":"破折号“——”表示转折/注释，连接号“—”连接数字范围或复合词。"}],
};
