/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'punycode',
  name: 'Punycode 域名转换',
  desc: '中文域名与 Punycode 互转：输入中文域名转 xn-- 形式，或反向还原。',
  keywords: 'punycode,中文域名,idn域名,国际化域名,xn--,域名编码',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入域名，如：中国.com 或 xn--fiqs8s.com"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="punycodeEncode">中文→Punycode</button><button id="x-run-1" class="btn btn-ghost" data-fn="punycodeDecode">Punycode→中文</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev","actions":[{"label":"中文→Punycode","fn":"punycodeEncode"},{"label":"Punycode→中文","fn":"punycodeDecode"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入中文域名（如 中国.com）点击“中文→Punycode”得到 xn--fiqs8s.com。</li>
  <li>粘贴 xn-- 开头域名点击反向还原。</li>
  <li>DNS 配置、证书签发、邮件头处理时需要。</li>
</ol>`,
  faq: [{"q":"为什么要转 Punycode？","a":"DNS 系统只支持 ASCII，中文域名需编码为 xn-- 前缀的 ASCII 形式才能在 DNS 中使用。"},{"q":"支持 emoji 域名吗？","a":"支持（按 Unicode 码点编码），但 emoji 域名浏览器兼容性差，不建议实际使用。"}],
};
