/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'quadratic',
  name: '一元二次方程',
  desc: '一元二次方程求解器：ax²+bx+c=0 的根、判别式与顶点坐标一键计算。',
  keywords: '二次方程,一元二次,方程求解,判别式,求根公式,数学求解',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">a（x² 系数）</label>
  <input type="number" id="ci-0" value="1" placeholder="">
</div><div class="field">
  <label for="ci-1">b（x 系数）</label>
  <input type="number" id="ci-1" value="-5" placeholder="">
</div><div class="field">
  <label for="ci-2">c（常数项）</label>
  <input type="number" id="ci-2" value="6" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">求根公式：x = (-b ± √(b²-4ac)) / 2a；判别式 Δ=b²-4ac。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"quadraticCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入 a、b、c 三个系数，点击“计算”。</li>
  <li>输出判别式、两个根（或无实数根提示）、顶点坐标与开口方向。</li>
  <li>数学学习、物理抛物运动、工程计算常用。</li>
</ol>`,
  faq: [{"q":"Δ\u003c0 怎么办？","a":"无实数根，方程在实数范围内无解；复数根需专业工具。"},{"q":"a=0 会怎样？","a":"退化为一次方程，本工具提示 a 不能为 0。"}],
};
