/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'quick-convert',
  name: '常用单位速换算',
  desc: '常用单位速换算：厘米英寸、公斤磅、公里英里、温度等一键互转。',
  keywords: '单位速算,厘米英寸,公斤磅,公里英里,摄氏华氏,单位转换',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数值</label>
  <input type="number" id="ci-0" value="10" placeholder="" step="any">
</div><div class="field"><label for="ci-1">从</label><select id="ci-1"><option value="cm" selected>厘米</option><option value="inch">英寸</option><option value="kg">千克</option><option value="lb">磅</option><option value="km">公里</option><option value="mile">英里</option><option value="c">摄氏度</option><option value="f">华氏度</option><option value="m">米</option><option value="ft">英尺</option><option value="l">升</option><option value="gal">加仑</option><option value="hectare">公顷</option><option value="acre">英亩</option></select></div><div class="field"><label for="ci-2">到</label><select id="ci-2"><option value="inch" selected>英寸</option><option value="cm">厘米</option><option value="lb">磅</option><option value="kg">千克</option><option value="mile">英里</option><option value="km">公里</option><option value="f">华氏度</option><option value="c">摄氏度</option><option value="ft">英尺</option><option value="m">米</option><option value="gal">加仑</option><option value="l">升</option><option value="acre">英亩</option><option value="hectare">公顷</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">覆盖长度/重量/距离/温度/体积/面积常用对。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"quickConvert","unit":""}</script>`,
  usage: `<ol><li>输入数值，选择源单位与目标单位，点击“计算”。</li><li>立即得到换算结果。</li><li>买鞋、看美标食谱、跑步换算等日常场景。</li></ol>`,
  faq: [{"q":"支持所有组合吗？","a":"支持表内 14 个单位的常用组合（约 20 对）；其余用“单位换算”全量工具。"},{"q":"温度怎么换算？","a":"选摄氏→华氏或反向即可，自动用公式换算。"}],
};
