/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'quote-convert',
  name: '引号转换',
  desc: '引号转换：中文弯引号与英文直引号互转，排版规范工具。',
  keywords: '引号转换,弯引号,直引号,中文引号,英文引号,排版规范',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入含引号的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="toCurlyQuotes">转弯引号</button><button id="x-run-1" class="btn btn-ghost" data-fn="toStraightQuotes">转直引号</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text3","actions":[{"label":"转弯引号","fn":"toCurlyQuotes"},{"label":"转直引号","fn":"toStraightQuotes"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“转弯引号”：英文双引号转为中文“ ”‘ ’。</li>
  <li>“转直引号”：中文引号还原为英文 " '。</li>
  <li>中文排版规范、代码字符串还原常用。</li>
</ol>`,
  faq: [{"q":"为什么中文排版用弯引号？","a":"国标规定中文文本使用全角弯引号“”，与汉字视觉协调。"},{"q":"转换会误伤代码吗？","a":"会处理所有引号；代码字符串请先分离再转换。"}],
};
