/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'radix-prefix',
  name: '进制前缀速查',
  desc: '编程进制前缀速查：0b/0o/0x 等进制表示法与特殊数值。',
  keywords: '进制前缀,0x,0b,0o,二进制八进制十六进制,编程数值,数字字面量',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"前缀","swatch":false,"mono":true},{"key":1,"label":"进制","swatch":false,"mono":false},{"key":2,"label":"示例","swatch":false,"mono":false}], search: "输入前缀（0x）或进制（二进制）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查编程语言数值字面量前缀。</li><li>搜索支持按前缀或进制过滤。</li><li>写代码、看源码、进制转换参考。</li></ol>`,
  faq: [{"q":"JS 里怎么写大整数？","a":"数字后加 n：12345678901234567890n（BigInt），超出 2⁵³-1 必须用。"},{"q":"数字分隔符是什么？","a":"1_000_000 表示一百万，ES2021 起支持，提升大数可读性。"}],
};
