/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'rail-fence',
  name: '栅栏密码',
  desc: '栅栏密码（Zigzag）加密/解密：按 N 条轨道之字形排列字符后按行读出，经典换位密码。',
  keywords: '栅栏密码,rail fence,之字形密码,换位密码,古典密码,分栏加密',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入明文或密文"></textarea>
</div>
<div class="field"><label for="xp-0">轨道数</label><input type="number" id="xp-0" value="3" min="2"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="railFence">加密</button><button id="x-run-1" class="btn btn-ghost" data-fn="railFenceDecode">解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"加密","fn":"railFence"},{"label":"解密","fn":"railFenceDecode"}],"multi":false,"auto":false,"params":[{"name":"rails","type":"number"}]}</script>`,
  usage: `<ol>
  <li>设置轨道数（2-20，默认 3），输入文本。</li>
  <li>“加密”把字符按之字形写入 N 条轨道后逐行读出；“解密”反向还原。</li>
  <li>轨道数越多，字符被打散得越远。</li>
</ol>`,
  faq: [{"q":"栅栏密码和“栅栏”二字什么关系？","a":"加密时字符像在篱笆的栅栏条之间之字形上下走，因此得名；它是纯换位密码，不改变字符本身。"},{"q":"怎么选择轨道数？","a":"常用 2-5。轨道数增加会加大“打散”效果，但也更易写错；解密时轨道数必须与加密一致。"},{"q":"为什么还原后和原文一样？","a":"换位密码只是重排位置，不改变字符，所以解密（逆向重排）后与原文逐字一致，中文同样支持。"}],
};
