/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'random-time',
  name: '随机时间生成',
  desc: '随机时间生成器：生成 HH:MM:SS 格式随机时间，测试数据常用。',
  keywords: '随机时间,时间生成,测试时间,随机时刻,时间数据',
  category: 'gen',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="5" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">生成 00:00:00-23:59:59 的随机时刻。</div>
<script type="application/json" id="g-cfg">{"lib":"gen2","fn":"randomTime","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>设置数量，点击“生成”。</li>
  <li>输出随机时间（HH:MM:SS）。</li>
  <li>日程系统测试、数据填充常用。</li>
</ol>`,
  faq: [{"q":"时间格式固定吗？","a":"固定 HH:MM:SS 24 小时制，补零对齐。"},{"q":"能生成日期+时间吗？","a":"日期可用“随机日期生成器”，两者可自行拼接。"}],
};
