/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'random-user',
  name: '随机用户信息',
  desc: '随机用户生成：从公共数据库获取真实感测试用户信息（联网获取）。',
  keywords: '随机用户,测试数据,用户信息生成,randomuser,假用户,数据填充',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="toolbar">
  <button id="api-run" class="btn">生成新用户</button>
  <span class="spacer"></span>
  <span class="text-3" style="font-size:13px">数据源：randomuser.me</span>
</div>
<div class="output">
  <div class="output-label">用户信息</div>
  <div id="api-out"></div>
</div>
<div class="note">自动加载随机用户；数据由 randomuser.me 生成（非真实个人），适合测试与演示。</div>
<script type="application/json" id="api-cfg">{"source":"randomuser.me（免费）","provider":"randomuser.me","url":"https://randomuser.me/api/","type":"randomuser"}</script>`,
  usage: `<ol><li>打开自动获取随机用户信息。</li><li>点击"生成新用户"刷新。</li><li>接口联调、表单测试、演示数据填充。</li></ol>`,
  faq: [{"q":"用户是真实的吗？","a":"不是，randomuser.me 生成的虚构数据，可放心用于测试。"},{"q":"能指定国家吗？","a":"当前随机国籍；该 API 支持 nat 参数，后续可加筛选。"}],
};
