/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'random-dog',
  name: '随机狗狗图片',
  desc: '随机狗狗图片：从 Dog CEO 数据库获取随机品种狗狗照片（联网获取）。',
  keywords: '随机狗狗,狗狗图片,宠物图片,dog ceo,柴犬,金毛',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="toolbar">
  <button id="api-run" class="btn">换一只</button>
  <span class="spacer"></span>
  <span class="text-3" style="font-size:13px">数据源：dog.ceo</span>
</div>
<div class="output">
  <div class="output-label">随机狗狗</div>
  <div id="api-out"></div>
</div>
<div class="note">自动加载随机狗狗照片；图片来自 Dog CEO 公开图片库，可下载使用（遵循其许可）。</div>
<script type="application/json" id="api-cfg">{"type":"dog"}</script>`,
  usage: `<ol><li>打开自动获取随机狗狗照片。</li><li>点击"换一只"刷新。</li><li>放松心情、设计素材、演示图片均可。</li></ol>`,
  faq: [{"q":"图片可以商用吗？","a":"dog.ceo 图片来自公开来源（多为 Flickr 免费许可），商用前建议确认单张图片的许可。"},{"q":"能指定品种吗？","a":"当前随机；该 API 支持按品种查询（如 corgi），后续可加品种选择。"}],
};
