/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'random-char',
  name: '随机字符生成',
  desc: '生成随机 ASCII 字符、可打印字符或随机字节序列（十六进制显示）。',
  keywords: '随机字符,随机字符串,随机字节,随机ascii,测试数据生成',
  category: 'text',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="16" min="1"></div><div class="field"><label for="gp-1">类型</label><select id="gp-1"><option value="printable" selected>可打印 ASCII</option><option value="alpha">字母</option><option value="alnum">字母数字</option><option value="hex">十六进制</option><option value="bytes">随机字节(hex)</option></select></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">使用 crypto.getRandomValues 生成，适合测试输入、模糊测试数据。</div>
<script type="application/json" id="g-cfg">{"lib":"misc","fn":"randomChars","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>选择字符类型与数量，点击“生成”。</li>
  <li>可打印 ASCII：33-126；字母/字母数字/十六进制：对应字符集；随机字节输出十六进制。</li>
  <li>生成结果可一键复制，用于测试与调试。</li>
</ol>`,
  faq: [{"q":"随机性可靠吗？","a":"使用浏览器 crypto 加密级随机源，适合一般测试场景。"},{"q":"能生成中文吗？","a":"本工具只生成 ASCII 范围；中文随机内容请用“Lorem 假文”或“假数据生成”。"}],
};
