/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'random-number',
  name: '随机数生成',
  desc: '随机数生成器：指定范围与数量，加密级随机，可重复多次生成。',
  keywords: '随机数生成,随机数,随机数字,随机整数,抽奖数字,加密随机',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">最小值</label>
  <input type="number" id="ci-0" value="1" placeholder="">
</div><div class="field">
  <label for="ci-1">最大值</label>
  <input type="number" id="ci-1" value="100" placeholder="">
</div><div class="field">
  <label for="ci-2">数量（1-100）</label>
  <input type="number" id="ci-2" value="5" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">使用 crypto.getRandomValues 加密级随机源，可含重复值；抽奖去重用“随机抽签”。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"randomNumberCalc","unit":""}</script>`,
  usage: `<ol>
  <li>设置范围（最小-最大）与生成数量，点击“计算”。</li>
  <li>输出 N 个随机整数，每行一个。</li>
  <li>测试数据、随机分组、抽号（允许重复）常用。</li>
</ol>`,
  faq: [{"q":"随机性可靠吗？","a":"基于浏览器 crypto 加密级随机源，优于 Math.random，适合抽奖等场景。"},{"q":"会重复吗？","a":"可能重复（独立抽取）；需要不重复的抽签请用“随机抽签”工具。"}],
};
