/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ratio-calc',
  name: '比例计算器',
  desc: '比例计算：a:b = c:x 求未知项，配方、缩放、汇率折算都能用。',
  keywords: '比例计算,比例求解,等比计算,未知项,a:b=c:d,配方比例',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">a</label>
  <input type="number" id="ci-0" value="2" placeholder="">
</div><div class="field">
  <label for="ci-1">b</label>
  <input type="number" id="ci-1" value="6" placeholder="">
</div><div class="field">
  <label for="ci-2">c</label>
  <input type="number" id="ci-2" value="3" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">解 a:b = c:x，即 x = b × c ÷ a。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"ratioCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入比例 a:b = c:x 中的 a、b、c，点击“计算”。</li>
  <li>工具按 x = b × c ÷ a 求出未知项 x。</li>
  <li>适合配方缩放、图片等比缩放、汇率折算等场景。</li>
</ol>`,
  faq: [{"q":"公式原理是什么？","a":"比例性质：a:b = c:x 等价于 a×x = b×c，所以 x = b×c÷a。"},{"q":"a 或 c 为 0 怎么办？","a":"0 会使比例失去意义，工具会提示；请检查输入。"}],
};
