/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'regex-syntax',
  name: '正则语法速查',
  desc: '正则表达式语法速查：字符类、量词、分组、预查等 30+ 语法。',
  keywords: '正则语法,正则表达式,正则教程,正则元字符,regex语法,正则符号',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"语法","swatch":false,"mono":true},{"key":1,"label":"说明","swatch":false,"mono":false}], search: "输入语法（\\d）或说明（分组）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查正则表达式核心语法。</li><li>搜索支持按语法或说明过滤。</li><li>配合“正则测试”工具实战练习。</li></ol>`,
  faq: [{"q":"贪婪和懒惰匹配？","a":"默认贪婪（尽量多匹配）；量词后加 ? 变懒惰（尽量少匹配）。"},{"q":"预查有什么用？","a":"(?=x) 匹配后跟 x 的位置但不消费字符，用于断言场景。"}],
};
