/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'regex-escape',
  name: '正则转义',
  desc: '正则表达式转义：把特殊字符自动加反斜杠，避免正则语法错误。',
  keywords: '正则转义,正则特殊字符,转义正则,regex escape,特殊字符转义',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入要转义的文本（如 a.b*c）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="regexEscape">转义</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">转义结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev3","actions":[{"label":"转义","fn":"regexEscape"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本，点击“转义”。</li>
  <li>特殊字符（. * + ? [ ] 等）自动加反斜杠。</li>
  <li>把用户输入当作字面量匹配时必用。</li>
</ol>`,
  faq: [{"q":"为什么要转义？","a":"正则中 . * + 等有特殊含义；匹配字面文本不转义会得到错误结果。"},{"q":"转义后能直接用吗？","a":"能，转义结果可直接放入 new RegExp() 或正则字面量。"}],
};
