/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'repeat-text',
  name: '文本重复生成',
  desc: '文本重复生成：指定次数重复文本，测试数据与占位常用。',
  keywords: '重复文本,文本重复,批量复制,重复生成,占位文本,测试文本',
  category: 'text',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">重复次数</label><input type="number" id="gp-0" value="3" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">每行重复一次，适合生成多行测试数据。</div>
<script type="application/json" id="g-cfg">{"lib":"text3","fn":"repeatText","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>填写要重复的内容与次数，点击“生成”。</li>
  <li>输出重复多行的文本。</li>
  <li>测试用例、批量占位、数据填充常用。</li>
</ol>`,
  faq: [{"q":"最大重复次数？","a":"上限 1000 行，防止浏览器卡顿。"},{"q":"内容能带换行吗？","a":"建议单行内容；多行内容会整体重复。"}],
};
