/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'riddle-poem',
  name: '谜语生成器',
  desc: '经典谜语生成器：传统谜语附带谜底，亲子娱乐与文化学习。',
  keywords: '谜语,谜语大全,猜谜语,传统谜语,灯谜,谜底',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="3" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">内置 20 条经典谜语（动物/植物/日用品等）。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomRiddle2","multi":false,"batch":1}</script>`,
  usage: `<ol><li>设置数量，点击“生成”。</li><li>谜面与谜底分行显示。</li><li>元宵灯谜、亲子游戏、语文教学常用。</li></ol>`,
  faq: [{"q":"谜语有分类吗？","a":"暂不分类，随机抽取；内容涵盖动植物与生活物品。"},{"q":"适合孩子吗？","a":"适合，谜底多为常见事物，难度适中。"}],
};
