/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'rot13',
  name: 'ROT13/ROT47 旋转',
  desc: 'ROT13（字母旋转 13 位）与 ROT47（可打印字符旋转 47 位）编解码，用于简单的文本混淆。',
  keywords: 'rot13,rot47,凯撒旋转,字母旋转,文本混淆,rot5',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要旋转的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="rot13">ROT13</button><button id="x-run-1" class="btn btn-ghost" data-fn="rot47">ROT47</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"ROT13","fn":"rot13"},{"label":"ROT47","fn":"rot47"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本，点击 ROT13 旋转字母（a-z/A-Z 各移 13 位），点击 ROT47 旋转全部可打印字符。</li>
  <li>两者都是自逆变换：对结果再执行一次即还原原文。</li>
  <li>ROT13 常用于论坛隐藏剧透；ROT47 可混淆含数字、符号的文本。</li>
</ol>`,
  faq: [{"q":"ROT13 是加密吗？","a":"不是。它只是简单的字母替换，没有密钥，任何人都能还原，只能防“一眼看到”，不能保护任何真实秘密。"},{"q":"ROT5 和 ROT13 什么关系？","a":"ROT5 只旋转数字 0-9，常与 ROT13 组合为 ROT5/13/18 处理数字+字母，用于验证码或简易混淆。"},{"q":"中文会被旋转吗？","a":"ROT13 只处理英文字母；中文、标点原样保留（ROT47 也仅处理 ASCII 可见字符）。"}],
};
