/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'rot5',
  name: 'ROT5/ROT18 旋转',
  desc: 'ROT5（数字旋转 5 位）与 ROT18（字母 ROT13 + 数字 ROT5）编解码。',
  keywords: 'rot5,rot18,数字旋转,验证码混淆,字母数字旋转,文本混淆',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要旋转的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="rot5">ROT5</button><button id="x-run-1" class="btn btn-ghost" data-fn="rot18">ROT18</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"ROT5","fn":"rot5"},{"label":"ROT18","fn":"rot18"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>ROT5：只旋转数字 0-9（各移 5 位）；ROT18：字母 ROT13 + 数字 ROT5。</li>
  <li>两者都是自逆变换，再次执行即还原。</li>
  <li>验证码防 OCR、简单混淆场景常用。</li>
</ol>`,
  faq: [{"q":"ROT18 是 ROT13+ROT5 吗？","a":"是的，ROT18 同时处理字母与数字，一次完成两类旋转。"},{"q":"能防住程序识别吗？","a":"只能防“一眼看穿”，正则即可破解；仅用于低强度混淆。"}],
};
