/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'round-calc',
  name: '数字舍入',
  desc: '数字舍入工具：四舍五入、向上/向下取整、截断到指定小数位。',
  keywords: '数字舍入,四舍五入,向上取整,向下取整,截断小数,round',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数字</label>
  <input type="number" id="ci-0" value="3.14159" placeholder="" step="any">
</div><div class="field">
  <label for="ci-1">小数位</label>
  <input type="number" id="ci-1" value="2" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">同时输出四种舍入方式到指定小数位。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"roundCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入任意数字（可带小数）与目标小数位，点击“计算”。</li>
  <li>对比四舍五入、向上取整、向下取整与直接截断四种结果。</li>
  <li>金额计算、测量数据处理、结果输出规范常用。</li>
</ol>`,
  faq: [{"q":"向上取整和四舍五入什么区别？","a":"向上取整无论下一位多少都进位（3.01→3.1@1位）；四舍五入看下一位是否 ≥5。"},{"q":"负数怎么处理？","a":"按数学定义处理：-3.141 向上取整到 2 位是 -3.14（向正方向），截断是 -3.14。"}],
};
