/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'rps-game',
  name: '石头剪刀布',
  desc: '石头剪刀布：和电脑对战一局，带结果判定。',
  keywords: '石头剪刀布,猜拳,剪刀石头布,rps,猜拳游戏,人机猜拳',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">你的选择</label><select id="gp-0"><option value="石头" selected>石头</option><option value="剪刀">剪刀</option><option value="布">布</option></select></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">石头胜剪刀、剪刀胜布、布胜石头。</div>
<script type="application/json" id="g-cfg">{"lib":"life","fn":"rpsGame","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>选择要出的手势，点击“生成”。</li>
  <li>电脑随机出手并判定胜负。</li>
  <li>谁先赢三局？多来几次！</li>
</ol>`,
  faq: [{"q":"电脑会作弊吗？","a":"不会，使用随机数独立出拳，无记忆。"},{"q":"平局怎么办？","a":"重新出拳即可；平局概率约 1/3。"}],
};
