/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'scenery-image',
  name: '随机风景图',
  desc: '随机风景图片：高山、大海、森林等自然风光，适合壁纸与演示（联网获取）。',
  keywords: '风景图,风景壁纸,自然风光,随机风景,桌面壁纸,风光摄影',
  category: 'web',
  kind: 'api',
  script: 'api-tool',
  
  body: `<div class="toolbar">
  <button id="api-run" class="btn">换一张</button>
  <span class="spacer"></span>
  <span class="text-3" style="font-size:13px">数据源：randompic.pldduck.com</span>
</div>
<div class="output">
  <div class="output-label">随机风景图</div>
  <div id="api-out"></div>
</div>
<div class="note">打开自动加载；图片为高清风光摄影（约 3790×2132）。版权归原作者所有，请勿商用。</div>
<script type="application/json" id="api-cfg">{"type":"randomImage","url":"https://randompic.pldduck.com/fj","alt":"随机风景图"}</script>`,
  usage: `<ol><li>打开页面自动获取随机风景图。</li><li>点击"换一张"刷新。</li><li>可保存为壁纸或用于演示占位。</li></ol>`,
  faq: [{"q":"图片分辨率多少？","a":"约 3790×2132 高清大图，适合 4K 以下屏幕。"},{"q":"可以商用吗？","a":"版权归原作者所有，个人使用为主；商用请自行确认授权。"}],
};
