/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'screen-size',
  name: '屏幕尺寸计算',
  desc: '由对角线尺寸与长宽比计算屏幕宽高与面积，选购显示器时参考。',
  keywords: '屏幕尺寸,显示器尺寸,长宽比,16比9,屏幕宽高,显示器计算',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">对角线（英寸）</label>
  <input type="number" id="ci-0" value="27" placeholder="">
</div><div class="field">
  <label for="ci-1">长宽比（宽）</label>
  <input type="number" id="ci-1" value="16" placeholder="">
</div><div class="field">
  <label for="ci-2">长宽比（高）</label>
  <input type="number" id="ci-2" value="9" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">常见长宽比：16:9、16:10、4:3、21:9。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"screenSizeCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入显示器对角线英寸数与长宽比，点击“计算”。</li>
  <li>输出实际宽、高（英寸）与可视面积。</li>
  <li>比较不同尺寸与比例显示器的大小差异。</li>
</ol>`,
  faq: [{"q":"27 寸 16:9 和 24 寸 16:10 哪个大？","a":"输入两组参数分别计算面积即可对比；同对角线 16:10 高度更大但宽度更小。"},{"q":"宽高怎么算出来的？","a":"由勾股定理：宽 = 对角线 × 比例宽 ÷ √(宽²+高²)，高同理。"}],
};
