/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'shichen',
  name: '十二时辰表',
  desc: '古代十二时辰速查：时辰名称、对应时间与生肖。',
  keywords: '十二时辰,时辰表,子时,古代时间,天干地支时辰',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"时辰","swatch":false,"mono":false},{"key":1,"label":"时间","swatch":false,"mono":true},{"key":2,"label":"生肖","swatch":false,"mono":false},{"key":3,"label":"说明","swatch":false,"mono":false}], search: "输入时辰（子时）或时间（23）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查十二时辰表。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"十","a":"二"},{"q":"子","a":"时"}],
};
