/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'shift-code',
  name: '字符位移加密',
  desc: '字符位移加密：所有字符码点整体位移 N 位，简单文本混淆。',
  keywords: '字符位移,码点位移,简单加密,文本混淆,位移加密,自定义加密',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本"></textarea>
</div>
<div class="field"><label for="xp-0">位移量</label><input type="number" id="xp-0" value="3"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="shiftCode">加密（+N）</button><button id="x-run-1" class="btn btn-ghost" data-fn="unshiftCode">解密（-N）</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text3","actions":[{"label":"加密（+N）","fn":"shiftCode"},{"label":"解密（-N）","fn":"unshiftCode"}],"multi":false,"auto":false,"params":[{"name":"shift","type":"number"}]}</script>`,
  usage: `<ol>
  <li>输入文本与位移量，点击“加密”或“解密”。</li>
  <li>每个字符的 Unicode 码点整体加/减 N。</li>
  <li>简单文本混淆（如防止聊天内容被搜索），非安全加密。</li>
</ol>`,
  faq: [{"q":"安全吗？","a":"不安全，已知位移量可立即还原；仅用于轻度混淆。"},{"q":"支持中文吗？","a":"支持，所有 Unicode 字符均可位移。"}],
};
