/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'shoe-size',
  name: '鞋码换算',
  desc: '鞋码换算器：脚长厘米与欧码、中国码、美码、英码互算，买鞋参考。',
  keywords: '鞋码换算,鞋码对照,脚长换算,欧码美码,买鞋尺码,鞋码查询',
  category: 'convert',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">脚长（cm）</label>
  <input type="number" id="ci-0" value="25" placeholder="" step="0.5">
</div><div class="field"><label for="ci-1">输入方式</label><select id="ci-1"><option value="cm" selected>脚长厘米</option><option value="eu">欧码</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输入脚长自动对照欧码/中国码/美码/英码；不同品牌有偏差。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"shoeSizeCalc","unit":""}</script>`,
  usage: `<ol>
  <li>测量脚长（脚跟到最长脚趾），输入厘米数，点击“计算”。</li>
  <li>一次得到欧码、中国码、男女美码与英码对照。</li>
  <li>海淘买鞋、代购尺码换算必备。</li>
</ol>`,
  faq: [{"q":"怎么量脚长？","a":"赤脚踩纸，标记脚跟与最长脚趾，量两点距离；建议下午量（脚会微胀）。"},{"q":"为什么同一码不同品牌差很多？","a":"鞋楦宽度、版型不同导致实际内长差异，运动鞋/皮鞋/高跟鞋各有偏码。"}],
};
