/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'shuffle-text',
  name: '随机打乱',
  desc: '字符随机打乱 / 单词随机打乱：洗牌式文本变换，趣味与测试用。',
  keywords: '随机打乱,字符打乱,单词打乱,洗牌,shuffle,乱序',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="shuffleChars">打乱字符</button><button id="x-run-1" class="btn btn-ghost" data-fn="shuffleWords">打乱单词</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"打乱字符","fn":"shuffleChars"},{"label":"打乱单词","fn":"shuffleWords"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“打乱字符”：逐字符随机重排（emoji 不拆散）。</li>
  <li>“打乱单词”：按空白分词后随机重排。</li>
  <li>测试数据处理、趣味变换、回文检查辅助常用。</li>
</ol>`,
  faq: [{"q":"结果可预测吗？","a":"不可预测，使用随机数；同一输入每次结果不同。"},{"q":"能还原吗？","a":"不能，打乱不可逆；需要保留原文请先复制。"}],
};
