/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'si-units',
  name: 'SI 国际单位制',
  desc: 'SI 基本单位与导出单位速查：米、千克、秒等 7 个基本单位及常用导出单位定义。',
  keywords: 'si单位,国际单位制,基本单位,导出单位,物理单位,单位定义',
  category: 'ref',
  kind: 'table',
  table: { columns: [{"key":0,"label":"中文名","swatch":false,"mono":false},{"key":1,"label":"符号","swatch":false,"mono":true},{"key":2,"label":"量纲","swatch":false,"mono":false},{"key":3,"label":"定义/换算","swatch":false,"mono":false}], search: "输入单位名（焦耳）、符号（J）或量纲…", dense: false },
  body: ``,
  usage: `<ol>
  <li>表格列出 SI 的 7 个基本单位（米、千克、秒、安培、开尔文、摩尔、坎德拉）与常用导出单位。</li>
  <li>每一行给出单位符号、度量量纲与定义/换算关系。</li>
  <li>适合物理学习、工程计算时快速核对单位定义。</li>
</ol>`,
  faq: [{"q":"基本单位和导出单位有什么区别？","a":"7 个基本单位由国际计量大会定义（如“米”定义为光在真空中 1/299792458 秒内走过的距离），导出单位由基本单位组合而来，如牛顿 = kg·m/s²。"},{"q":"千克还有实物基准吗？","a":"没有了。2019 年起“千克”改为基于普朗克常数定义，不再依赖巴黎的铂铱千克原器，所有 SI 单位都有自然常数基准。"},{"q":"摄氏度和开尔文怎么换算？","a":"摄氏度是开尔文的导出单位：t°C = T(K) - 273.15，即 0°C = 273.15K，二者温差刻度相同。"}],
};
