/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'significant-figures',
  name: '有效数字',
  desc: '按指定位数保留有效数字，科学计算与实验数据处理常用。',
  keywords: '有效数字,有效位数,保留位数,科学计数法保留,精度控制',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">数字</label>
  <input type="number" id="ci-0" value="12345.6789" placeholder="">
</div><div class="field">
  <label for="ci-1">有效位数</label>
  <input type="number" id="ci-1" value="3" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">有效数字从第一个非零数字开始计，如 0.001234 保留 2 位 = 0.0012。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"significantFigures","unit":""}</script>`,
  usage: `<ol>
  <li>输入数字与要保留的有效位数（1-15），点击“计算”。</li>
  <li>输出四舍五入后的数值与科学计数法形式。</li>
  <li>物理、化学实验记录测量结果时规范表达精度。</li>
</ol>`,
  faq: [{"q":"有效数字和保留小数位有什么区别？","a":"有效数字从第一个非零位算起（12345 保留 3 位 = 12300），保留小数位固定在小数点后（12345.679 保留 3 位小数）。两者在不同场景各有用途。"},{"q":"0 开头的小数怎么算？","a":"前导零不算有效数字：0.001234 的有效数字从 1 开始。"}],
};
