/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'sleep-cycle',
  name: '睡眠周期计算',
  desc: '最佳起床时间计算：按 90 分钟睡眠周期推荐起床时间，睡醒更清醒。',
  keywords: '睡眠周期,最佳起床时间,睡眠计算,90分钟周期,入睡时间,起床建议',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">入睡时</label>
  <input type="number" id="ci-0" value="23" placeholder="" min="0">
</div><div class="field">
  <label for="ci-1">入睡分</label>
  <input type="number" id="ci-1" value="0" placeholder="" min="0">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按 4-6 个 90 分钟周期反推，在周期结束（浅睡眠）时起床最清醒。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"sleepCycle","unit":""}</script>`,
  usage: `<ol>
  <li>输入计划入睡时间（时/分），点击“计算”。</li>
  <li>查看 4/5/6 个周期对应的建议起床时间。</li>
  <li>在周期结束时起床，减少“起床气”。</li>
</ol>`,
  faq: [{"q":"90 分钟周期科学吗？","a":"睡眠周期平均约 90 分钟（个体 70-120 分钟），这是常见实用估算；个体差异存在。"},{"q":"能倒推入睡时间吗？","a":"原理相同：确定起床时间后往前数整数个周期入睡。"}],
};
