/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'sleep-need',
  name: '睡眠需求查询',
  desc: '睡眠需求查询：按年龄查看建议睡眠时长（NSF 标准）。',
  keywords: '睡眠时长,睡眠需求,建议睡眠,最佳睡眠时间,睡眠标准,睡多久',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">年龄</label>
  <input type="number" id="ci-0" value="30" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">基于美国国家睡眠基金会（NSF）年龄分层建议。</div>
<script type="application/json" id="c-cfg">{"lib":"dev2","fn":"sleepNeedCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入年龄，点击“计算”。</li>
  <li>查看对应年龄段的建议睡眠时长。</li>
  <li>结合“睡眠周期计算”工具规划入睡/起床时间。</li>
</ol>`,
  faq: [{"q":"睡得越多越好吗？","a":"不是，过长睡眠（>9-10 小时）同样与健康风险相关；规律比时长更重要。"},{"q":"孩子需要多久？","a":"婴幼儿 11-14 小时，学龄前 10-13 小时，青少年 8-10 小时，逐步减少。"}],
};
