/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'solar-terms',
  name: '二十四节气表',
  desc: '二十四节气速查：节气名称、公历日期与含义，传统文化参考。',
  keywords: '二十四节气,节气表,节气查询,节气日期,24节气,农历节气',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"节气","swatch":false,"mono":false},{"key":1,"label":"公历日期","swatch":false,"mono":true},{"key":2,"label":"含义","swatch":false,"mono":false}], search: "输入节气名（立春）或月份过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查二十四节气的公历日期与含义。</li><li>搜索支持按节气名或关键词过滤。</li><li>农事安排、养生参考、传统文化学习常用。</li></ol>`,
  faq: [{"q":"节气日期每年一样吗？","a":"基于太阳黄经计算，公历日期前后浮动 1-2 天；如立春在 2 月 3-5 日。"},{"q":"节气是农历还是公历？","a":"节气按太阳位置确定（黄经），与公历对应稳定，是农历的阳历成分。"}],
};
