/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'soul-soup',
  name: '毒鸡汤生成器',
  desc: '毒鸡汤生成器：扎心又真实的文案，反鸡汤爱好者福利。',
  keywords: '毒鸡汤,反鸡汤,扎心语录,毒文案,丧文化,吐槽语录',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="3" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">内置 20 条经典毒鸡汤，仅供娱乐。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomSoulSoup","multi":false,"batch":1}</script>`,
  usage: `<ol><li>设置数量，点击“生成”。</li><li>输出扎心文案。</li><li>朋友圈吐槽、减压放松、文案灵感常用。</li></ol>`,
  faq: [{"q":"内容消极吗？","a":"以幽默吐槽为主，博君一笑，请勿当真。"},{"q":"可以商用吗？","a":"文案为网络流行语整理，商用请注意原创性。"}],
};
