/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'special-symbols',
  name: '特殊符号大全',
  desc: '特殊符号合集：星形、箭头、几何、数字圈、货币、标点，可复制使用。',
  keywords: '特殊符号,符号大全,符号复制,特殊字符,花纹符号,字体符号',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"符号","swatch":false,"mono":true},{"key":1,"label":"名称","swatch":false,"mono":false}], search: "输入符号（★）或名称（箭头）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>浏览特殊符号分类与写法。</li><li>点击复制按钮直接获取符号。</li><li>昵称装饰、文档排版、海报文案常用。</li></ol>`,
  faq: [{"q":"符号在手机上显示正常吗？","a":"多数 Unicode 符号跨平台显示正常；个别冷门符号可能显示为方框。"},{"q":"带圈数字最大到几？","a":"常用 ①-⑳（U+2460-U+2473）；更大的圈数字需用其他编码。"}],
};
