/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'sql-syntax',
  name: 'SQL 语法速查',
  desc: 'SQL 常用语法速查表：查询、连接、增删改、建表与事务。',
  keywords: 'sql语法,sql速查,sql语句,数据库查询,sql教程,mysql语法',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"语法","swatch":false,"mono":true},{"key":1,"label":"说明","swatch":false,"mono":false}], search: "输入语法（JOIN）或用途（排序）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查 SQL 核心语法：SELECT/JOIN/增删改/建表/事务。</li><li>搜索支持按语法或用途过滤。</li><li>写查询时对照语法格式，注意各数据库方言差异。</li></ol>`,
  faq: [{"q":"各数据库语法通用吗？","a":"核心 SQL 通用；分页（LIMIT/TOP）、自增、日期函数有方言差异，按库查询。"},{"q":"JOIN 类型怎么选？","a":"内连接取交集；LEFT JOIN 保留左表全部；RIGHT/FULL 同理；先用 LEFT 足够覆盖多数场景。"}],
};
