/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'sql-format',
  name: 'SQL 格式化',
  desc: 'SQL 格式化工具：关键字换行缩进，让 SQL 更易读。',
  keywords: 'sql格式化,sql美化,sql排版,sql整理,格式化sql,pretty sql',
  category: 'dev',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴 SQL 语句，如：select * from users where id=1"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="sqlFormat">格式化</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">格式化结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"dev2","actions":[{"label":"格式化","fn":"sqlFormat"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴 SQL 语句，点击“格式化”。</li>
  <li>SELECT/FROM/WHERE/JOIN 等关键字自动换行并缩进。</li>
  <li>适合阅读长查询、代码评审、教学展示。</li>
</ol>`,
  faq: [{"q":"支持哪些数据库？","a":"关键字为 SQL 通用标准，MySQL/PostgreSQL/SQLite 等通用语法均可。"},{"q":"能格式化 INSERT 吗？","a":"能，VALUES 等关键字也会换行；复杂子查询缩进基本正确。"}],
};
