/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'standard-weight',
  name: '标准体重计算',
  desc: '标准体重计算：BMI 健康范围 + Broca/Devine 公式多维度参考。',
  keywords: '标准体重,理想体重,健康体重,bmi范围,体重计算,体重标准',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">身高（cm）</label>
  <input type="number" id="ci-0" value="175" placeholder="">
</div><div class="field"><label for="ci-1">性别</label><select id="ci-1"><option value="male" selected>男</option><option value="female">女</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">健康范围按中国标准 BMI 18.5-23.9 计算。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"standardWeightCalc","unit":""}</script>`,
  usage: `<ol><li>输入身高与性别，点击“计算”。</li><li>得到 BMI 健康体重范围与多种公式参考值。</li><li>健身目标设定、体检对照常用。</li></ol>`,
  faq: [{"q":"为什么不同公式结果不同？","a":"各公式假设不同（骨架、肌肉量），范围比单点更有参考价值。"},{"q":"肌肉多体重超标正常吗？","a":"正常，BMI 不区分肌肉脂肪；结合体脂率综合判断。"}],
};
