/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'stats-calc',
  name: '统计分析计算',
  desc: '统计分析：均值、中位数、众数、方差、标准差、极差一键计算。',
  keywords: '统计分析,平均值,中位数,众数,方差,标准差,数据统计',
  category: 'math',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入数字，空格/逗号/换行分隔，如：1 2 3 4 5"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="statsCalc">统计分析</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">统计结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"math-extra","actions":[{"label":"统计分析","fn":"statsCalc"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴数字列表（空格、逗号或换行分隔），点击“统计分析”。</li>
  <li>输出数量、总和、均值、中位数、众数、极值、方差与标准差。</li>
  <li>成绩统计、测试数据、日常数据分析常用。</li>
</ol>`,
  faq: [{"q":"中位数怎么算？","a":"排序后取中间值：奇数个取正中，偶数个取中间两数平均。"},{"q":"众数有多个怎么办？","a":"并列最高频的数值全部列出，用逗号分隔。"}],
};
