/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'subnet-calc',
  name: '子网计算器',
  desc: '子网计算器（CIDR）：输入 IP 与掩码，算出网络地址、广播地址、可用主机数。',
  keywords: '子网计算,子网掩码,cidr,网络地址,广播地址,ip计算,网段计算',
  category: 'web',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">IP 地址</label><input type="text" id="ci-0" value="192.168.1.5" placeholder=""></div><div class="field">
  <label for="ci-1">前缀（/24）</label>
  <input type="number" id="ci-1" value="24" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">支持输入 CIDR 形式（192.168.1.5/24）或分开填写。</div>
<script type="application/json" id="c-cfg">{"lib":"dev2","fn":"subnetCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入 IP 与子网前缀（0-32），点击“计算”。</li>
  <li>输出网络地址、广播地址、掩码、可用主机数与地址范围。</li>
  <li>网络规划、防火墙规则、VLAN 划分必备。</li>
</ol>`,
  faq: [{"q":"/24 是多少主机？","a":"/24 有 256 个地址，可用 254 个（去掉网络地址与广播地址）。"},{"q":"/31 和 /32 呢？","a":"/31 用于点对点链路（2 地址全可用），/32 是单主机（常用于精确 ACL）。"}],
};
