/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'substitution',
  name: '单表替换密码',
  desc: '单表替换密码：密钥生成替换字母表，古典替换加密/解密。',
  keywords: '单表替换,替换密码,密钥替换,古典密码,字母表替换,cipher',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入明文或密文"></textarea>
</div>
<div class="field"><label for="xp-0">密钥（字母）</label><input type="number" id="xp-0" value="ZEBRA"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="substitutionEncode">加密</button><button id="x-run-1" class="btn btn-ghost" data-fn="substitutionDecode">解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec2","actions":[{"label":"加密","fn":"substitutionEncode"},{"label":"解密","fn":"substitutionDecode"}],"multi":false,"auto":false,"params":[{"name":"key","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写密钥（仅取字母，自动去重并补齐 26 字母表）。</li>
  <li>“加密”按替换表逐字母替换；“解密”反向还原。</li>
  <li>密钥一致才能正确还原。</li>
</ol>`,
  faq: [{"q":"密钥怎么生成替换表？","a":"密钥字母在前（去重），剩余字母按 A-Z 补齐，如密钥 ZEBRA → ZEBRACDFGHIJKLMNOPQSTUVWXY。"},{"q":"安全吗？","a":"单表替换可被频率分析轻松破解（英文文本中 e/t/a 频率特征明显），仅适合教学与谜题。"}],
};
