/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'surnames',
  name: '百家姓速查',
  desc: '百家姓前 100 位速查：常见姓氏与排名，起名参考。',
  keywords: '百家姓,姓氏排名,常见姓氏,姓氏速查,起名参考,中华姓氏',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"姓氏","swatch":false,"mono":false},{"key":1,"label":"排名","swatch":false,"mono":true}], search: "输入姓氏（王）或排名（10）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查百家姓前 100 位。</li><li>搜索支持按姓氏或排名过滤。</li><li>起名、家族文化、数据模拟常用。</li></ol>`,
  faq: [{"q":"百家姓顺序是按人口吗？","a":"《百家姓》成书于北宋，顺序按韵脚与政治地位编排；现代人口排名王、李、张居前。"},{"q":"为什么有些少见姓没收录？","a":"只收录前 100 位常见姓；《百家姓》全本含 504 姓。"}],
};
