/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'tarot',
  name: '塔罗牌占卜',
  desc: '塔罗牌占卜：随机抽取大阿卡纳牌，附牌意解读，娱乐放松。',
  keywords: '塔罗牌,塔罗占卜,大阿卡纳,抽塔罗,塔罗解读,每日塔罗',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">抽牌数量</label><select id="gp-0"><option value="1" selected>单张（每日指引）</option><option value="3">三张（过去-现在-未来）</option><option value="5">五张（十字阵）</option></select></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">22 张大阿卡纳随机抽取，附简要牌意；结果仅供娱乐。</div>
<script type="application/json" id="g-cfg">{"lib":"life","fn":"tarotDraw","multi":false,"batch":1}</script>`,
  usage: `<ol>
  <li>选择抽牌数量（1/3/5 张），点击“生成”。</li>
  <li>默念问题后抽牌，查看牌名与牌意。</li>
  <li>三张牌可对应过去-现在-未来解读。</li>
</ol>`,
  faq: [{"q":"抽牌结果会重复吗？","a":"同一局内不重复（整副牌随机取）；不同局可能抽到相同牌。"},{"q":"结果准确吗？","a":"占卜本质是随机+心理投射，请当作自我反思的工具，理性看待。"}],
};
