/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'temp-quick',
  name: '摄氏度换算',
  desc: '摄氏度与华氏度、开尔文快速换算，温度单位三向对照。',
  keywords: '摄氏度华氏度,温度换算,摄氏转华氏,开尔文,温度转换,℃℉',
  category: 'convert',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">摄氏度（℃）</label>
  <input type="number" id="ci-0" value="100" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">更多温度单位（含华氏/开尔文输入）见“单位换算”工具。</div>
<script type="application/json" id="c-cfg">{"lib":"convert-extra","fn":"tempConvert","unit":""}</script>`,
  usage: `<ol>
  <li>输入摄氏度数值，点击“计算”。</li>
  <li>输出华氏度（F = C×9/5+32）与开尔文（K = C+273.15）。</li>
  <li>烹饪、天气、科学实验场景快速对照。</li>
</ol>`,
  faq: [{"q":"华氏度怎么读？","a":"F = C × 9/5 + 32，如 100°C = 212°F（水的沸点）。"},{"q":"0K 是什么概念？","a":"0K（绝对零度）是理论上最低温度，等于 -273.15°C，此时分子热运动停止。"}],
};
