/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-wrap',
  name: '文本换行/合并',
  desc: '按指定宽度折行、移除换行、按分隔符合并多行，文本排版整理工具。',
  keywords: '文本换行,折行工具,合并行,按分隔符合并,文本整理',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要整理的文本"></textarea>
</div>
<div class="field"><label for="xp-0">折行宽度</label><input type="number" id="xp-0" value="80" min="1"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="wrapLines">按宽度折行</button><button id="x-run-1" class="btn btn-ghost" data-fn="removeLineBreaks">合并为一行</button><button id="x-run-2" class="btn btn-ghost" data-fn="joinLinesComma">逗号合并</button><button id="x-run-3" class="btn btn-ghost" data-fn="joinLinesDun">顿号合并</button><button id="x-run-4" class="btn btn-ghost" data-fn="splitBySpace">按空格拆行</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"按宽度折行","fn":"wrapLines"},{"label":"合并为一行","fn":"removeLineBreaks"},{"label":"逗号合并","fn":"joinLinesComma"},{"label":"顿号合并","fn":"joinLinesDun"},{"label":"按空格拆行","fn":"splitBySpace"}],"multi":false,"auto":false,"params":[{"name":"width","type":"number"}]}</script>`,
  usage: `<ol>
  <li>“按宽度折行”在指定列处截断（默认 80 列）；“合并为一行”删除所有换行。</li>
  <li>“逗号/顿号合并”把每行用符号连接成一行；“按空格拆行”把空格分隔内容转多行。</li>
  <li>适合整理关键词列表、长文本排版。</li>
</ol>`,
  faq: [{"q":"折行会按单词断行吗？","a":"不会，纯按字符宽度截断（硬折行），中英文都一样，适合固定宽度场景。"},{"q":"合并行时行内空格保留吗？","a":"保留。需要同时清理空格可先用“文本处理/统计”里的去空格功能。"},{"q":"逗号合并适合什么场景？","a":"把每行一个的关键词列表转成 CSV 或 SQL IN 子句的逗号串。"}],
};
