/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-reverse',
  name: '文本反转',
  desc: '逐字反转、逐行反转、逐词反转三种方式，趣味与调试兼用。',
  keywords: '文本反转,倒序,字符串反转,文字倒过来,反向文本',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入需要反转的文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="reverseText">逐字反转</button><button id="x-run-1" class="btn btn-ghost" data-fn="reverseLines">逐行反转</button><button id="x-run-2" class="btn btn-ghost" data-fn="reverseWords">逐词反转</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"逐字反转","fn":"reverseText"},{"label":"逐行反转","fn":"reverseLines"},{"label":"逐词反转","fn":"reverseWords"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>逐字反转：abc 变 cba（按 Unicode 码点，emoji 不乱码）；逐行反转：最后一行变第一行；逐词反转：单词顺序倒置。</li>
  <li>适合回文检查、文本游戏与简单数据倒序。</li>
</ol>`,
  faq: [{"q":"emoji 反转会坏吗？","a":"不会。按 Unicode 码点（code point）反转，代理对组成的 emoji 会被整体搬运。"},{"q":"反转后怎么还原？","a":"再执行一次同样的反转即还原。"}],
};
