/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-indent',
  name: '文本缩进/去除',
  desc: '整体添加空格缩进、去除首尾空格、删除全部空白字符。',
  keywords: '文本缩进,加缩进,去除空格,删除空白,缩进工具',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本"></textarea>
</div>
<div class="field"><label for="xp-0">缩进空格数</label><input type="number" id="xp-0" value="2" min="0"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="indentText">加缩进</button><button id="x-run-1" class="btn btn-ghost" data-fn="trimLines">去首尾空格</button><button id="x-run-2" class="btn btn-ghost" data-fn="removeSpaces">删除全部空白</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"加缩进","fn":"indentText"},{"label":"去首尾空格","fn":"trimLines"},{"label":"删除全部空白","fn":"removeSpaces"}],"multi":false,"auto":false,"params":[{"name":"spaces","type":"number"}]}</script>`,
  usage: `<ol>
  <li>“加缩进”给每行行首加 N 个空格（默认 2）；“去首尾空格”去除每行两端空白；“删除全部空白”连中间空格、换行一起去掉。</li>
  <li>适合粘贴代码进 Markdown 代码块、清理复制来的文本格式。</li>
</ol>`,
  faq: [{"q":"删除全部空白会删中文之间的空格吗？","a":"会，包括空格、Tab、换行，全部移除；请确认这是你想要的再操作。"},{"q":"缩进支持 Tab 吗？","a":"当前只加空格；需要 Tab 可把结果里的前导空格替换为 \\t。"}],
};
