/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-replace',
  name: '文本批量替换',
  desc: '文本批量替换：普通替换与正则替换两种模式，一键处理。',
  keywords: '批量替换,文本替换,正则替换,查找替换,replace,字符串替换',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入原文"></textarea>
</div>
<div class="field"><label for="xp-0">查找（正则模式支持语法）</label><input type="number" id="xp-0" value=""></div><div class="field"><label for="xp-1">替换为</label><input type="number" id="xp-1" value=""></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="replaceAll">普通替换</button><button id="x-run-1" class="btn btn-ghost" data-fn="replaceRegex">正则替换</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">替换结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"普通替换","fn":"replaceAll"},{"label":"正则替换","fn":"replaceRegex"}],"multi":false,"auto":false,"params":[{"name":"find","type":"text"},{"name":"replace","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写“查找”与“替换为”文本，选择替换模式。</li>
  <li>普通替换：全部替换（区分大小写）；正则替换：支持 \\d、[a-z] 等。</li>
  <li>批量清洗数据、统一格式常用。</li>
</ol>`,
  faq: [{"q":"正则怎么替换？","a":"用 JavaScript 正则语法，如 \\d+ 匹配数字；替换串支持 $1 引用分组。"},{"q":"替换所有还是第一个？","a":"全部替换；需要只替换第一个请用正则的取消 g 模式（暂不支持）。"}],
};
