/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-lines',
  name: '文本行处理',
  desc: '文本行操作工具：去重、排序、反转、加行号、去空行、去除首尾空格一键完成。',
  keywords: '文本行处理,行去重,行排序,加行号,去空行,行操作工具',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="每行一条内容"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="dedupeLines">去重</button><button id="x-run-1" class="btn btn-ghost" data-fn="dedupeSortLines">去重+排序</button><button id="x-run-2" class="btn btn-ghost" data-fn="sortLines">排序（升）</button><button id="x-run-3" class="btn btn-ghost" data-fn="sortLinesDesc">排序（降）</button><button id="x-run-4" class="btn btn-ghost" data-fn="reverseLines">行反转</button><button id="x-run-5" class="btn btn-ghost" data-fn="stripEmptyLines">去空行</button><button id="x-run-6" class="btn btn-ghost" data-fn="trimLines">每行去空格</button><button id="x-run-7" class="btn btn-ghost" data-fn="shuffleLines">随机打乱</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">处理结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"去重","fn":"dedupeLines"},{"label":"去重+排序","fn":"dedupeSortLines"},{"label":"排序（升）","fn":"sortLines"},{"label":"排序（降）","fn":"sortLinesDesc"},{"label":"行反转","fn":"reverseLines"},{"label":"去空行","fn":"stripEmptyLines"},{"label":"每行去空格","fn":"trimLines"},{"label":"随机打乱","fn":"shuffleLines"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴文本（每行一条），选择要执行的操作。</li>
  <li>去重保留首次出现顺序；排序支持升/降序；随机打乱适合抽选分组。</li>
  <li>处理结果可直接复制使用。</li>
</ol>`,
  faq: [{"q":"去重是精确匹配吗？","a":"是的，按整行精确去重（含空格差异），去重前可先执行“每行去空格”统一格式。"},{"q":"空行算一行吗？","a":"“去空行”会删除空白行；其他操作保留空行不删，避免改变行号语义。"},{"q":"能处理多大文本？","a":"几十 MB 文本在浏览器本地处理无压力，结果一次性渲染。"}],
};
