/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-bytes',
  name: '文本字节查看',
  desc: '文本字节查看：UTF-8 字节序列与文本信息统计（字符/字节/行数）。',
  keywords: '字节查看,utf8字节,字节序列,文本信息,字符统计,字节统计',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="textToBytes">查看字节</button><button id="x-run-1" class="btn btn-ghost" data-fn="textLengthInfo">文本信息</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"查看字节","fn":"textToBytes"},{"label":"文本信息","fn":"textLengthInfo"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“查看字节”：每个 UTF-8 字节输出十进制值，空格分隔。</li>
  <li>“文本信息”：字符数、字节数、行数、汉字数、英文单词数。</li>
  <li>调试编码、估算存储、内容统计常用。</li>
</ol>`,
  faq: [{"q":"字节和字符什么区别？","a":"一个汉字 UTF-8 占 3 字节但只算 1 字符；emoji 占 4 字节。"},{"q":"字节数能转十六进制吗？","a":"需要十六进制请用“文本十六进制互转”工具。"}],
};
