/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-hex',
  name: '文本十六进制互转',
  desc: '文本与十六进制互转：UTF-8 字节流与 Hex 字符串双向转换，调试利器。',
  keywords: '文本转十六进制,hex转文本,hex编码,十六进制查看,utf8 hex',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或十六进制串（如 48656c6c6f）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="textToHex">文本→Hex</button><button id="x-run-1" class="btn btn-ghost" data-fn="hexToText">Hex→文本</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"文本→Hex","fn":"textToHex"},{"label":"Hex→文本","fn":"hexToText"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“文本→Hex”：按 UTF-8 输出每个字节的两位十六进制。</li>
  <li>“Hex→文本”：粘贴十六进制（可含空格、0x 前缀、大写小写均可）还原。</li>
  <li>调试协议报文、查看文件魔数、核对字节序列都常用。</li>
</ol>`,
  faq: [{"q":"怎么去掉 0x 前缀？","a":"解码时自动忽略 0x、空格与换行，直接粘贴即可。"},{"q":"奇数个十六进制字符怎么办？","a":"本工具要求成对字节（偶数长度），奇数会提示错误；一个字节由两位十六进制表示。"},{"q":"和 Unicode 码点有什么区别？","a":"本工具展示的是 UTF-8 编码字节；Unicode 码点是字符编号（如 U+4F60），需要码点请用“ASCII 与字符互转”工具。"}],
};
