/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'text-binary',
  name: '文本二进制互转',
  desc: '文本与二进制（0/1）互转：每个 UTF-8 字节转 8 位二进制，支持中文。',
  keywords: '文本转二进制,二进制转文本,文本转01,二进制编码,机器码查看',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或二进制串（每字节 8 位）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="textToBinary">文本→二进制</button><button id="x-run-1" class="btn btn-ghost" data-fn="binaryToText">二进制→文本</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"文本→二进制","fn":"textToBinary"},{"label":"二进制→文本","fn":"binaryToText"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“文本→二进制”：按 UTF-8 把每个字节输出 8 位 0/1，空格分隔。</li>
  <li>“二进制→文本”：粘贴 8 位一组（可含空格）还原为文本。</li>
  <li>适合计算机基础教学、理解字符在内存中的表示。</li>
</ol>`,
  faq: [{"q":"为什么一个中文要 24 位？","a":"UTF-8 编码下汉字占 3 字节 = 24 位，这是 Unicode 标准规定的，emoji 甚至占 4 字节（32 位）。"},{"q":"二进制串能带空格吗？","a":"可以，解码时自动忽略空格与换行；建议每 8 位一组便于阅读。"},{"q":"和 ASCII 表什么关系？","a":"英文字符的二进制与 ASCII 表一致（如 A=01000001）；本工具按 UTF-8 处理，中文也能正确转换。"}],
};
