/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'time-units',
  name: '时间单位换算速查',
  desc: '时间单位速查：秒分时天周月年的换算关系对照表。',
  keywords: '时间单位,时间换算,时分秒,天周月年,时间单位速查,单位换算',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"单位","swatch":false,"mono":true},{"key":1,"label":"换算","swatch":false,"mono":false},{"key":2,"label":"符号","swatch":false,"mono":false}], search: "输入单位（年）或符号（h）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查时间单位换算关系。</li><li>搜索支持按单位或符号过滤。</li><li>时长换算、排期、开发时间戳处理参考。</li></ol>`,
  faq: [{"q":"一个月是多少天？","a":"平均 30.44 天（365.25/12）；具体月 28-31 天不等，精确计算按日历。"},{"q":"光年是时间单位吗？","a":"不是，光年是距离单位（光走一年的距离）；表格列出仅供参考。"}],
};
