/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'time-diff',
  name: '时间差计算',
  desc: '时间差计算：指定时间与当前时间的差值（未来/过去）。',
  keywords: '时间差,当前时间对比,倒计时计算,时间距离,还剩多久',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">目标时间</label><input type="datetime-local" id="ci-0" value=""></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">选择日期时间，计算与现在的差值。</div>
<script type="application/json" id="c-cfg">{"lib":"dev4","fn":"timeDiffCalc","unit":""}</script>`,
  usage: `<ol><li>选择目标日期时间，点击“计算”。</li><li>输出方向（未来/过去）与天时分秒差值。</li><li>活动倒计时、任务截止提醒常用。</li></ol>`,
  faq: [{"q":"支持秒级吗？","a":"支持，datetime-local 精度到分钟；秒级差异也会显示。"},{"q":"和日期差工具区别？","a":"本工具对比“当前时刻”，日期差对比两个指定日期。"}],
};
