/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'time-format',
  name: '毫秒时长格式化',
  desc: '毫秒转天时分秒：时长格式化工具，性能分析常用。',
  keywords: '毫秒转换,时长格式化,天时分秒,毫秒转秒,时间格式,耗时分析',
  category: 'dev',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">毫秒数</label>
  <input type="number" id="ci-0" value="86461000" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出天时分秒、总秒数、总分钟等多种表示。</div>
<script type="application/json" id="c-cfg">{"lib":"dev3","fn":"timeFormat","unit":""}</script>`,
  usage: `<ol>
  <li>输入毫秒数（如接口耗时、视频时长），点击“计算”。</li>
  <li>输出天/时/分/秒与总秒数、总分钟。</li>
  <li>日志耗时分析、倒计时设计、数据展示常用。</li>
</ol>`,
  faq: [{"q":"86461000ms 是多少？","a":"1 天 0 时 1 分 1 秒（86461000 = 24×3600×1000 + 61000）。"},{"q":"支持负数吗？","a":"不支持，请输入非负毫秒数。"}],
};
