/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'tlds',
  name: '顶级域名速查',
  desc: '常见顶级域名速查表：.com/.cn/.io 等 34 个通用与国别顶级域。',
  keywords: '顶级域名,tld,域名后缀,.com,.cn,域名大全',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"后缀","swatch":false,"mono":true},{"key":1,"label":"含义","swatch":false,"mono":false},{"key":2,"label":"说明","swatch":false,"mono":false}], search: "输入后缀（.io）或含义（中国）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查顶级域名。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"顶","a":"级"},{"q":".","a":"i"}],
};
