/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'tongue-twister',
  name: '绕口令生成器',
  desc: '绕口令生成器：经典中文绕口令，口才与发音练习。',
  keywords: '绕口令,绕口令大全,口才练习,发音练习,普通话练习',
  category: 'life',
  kind: 'gen',
  
  
  body: `<div class="row">
<div class="field"><label for="gp-0">数量</label><input type="number" id="gp-0" value="1" min="1"></div>
</div>
<div class="toolbar">
  <button id="g-run" class="btn">生成</button>
  <span class="spacer"></span>
  <button data-copy-from="#g-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">生成结果</div>
  <pre id="g-out">点击按钮生成</pre>
</div>
<div class="note">内置 12 条经典绕口令（四十四、化肥、扁担等）。</div>
<script type="application/json" id="g-cfg">{"lib":"gen3","fn":"randomTongueTwister","multi":false,"batch":1}</script>`,
  usage: `<ol><li>设置数量，点击“生成”。</li><li>大声朗读练习发音与语速。</li><li>播音主持练习、亲子互动、课堂游戏常用。</li></ol>`,
  faq: [{"q":"有难度分级吗？","a":"暂不分级；从“四是四”入门到“化肥”进阶。"},{"q":"能随机换吗？","a":"重新点击生成即可换一条。"}],
};
