/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'trig-calc',
  name: '三角函数计算',
  desc: '三角函数：sin/cos/tan 与弧度换算，角度制输入。',
  keywords: '三角函数,sin,cos,tan,角度弧度,三角计算,正弦余弦',
  category: 'math',
  kind: 'calc',
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">角度（度）</label>
  <input type="number" id="ci-0" value="30" placeholder="" step="any">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">30° 的 sin=0.5、cos≈0.866、tan≈0.577，弧度 π/6。</div>
<script type="application/json" id="c-cfg">{"lib":"math-extra","fn":"trigCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入角度（度），点击“计算”。</li>
  <li>输出 sin、cos、tan 值与对应弧度。</li>
  <li>几何计算、信号处理、物理力学分解常用。</li>
</ol>`,
  faq: [{"q":"tan(90°) 为什么显示—？","a":"90° 的余弦为 0，tan = sin/cos 分母为 0 无定义，属数学正常现象。"},{"q":"支持弧度输入吗？","a":"当前按角度输入；需要弧度可先用“角度换算”工具转成度。"}],
};
