/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'ua-list',
  name: 'User-Agent 列表',
  desc: '常见浏览器与爬虫 User-Agent 速查：Chrome、Edge、百度、Googlebot 等可直接复制。',
  keywords: 'user-agent,ua列表,ua大全,浏览器ua,爬虫ua,ua复制',
  category: 'ref',
  kind: 'table',
  table: { columns: [{"key":0,"label":"名称","swatch":false,"mono":false},{"key":1,"label":"User-Agent","swatch":false,"mono":true}], search: "输入浏览器名（Chrome）或设备（iPhone）过滤…", dense: false },
  body: ``,
  usage: `<ol>
<li>表格列出常用浏览器与爬虫的 User-Agent 字符串。</li>
<li>点击复制按钮直接获取完整 UA。</li>
<li>开发爬虫伪装、测试 UA 识别、配置反爬规则时常用。</li>
</ol>`,
  faq: [{"q":"UA 可以伪造吗？","a":"可以。UA 是客户端自报信息，服务端只能“信任”它；分析时需结合 IP、行为等综合判断。"},{"q":"为什么同一浏览器 UA 不一样？","a":"UA 含操作系统、内核版本、设备型号，不同环境自然不同；表格提供常见版本示例。"}],
};
