/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'unicode-blocks',
  name: 'Unicode 区块速查',
  desc: 'Unicode 区块大全：常用语系、符号、CJK 汉字、emoji 的码点范围速查表。',
  keywords: 'unicode区块,unicode编码范围,码点区间,cjk汉字范围,emoji编码,字符范围表',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"码点范围","swatch":false,"mono":true},{"key":1,"label":"英文名","swatch":false,"mono":false},{"key":2,"label":"中文说明","swatch":false,"mono":false}], search: "输入区块名、汉字范围或关键词…", dense: true },
  body: ``,
  usage: `<ol>
  <li>表格列出主要 Unicode 区块的码点范围（十六进制）与说明。</li>
  <li>按语系（如 CJK、希腊、西里尔）或符号类别（箭头、数学运算符、emoji）快速定位。</li>
  <li>开发正则表达式时可用范围判断字符类别，如中文常用 \\u4e00-\\u9fff。</li>
</ol>`,
  faq: [{"q":"中文汉字在哪个区间？","a":"常用汉字在 CJK 统一表意文字区 U+4E00-U+9FFF（约 2 万汉字），扩展 A 区在 U+3400-U+4DBF（生僻字）。"},{"q":"emoji 是哪个区块？","a":"emoji 分散在多个区块：U+1F300-U+1F5FF 杂项符号、U+1F600-U+1F64F 表情、U+1F680-U+1F6FF 交通符号等，还有大量来自其他区块的组合。"},{"q":"私用区（PUA）是什么？","a":"U+E000-U+F8FF 是私用区，供字体厂商和应用程序自行定义字符，没有统一标准含义，普通文本应避免使用。"}],
};
