/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'unicode-escape',
  name: 'Unicode 转义/反转义',
  desc: 'Unicode 转义转换：文本转 \\uXXXX 转义序列，反向还原。',
  keywords: 'unicode转义,转义序列,\\u编码,json转义,反转义,编码转换',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文本或 \\u 转义序列"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="unicodeEscape">转义</button><button id="x-run-1" class="btn btn-ghost" data-fn="unicodeUnescape">反转义</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"转义","fn":"unicodeEscape"},{"label":"反转义","fn":"unicodeUnescape"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>“转义”：中文/特殊字符转为 \\uXXXX 形式。</li>
  <li>“反转义”：粘贴 \\u4F60 等序列还原为文本。</li>
  <li>JSON 字符串、日志调试、代码硬编码常用。</li>
</ol>`,
  faq: [{"q":"JSON 里能用吗？","a":"能，JSON 字符串支持 \\uXXXX；本工具转义结果可直接放入 JSON。"},{"q":"支持 \\u{...} 扩展格式吗？","a":"支持（ES6 语法），大于 BMP 的字符用 \\u{1F600} 形式。"}],
};
