/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'unique-words',
  name: '单词去重',
  desc: '英文单词去重与词频统计：按空格分词去重或统计 Top N 高频词。',
  keywords: '单词去重,词频统计,高频词,英文分词,去重工具,top词',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入英文文本"></textarea>
</div>
<div class="field"><label for="xp-0">Top N</label><input type="number" id="xp-0" value="20" min="1"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="uniqueWords">单词去重</button><button id="x-run-1" class="btn btn-ghost" data-fn="wordFrequencyTop">词频 Top N</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text2","actions":[{"label":"单词去重","fn":"uniqueWords"},{"label":"词频 Top N","fn":"wordFrequencyTop"}],"multi":true,"auto":false,"params":[{"name":"count","type":"number"}]}</script>`,
  usage: `<ol>
  <li>“单词去重”：按空白分词去重，每词一行。</li>
  <li>“词频 Top N”：统计出现最多的 N 个单词及次数。</li>
  <li>文章关键词分析、停止词过滤、词云准备常用。</li>
</ol>`,
  faq: [{"q":"大小写会合并吗？","a":"词频统计统一转小写合并；去重保留原样（区分大小写）。"},{"q":"标点会处理吗？","a":"词频统计只匹配字母数字，标点自动忽略；去重按空白切分含标点。"}],
};
