/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'url-extract',
  name: 'URL 提取',
  desc: '从文本中提取全部网址链接，去重后逐行列出，爬虫与文本分析常用。',
  keywords: '提取网址,url提取,链接提取,提取链接,url抓取,网址筛选',
  category: 'text',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴含链接的文本（日志、HTML、聊天记录…）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="extractUrls">提取 URL</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">提取结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"提取 URL","fn":"extractUrls"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴任意文本，点击“提取 URL”，自动找出所有 http/https 链接。</li>
  <li>结果逐行列出，复制后去重排序可用“文本行处理”工具。</li>
  <li>适合从日志、爬虫页面中批量收集网址。</li>
</ol>`,
  faq: [{"q":"能提取相对路径吗？","a":"只能提取完整 http/https 链接；相对路径没有协议头无法识别。"},{"q":"链接带中文或特殊字符怎么办？","a":"按空白与尖括号边界截取，中文链接会保留；被截断的链接建议手工补全。"},{"q":"结果会去重吗？","a":"按出现顺序原样列出（不去重）；需要去重用“文本行处理”。"}],
};
