/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'url-params',
  name: 'URL 参数解析',
  desc: 'URL 查询参数解析：自动解码 URL 编码，输出参数名与值列表。',
  keywords: 'url参数,查询参数解析,query参数,参数提取,url解码,query string',
  category: 'web',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="粘贴带 ? 的 URL，如：https://x.com/path?a=1&b=hello%20world"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="urlParams">解析</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">参数列表</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"web","actions":[{"label":"解析","fn":"urlParams"}],"multi":true,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>粘贴完整 URL，点击“解析”。</li>
  <li>提取 ? 后全部参数，自动解码 %20、+ 等转义。</li>
  <li>调试跳转链接、分析埋点参数、构造接口请求常用。</li>
</ol>`,
  faq: [{"q":"没有参数会怎样？","a":"提示“URL 中没有查询参数”；带 #hash 的部分会忽略。"},{"q":"重复参数名怎么办？","a":"逐个列出（同名多条），不合并；需要合并可自行处理结果。"}],
};
