/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'vector-calc',
  name: '向量计算器',
  desc: '二维向量计算：模长、点积、夹角、加减法一键计算。',
  keywords: '向量计算,向量模长,点积,向量夹角,向量加减,数学向量',
  category: 'math',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">向量 a 的 x</label>
  <input type="number" id="ci-0" value="3" placeholder="">
</div><div class="field">
  <label for="ci-1">向量 a 的 y</label>
  <input type="number" id="ci-1" value="4" placeholder="">
</div><div class="field">
  <label for="ci-2">向量 b 的 x</label>
  <input type="number" id="ci-2" value="1" placeholder="">
</div><div class="field">
  <label for="ci-3">向量 b 的 y</label>
  <input type="number" id="ci-3" value="0" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出两向量的模长、点积、夹角与加减结果。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"vectorCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入两个二维向量的 x、y 分量，点击“计算”。</li>
  <li>得到模长、点积、夹角（度）与 a±b。</li>
  <li>物理力学分解、计算机图形学、数学学习常用。</li>
</ol>`,
  faq: [{"q":"夹角公式是什么？","a":"cosθ = (a·b) / (|a|×|b|)，θ 为两向量夹角（0-180°）。"},{"q":"点积为 0 说明什么？","a":"两向量垂直（正交），这是判断垂直的常用方法。"}],
};
