/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'version-compare',
  name: '版本号比较',
  desc: '版本号比较：比较两个 semver 版本号大小（如 1.2.3 vs 1.10.0）。',
  keywords: '版本比较,版本号,版本对比,semver,版本大小,版本判断',
  category: 'dev',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">版本 A</label><input type="text" id="ci-0" value="1.2.3" placeholder=""></div><div class="field"><label for="ci-1">版本 B</label><input type="text" id="ci-1" value="1.10.0" placeholder=""></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按主版本.次版本.修订号逐段比较，支持 v 前缀。</div>
<script type="application/json" id="c-cfg">{"lib":"convert3","fn":"versionCompare","unit":""}</script>`,
  usage: `<ol>
  <li>输入两个版本号（支持 v 前缀与多段数字），点击“计算”。</li>
  <li>输出 A > B / A < B / A = B。</li>
  <li>判断依赖版本、升级检查、接口兼容性常用。</li>
</ol>`,
  faq: [{"q":"1.10.0 比 1.2.0 大吗？","a":"大。按段比较：1=1，然后 10>2，所以 1.10.0 > 1.2.0。"},{"q":"支持预发布后缀吗？","a":"暂不支持 -alpha/-beta 后缀，只比较数字段。"}],
};
