/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'vertical-text',
  name: '竖排文字',
  desc: '文本竖排转换：逐字换行生成竖排效果，海报、横幅排版常用。',
  keywords: '竖排文字,竖排转换,文字竖排,竖排生成,纵向文字',
  category: 'text',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入文字（每行视为一列）"></textarea>
</div>

<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="verticalText">竖排</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">竖排结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"text","actions":[{"label":"竖排","fn":"verticalText"}],"multi":false,"auto":false,"params":[]}</script>`,
  usage: `<ol>
  <li>输入文本（多行时每行成为一列），点击“竖排”。</li>
  <li>输出逐字换行的纵向文本，适合生成竖排海报文案的底稿。</li>
</ol>`,
  faq: [{"q":"多行输入怎么处理？","a":"每一行独立竖排，行与行之间以空行分隔，形成多列效果。"},{"q":"标点符号会竖排吗？","a":"会逐字竖排；中文标点按常规竖排习惯保留在字后。"}],
};
