/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'vigenere',
  name: '维吉尼亚密码',
  desc: '维吉尼亚密码加密/解密：用密钥重复扩展对字母位移，古典多表替换密码。',
  keywords: '维吉尼亚,维吉尼亚密码,vigenere,多表替换,古典密码,密钥加密',
  category: 'codec',
  kind: 'transform',
  
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入明文或密文"></textarea>
</div>
<div class="field"><label for="xp-0">密钥（字母）</label><input type="text" id="xp-0" value="key"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="vigenere">加密</button><button id="x-run-1" class="btn btn-ghost" data-fn="vigenereDecode">解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"加密","fn":"vigenere"},{"label":"解密","fn":"vigenereDecode"}],"multi":false,"auto":false,"params":[{"name":"key","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写密钥（仅取字母，如 secret），输入文本。</li>
  <li>点击“加密”逐字母位移得到密文；粘贴密文点击“解密”还原。</li>
  <li>密钥越长、越随机，破译难度越高；短密钥可用频率分析破解。</li>
</ol>`,
  faq: [{"q":"和凯撒密码有什么区别？","a":"凯撒对所有字母用同一个位移量；维吉尼亚按密钥字母逐位变化位移量（A=0、B=1…），相同字母在不同位置加密结果可能不同。"},{"q":"为什么解密结果偶尔不对？","a":"本工具只处理英文字母且密钥只取字母，中文与符号原样保留；请确认密钥一致且未混入非字母字符。"},{"q":"维吉尼亚密码安全吗？","a":"历史上曾被认为不可破，但 1863 年卡西斯基测试可破解；现代标准至少要求密钥长于明文且完全随机。"}],
};
