/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'waist-hip',
  name: '腰臀比计算',
  desc: '腰臀比（WHR）计算：腰围÷臀围，评估中心性肥胖风险。',
  keywords: '腰臀比,whr,腰围臀围,健康指标,肥胖风险,身材比例',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">腰围（cm）</label>
  <input type="number" id="ci-0" value="80" placeholder="">
</div><div class="field">
  <label for="ci-1">臀围（cm）</label>
  <input type="number" id="ci-1" value="100" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">WHO 标准：男 <0.9、女 <0.85 为低风险。</div>
<script type="application/json" id="c-cfg">{"lib":"dev2","fn":"waistHipCalc","unit":""}</script>`,
  usage: `<ol>
  <li>测量腰围（肚脐水平）与臀围（最宽处），输入并计算。</li>
  <li>得到腰臀比与风险分级。</li>
  <li>腰臀比高（苹果型身材）与心血管风险相关。</li>
</ol>`,
  faq: [{"q":"腰臀比和 BMI 什么关系？","a":"BMI 看整体胖瘦，腰臀比看脂肪分布；两者结合评估更全面。"},{"q":"怎么测腰围？","a":"自然站立、呼气末，绕肚脐水平一周测量；不要吸气收腹。"}],
};
