/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'water-intake',
  name: '每日饮水计算',
  desc: '每日饮水量计算：按体重估算建议饮水量，健康习惯养成。',
  keywords: '饮水量,喝水计算,每天喝多少水,健康饮水,补水计算,喝水提醒',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">体重（kg）</label>
  <input type="number" id="ci-0" value="60" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">公式：体重 × 30ml（温和运动者）；运动、高温天气需增加。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"waterIntake","unit":""}</script>`,
  usage: `<ol>
  <li>输入体重，点击“计算”。</li>
  <li>得到每日建议饮水量（毫升与杯数）。</li>
  <li>少量多次饮用，不要等口渴才喝。</li>
</ol>`,
  faq: [{"q":"喝多了有害吗？","a":"短时大量饮水可能水中毒（低钠血症），每天 2-3L 对健康成人安全；肾病等患者遵医嘱。"},{"q":"茶水咖啡算水吗？","a":"算，但含咖啡因有利尿作用；白开水仍是最佳选择。"}],
};
