/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'weather-symbols',
  name: '天气符号速查',
  desc: '天气符号大全：晴、雨、雪、雷等 20 个符号可复制。',
  keywords: '天气符号,天气图标,天气预报符号,天气表情,天气大全',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"符号","swatch":false,"mono":false},{"key":1,"label":"含义","swatch":false,"mono":false}], search: "输入符号（☀️）或含义（雨）过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查天气符号。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"天","a":"气"},{"q":"符","a":"号"}],
};
