/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'weekday-calc',
  name: '日期星期查询',
  desc: '日期星期查询：输入日期得星期、年中第几天、第几周。',
  keywords: '星期查询,日期星期,第几周,年中第几天,星期几,日历计算',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">日期</label><input type="date" id="ci-0" value="2026-09-05"></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">输出星期、一年中第几天、第几周与闰年信息。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"weekdayCalc","unit":""}</script>`,
  usage: `<ol><li>选择日期，点击“计算”。</li><li>得到星期、年中天数、周数与闰年判断。</li><li>排期规划、纪念日查询、日期分析常用。</li></ol>`,
  faq: [{"q":"和日期计算器重复吗？","a":"本工具聚焦“星期/周数”信息；日期差与加减用“日期计算器”。"},{"q":"周数按什么标准？","a":"按自然周（第 N 周 = 天数÷7 向上取整），非 ISO 周。"}],
};
