/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'workdays',
  name: '工作日计算',
  desc: '两个日期之间的工作日与周末天数统计，排期规划常用。',
  keywords: '工作日计算,工作日天数,周末计算,上班天数,工时统计,自然日',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">起始日期</label><input type="date" id="ci-0" value="2024-08-01"></div><div class="field"><label for="ci-1">结束日期</label><input type="date" id="ci-1" value="2024-08-31"></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按周一至周五为工作日计算；法定调休日不在计算范围。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"workdaysCalc","unit":""}</script>`,
  usage: `<ol>
  <li>选择起止日期，点击“计算”。</li>
  <li>输出自然日、工作日（周一~五）、周末天数与周数。</li>
  <li>项目排期、请假统计、交付工期估算常用。</li>
</ol>`,
  faq: [{"q":"包含法定节假日调休吗？","a":"不含。本工具按固定“周一~五 = 工作日”计算，法定调休（如国庆补班）需自行增减。"},{"q":"起止日期顺序有要求吗？","a":"没有，自动取前小后大计算，输出为正数。"}],
};
