/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'xor',
  name: 'XOR 异或加密',
  desc: 'XOR 异或加密/解密：用密钥对字节流逐位异或，输出 Base64，同一操作可加密与解密。',
  keywords: 'xor加密,异或加密,异或解密,对称加密,简单加密,xor cipher',
  category: 'codec',
  kind: 'transform',
  
  body: `<div class="field">
  <label for="x-in">输入</label>
  <textarea id="x-in" class="mono" rows="6" placeholder="输入明文或 Base64 密文"></textarea>
</div>
<div class="field"><label for="xp-0">密钥</label><input type="number" id="xp-0" value="secret"></div>
<div class="toolbar">
  <button id="x-run-0" class="btn" data-fn="xorEncrypt">加密</button><button id="x-run-1" class="btn btn-ghost" data-fn="xorDecrypt">解密</button>
  <span class="spacer"></span>
  <button data-copy-from="#x-out" class="btn btn-ghost btn-sm">复制结果</button>
  <button id="x-clear" class="btn btn-ghost btn-sm">清空</button>
</div>
<div class="output">
  <div class="output-label" id="x-label">结果</div>
  <div id="x-out-wrap"><pre id="x-out">等待输入…</pre></div>
</div>

<script type="application/json" id="x-cfg">{"lib":"codec","actions":[{"label":"加密","fn":"xorEncrypt"},{"label":"解密","fn":"xorDecrypt"}],"multi":false,"auto":false,"params":[{"name":"key","type":"text"}]}</script>`,
  usage: `<ol>
  <li>填写密钥，输入文本。</li>
  <li>“加密”把文本按 UTF-8 转字节后与密钥循环异或，输出 Base64；“解密”需使用相同密钥。</li>
  <li>XOR 是对称操作：同一密钥再执行一次即还原。</li>
</ol>`,
  faq: [{"q":"XOR 加密安全吗？","a":"不安全。短密钥 XOR 可用频率分析/已知明文破解；若密钥长于数据且完全随机（一次性密码本）才是信息论安全的。XOR 常用于简单的数据混淆。"},{"q":"密钥可以含中文吗？","a":"可以。密钥与数据都按 UTF-8 转字节后逐字节异或，中文密钥同样生效。"},{"q":"密文为什么是 Base64？","a":"异或后的字节可能不是可打印字符，用 Base64 表示便于复制存储，同时兼容本工具的文本输入框。"}],
};
