/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'zodiac',
  name: '星座查询',
  desc: '星座查询：输入月日即得星座，附日期范围对照。',
  keywords: '星座查询,星座,星座表,生日星座,十二星座,星座日期',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">月份</label>
  <input type="number" id="ci-0" value="8" placeholder="" min="1">
</div><div class="field">
  <label for="ci-1">日期</label>
  <input type="number" id="ci-1" value="20" placeholder="" min="1">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按公历（阳历）生日计算星座，非农历。</div>
<script type="application/json" id="c-cfg">{"lib":"date","fn":"zodiacCalc","unit":""}</script>`,
  usage: `<ol>
  <li>输入公历生日的月份与日期，点击“计算”。</li>
  <li>输出对应星座；星座按公历日期划分，与农历无关。</li>
</ol>`,
  faq: [{"q":"星座按农历还是公历？","a":"按公历。如果只记得农历生日，请先换算成公历（可用本站“农历换算”）。"},{"q":"交界日怎么算？","a":"以当日 0 点划分，如 8 月 23 日 0 点起是处女座，8 月 22 日是狮子座。"}],
};
