/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'zodiac-age',
  name: '生肖年龄速查',
  desc: '生肖年龄速查：输入出生年份得生肖、周岁与虚岁。',
  keywords: '生肖年龄,年龄生肖,周岁虚岁,属相查询,年龄计算,属相年龄',
  category: 'date',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field">
  <label for="ci-0">出生年份</label>
  <input type="number" id="ci-0" value="1995" placeholder="">
</div><div class="field">
  <label for="ci-1">参考年份</label>
  <input type="number" id="ci-1" value="2026" placeholder="">
</div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">默认参考今年；生肖按农历年份简化对应。</div>
<script type="application/json" id="c-cfg">{"lib":"life2","fn":"zodiacAgeCalc","unit":""}</script>`,
  usage: `<ol><li>输入出生年份（与参考年份），点击“计算”。</li><li>得到生肖、周岁与虚岁。</li><li>填写资料、传统文化交流常用。</li></ol>`,
  faq: [{"q":"周岁虚岁怎么算？","a":"周岁=参考年-出生年；虚岁=周岁+1（传统出生算 1 岁）。"},{"q":"春节前出生生肖？","a":"本工具按公历年份简化；精确生肖以农历正月初一划分。"}],
};
