/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'zodiac-dates',
  name: '星座日期表',
  desc: '十二星座日期与元素速查：日期范围、四象属性与性格。',
  keywords: '星座日期,十二星座,星座表,星座属性,星座大全',
  category: 'ref',
  kind: 'table',
  
  table: { columns: [{"key":0,"label":"星座","swatch":false,"mono":false},{"key":1,"label":"日期","swatch":false,"mono":false},{"key":2,"label":"元素","swatch":false,"mono":false},{"key":3,"label":"性格","swatch":false,"mono":false}], search: "输入星座（白羊）或日期过滤…", dense: true },
  body: ``,
  usage: `<ol><li>速查星座日期表。</li><li>搜索支持按关键词过滤。</li><li>日常开发与学习快速参考。</li></ol>`,
  faq: [{"q":"星","a":"座"},{"q":"四","a":"象"}],
};
