/* @generated by scripts/gen-tools.mjs —— 手改请同步到 tool-data 定义 */
export default {
  slug: 'zodiac-match',
  name: '星座配对',
  desc: '星座配对测试：输入两个星座查看契合度，附星座速配参考。',
  keywords: '星座配对,星座速配,星座匹配,情侣星座,星座缘分,星座测试',
  category: 'life',
  kind: 'calc',
  
  
  body: `<div class="calc-form">
<div class="field"><label for="ci-0">星座一</label><select id="ci-0"><option value="白羊座" selected>白羊座</option><option value="金牛座">金牛座</option><option value="双子座">双子座</option><option value="巨蟹座">巨蟹座</option><option value="狮子座">狮子座</option><option value="处女座">处女座</option><option value="天秤座">天秤座</option><option value="天蝎座">天蝎座</option><option value="射手座">射手座</option><option value="摩羯座">摩羯座</option><option value="水瓶座">水瓶座</option><option value="双鱼座">双鱼座</option></select></div><div class="field"><label for="ci-1">星座二</label><select id="ci-1"><option value="白羊座">白羊座</option><option value="金牛座">金牛座</option><option value="双子座">双子座</option><option value="巨蟹座">巨蟹座</option><option value="狮子座" selected>狮子座</option><option value="处女座">处女座</option><option value="天秤座">天秤座</option><option value="天蝎座">天蝎座</option><option value="射手座">射手座</option><option value="摩羯座">摩羯座</option><option value="水瓶座">水瓶座</option><option value="双鱼座">双鱼座</option></select></div>
</div>
<div class="toolbar">
  <button id="c-run" class="btn">计算</button>
  <span class="spacer"></span>
  <button data-copy-from="#c-out" class="btn btn-ghost btn-sm">复制结果</button>
</div>
<div class="output">
  <div class="output-label">计算结果</div>
  <pre id="c-out">等待输入…</pre>
</div>
<div class="note">按传统星座速配表判定（火象配风象等），仅供参考。</div>
<script type="application/json" id="c-cfg">{"lib":"life","fn":"zodiacMatch","unit":""}</script>`,
  usage: `<ol>
  <li>选择两个星座，点击“计算”。</li>
  <li>查看组合评价：天生一对 / 有火花也有摩擦。</li>
  <li>娱乐向测试，感情还需真实相处。</li>
</ol>`,
  faq: [{"q":"速配表依据是什么？","a":"沿用占星传统：火象（白羊/狮子/射手）配风象（双子/天秤/水瓶），土象配水象等。"},{"q":"同星座怎么算？","a":"按“同星座默契但个性相近，注意互补”处理。"}],
};
